### ISSUE TITLE
Removing extra characters on SIM Bank screen not intuitive

### ISSUE THREAD

**Issue by cliftona-hursley** [galasa-dev/projectmanagement#1]
Having started SIMBank running I connected to it using a PECOM session and connected though to the simulated CICS screen.

At this stage I got distracted onto something else and on return saw a CICS logo, cleared the screen,  typed "cemt inq task" and pressed enter. 

Apart from a brief "x-System" at the bottom, nothing seemed to happen and after a bit of thinking I remembered this was a SimBank session and I should have entered BANK so I:

Pressed clear - nothing happened
Pressed F3 - nothing happened
Deleted all the characters, type bank and pressed enter - screen changed to have "bank inq task" and nothing else happened.

During a recreate of this, no messages were issued to my SimBank console.

I was finally able to continue by overtyping the "inq task" with spaces and pressing enter.

Obviously this is a simulation so does not have to be perfect and there are many things it could do:, 

a) Invalid input could result in the data being removed from the screen and issue a message to the screen that xxx was invalid.
b) Recognise and process clear and f3 keys being pressed (perhaps an error for any other key).
c) Mimic CICS behaviour more closely and take the first word of input or its first four characters if longer. Then my unintentional "bank inq task" would be seen as "bank" with some ignored input.(Perhaps with a) above also incorporated).

**Comment by Michael-Baylis** [comment]
I have a funny feeling that if you type anything other than BANK,   it simply returns the screen.   Which would explain what you see.
Need to put in the the unrecognised message.   to indicate we are hearing you

**Comment by Michael-Baylis** [comment]
Yep,   checked the code.   it's in a while(true) {} loop.   will get that modified soon

**Comment by Michael-Baylis** [comment]
@cliftona-hursley this should be in place.   you will need to update the plugin from the https://p2snapshot.galasa.dev.

Would you please verify.   I am closing the this issue.    If there is a problem still,  please comment here and I will re-open the iisue
