### ISSUE TITLE
Step 5 of https://galasa.dev/docs/running-simbank-tests/simbank-IVT not accurate

### ISSUE THREAD

**Issue by Earthy707** [galasa-dev/projectmanagement#1003]
Step 5 of https://galasa.dev/docs/running-simbank-tests/simbank-IVT does not accurately represent what is shown on the screen during the set up of run configuration for SimBank IVT

**Comment by hobbit1983** [comment]
Thanks Callum - can you go ahead and fix this issue and then raise a PR for @CaroMac to review please
