### ISSUE TITLE
Test the new Helm charts

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1004]
Test the Helm charts for the Galasa ecosystem.

Instructions at can be found at:-

https://github.com/galasa-dev/helm/tree/release

The values file is currently set for Hursley working, I will modify this before release to be more generic.

**Comment by Jimbo4794** [comment]
Opened #1005 #1006 #1007

Leaving open for second review

**Comment by Jimbo4794** [comment]
Changes complete and issues resolved. 
Tested:
Basic install
Deployment of test stream and sample tests
Run sample tests through eclispe
Upgrade mechanisms ensuring we dont loose any stream or test data
