### ISSUE TITLE
Docker Image name repository

### ISSUE THREAD

**Issue by rsomers1998** [galasa-dev/projectmanagement#101]
The use of `/library` or other prefixes (when needed) is unclear and confusing, especially in cases where there is no repository for the image (eg. on artefactory)

**Comment by Michael-Baylis** [comment]
This is more a confusion with docker than galasa.    the whole repository stuff is not clear in the docker documentation.   the point of library,  only relates to dockerhub and the official public images

**Comment by Jimbo4794** [comment]
So is this something we just want to add to documentation?

I know dockerhub supports the use of "repository namespaces", but dont know about things like artefactory and sonartype nexus do.

When I reference images on our local artefactory I dont include any repo namespace and just the image name like: exampleName:latest

But then using dockerhub you HAVE to have the repo namespace, and in the case where it is a dockerhub standard image you use the library repo namespace. (E.g library/httpd:latest or sonatype/nexus3:latest)

I have not tested on any others.

**Comment by Michael-Baylis** [comment]
the repository namespaces can be viewed as "folders".   Artifactory and Nexus support it.  However,  I don't believe we need to change the documentation.   Anyone familiar with docker should know this.   The only thing we needed to point out is "library" needs to be included.

**Comment by Jimbo4794** [comment]
Ok, think im fine with that. What do we want to do with this item, do we want to add a documentation label?

**Comment by Michael-Baylis** [comment]
if richard is happy,  close
