### ISSUE TITLE
Helm Install - Bootstrap requires post install setup after upgrade

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1010]
An upgrade now works but the bootstrap reverts to:
```
#Galasa Bootstrap Properties
#Wed May 25 15:51:35 UTC 2022
framework.extra.bundles=dev.galasa.cps.etcd,dev.galasa.ras.couchdb
framework.config.store=etcd\:http\://etcd\:2379
```
rather than containing external information for the cofiguration store

**Comment by Michael-Baylis** [comment]
had to add post-setup to the upgrade and rollback hooks.
Not happy with this as would prefer helm didn't upgrade the configmaps as any changes the user makes will be lost.
New chart 0.0.5
