### ISSUE TITLE
CICSTerminals screens not stored in test stored artifacts like 3270Terminal

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1012]
When running a Galasa test with a standard z/OS 3270 terminal and a CICS Terminal, in the stored artifacts in the test run editor I can see the z/OS 3270 screens saved, but not the CICS Terminal screens.

**Comment by hobbit1983** [comment]
@lewisja1406 this is going to sound weird - but stick with me - can you run at least 10 screens through the ICICSTerminal object and see if it then gets 'some' data persisted

**Comment by lewisja1406** [comment]
Nope still nothing, been driving CES with around 15 screens in the run in total and not storing still

**Comment by lewisja1406** [comment]
Retesting it does work after 10 screens have been driven. The terminals appear under zos3270 tab in stored artifacts. If there is less than 10 however, this does not get stored.

**Comment by hobbit1983** [comment]
So the core issue here is that the CicsTSManager doesn't directly use the Zos3270Manager to provision a terminal, it instead directly uses the TerminalImpl class.  The Implementation will empty the terminal cache to the RAS every 10 screens.  However the Zos3270Manager will also flush the cache to the RAS before it disconnects the terminal at the end of the test.  The CicsTSManager doesn't.  So we either need to allow the CICSTsManager to use the Zos3270Manager to allocate a terminal OR ensure the CICSTsManager empties the cache

**Comment by hobbit1983** [comment]
We've not seen this when running a test because we use > 10 screens

**Comment by hobbit1983** [comment]
PR for fix to this issue is here https://github.com/galasa-dev/managers/pull/778

**Comment by hobbit1983** [comment]
done
