### ISSUE TITLE
Performing multiple CICS terminal operations eventually returns ITerminal disallowing certain functions

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1013]
I was writing a test to drive the CECI screen through the 3270 terminal. 
I have used a ICicsTerminal object 

`cicsTerminal.resetAndClear().type("CECI").enter().waitForTextInField("USER").pf3().wfk().clear().wfk()`

`.resetAndClear()` returns the ICicsTerminal but `.type()`returns ITerminal which is the super class of ICicsTerminal. 

When I then try to later reference `.resetAndClear()` it doesn't allow me so I have to use `.pf3() `and `.clear()` instead.

**Comment by hobbit1983** [comment]
the resetAndClear method is in ICicsTerminal while all the other methods are in ITerminal.  However your base object is going to remain an ICicsTerminal so either explicit casting or ending the line with a `;` and starting a new line with the cicsTerminal will get you around the problem.

**Comment by hobbit1983** [comment]
bounced an idea around with Mike and think that we have a solution using generics that would help here - so re-opening

**Comment by Michael-Baylis** [comment]
been wrapping my head around this for a couple of hours and decided we cannot do this using generics.   The only way is by stubbing all the fluent methods in Terminal inside CicsTerminal.  Although, nearly all the methods will be like this:-

public y xxxx() {
     super.xxxx();
     return y;
}

Which would be 48 of them.    I am willing to do it.   BUT,   if ITerminal is modified with a new fluent,  it won't cause a compile failure.   to keep the fluent chain, we would need to remember to add it to the inheriting class.

reference: https://stackoverflow.com/questions/23731270/fluent-api-with-inheritance-and-generics

@hobbit1983 I believe it is acceptable to have this overhead as at some point zos3270 will be stable, do you agree?
