### ISSUE TITLE
Text output from the secvuln ossindex should provide additional diagnostic information

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1017]
As a diagnostic aid,  the console output for the secvuln ossindex should provide additional information other than just:-

Exported security vulnerability report to results

eg

Exported 999 security vulnerabilities from 999 maven projects to file xxxxx.yaml

that way if the xxxx.yaml does not contain what we expected, we get confirmation that we scanned the right place etc.

**Comment by jadecarino** [comment]
The output for the secvuln ossindex command now prints:
xx Galasa projects processed
xx vulnerabilities found
Exported security vulnerability report to xxxx.yaml
Hopefully that provides enough information.
