### ISSUE TITLE
console output from secvuln maven should include project count

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1018]
at the moment the command lists the projects and displays the message:-

Security scanning project pom.xml updated

how about 

Security scanning project pom.xml created with 999 modules.

That way we can tie it up with the next command to ensure the correct counts are flowing through the workflow

**Comment by jadecarino** [comment]
This is done - the output of the secvuln maven command now lists all processed projects and then the amount of projects processed into pseudo maven projects. The secvuln ossindex command then prints the amount of processed projects for the yaml, and this number should match up with the last.
