### ISSUE TITLE
secvuln maven pom.xml output should include the dep:tree plugin on the validate phase

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1019]
to run the maven command I need to do:-

mvn validate dependency:tree -DoutputFile=deps.txt -DoutputType=dot

"mvn validate" should be enough.  Therefore add the dependency:tree and properties to the <build><plugins> list to run as part of the validate phase.

**Comment by jadecarino** [comment]
This is done - https://github.com/galasa-dev/buildutils/blob/main/pkg/cmd/secvulnMaven.go lines 263 - 277 add the needed properties to the pom so mvn validate is all that's needed
