### ISSUE TITLE
panic receive during secvuln command

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1024]
getting:-

[../bin/galasabld-darwin-amd64 secvuln ossindex --parent maven --output results]
Galasa Build - Security Vulnerability OSS Index - version 0.0.7
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
galasa.dev/buildUtilities/pkg/cmd.scanAuditReportForVulnerabilities({0xc000140000, 0x2f01, 0x2f02}, {0xc0000aa9f0, 0x21})
	/Users/mikebyls/git/prs/buildutils/pkg/cmd/secvulnOssindex.go:115 +0x918
galasa.dev/buildUtilities/pkg/cmd.walkFunc({0xc0000a0340, 0x3a}, {0x1465c68, 0xc00012d1e0}, {0x0, 0x0})
	/Users/mikebyls/git/prs/buildutils/pkg/cmd/secvulnOssindex.go:80 +0x1a5
path/filepath.walk({0xc0000a0340, 0x3a}, {0x1465c68, 0xc00012d1e0}, 0x13fba68)
	/usr/local/Cellar/go/1.17.6/libexec/src/path/filepath/path.go:418 +0x125
path/filepath.walk({0xc0000aa960, 0x28}, {0x1465c68, 0xc00012d110}, 0x13fba68)
	/usr/local/Cellar/go/1.17.6/libexec/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc0000aa810, 0x21}, {0x1465c68, 0xc00012cea0}, 0x13fba68)
	/usr/local/Cellar/go/1.17.6/libexec/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0x7ffeefbffa88, 0x5}, {0x1465c68, 0xc00012c270}, 0x13fba68)
	/usr/local/Cellar/go/1.17.6/libexec/src/path/filepath/path.go:442 +0x28f
path/filepath.Walk({0x7ffeefbffa88, 0x5}, 0x13fba68)
	/usr/local/Cellar/go/1.17.6/libexec/src/path/filepath/path.go:505 +0x6c
galasa.dev/buildUtilities/pkg/cmd.findAuditReports({0x7ffeefbffa88, 0x5})
	/Users/mikebyls/git/prs/buildutils/pkg/cmd/secvulnOssindex.go:60 +0x31
galasa.dev/buildUtilities/pkg/cmd.secvulnOssindexExecute(0x16be560, {0x13d3d60, 0x4, 0x4})
	/Users/mikebyls/git/prs/buildutils/pkg/cmd/secvulnOssindex.go:50 +0x89
github.com/spf13/cobra.(*Command).execute(0x16be560, {0xc0000cc480, 0x4, 0x4})
	/Users/mikebyls/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x16bfe60)
	/Users/mikebyls/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mikebyls/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
galasa.dev/buildUtilities/pkg/cmd.Execute()
	/Users/mikebyls/git/prs/buildutils/pkg/cmd/root.go:22 +0x25
main.main()
	/Users/mikebyls/git/prs/buildutils/cmd/galasabld/main.go:20 +0x6a

using the following script:-

#!/bin/bash

rm -rf maven
mkdir maven

../bin/galasabld-darwin-amd64 secvuln maven --parent maven --pom https://galasadev-cicsk8s.hursley.ibm.com/main/maven/obr/dev/galasa/dev.galasa.uber.obr/0.24.0/dev.galasa.uber.obr-0.24.0.pom --repo https://galasadev-cicsk8s.hursley.ibm.com/main/maven/obr --repo https://repo.maven.apache.org/maven2

cd maven

mvn validate dependency:tree -DoutputFile=deps.txt -DoutputType=dot

cd ..

../bin/galasabld-darwin-amd64 secvuln ossindex --parent maven --output results

../bin/galasabld-darwin-amd64 secvuln report --extract results --output md --acceptance file:acceptance.yaml

**Comment by jadecarino** [comment]
Can we close this @Michael-Baylis ?
