### ISSUE TITLE
Add Conversion plugin for RTCDefect

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1032]
Add a conversion plugin for the RTCDefect.

1. Straight swap for the import.
1. Straight swap for the actual annotation.   
1. Leave the githubid as default 
1. Leave the repository as default
1. Convert defect to "issue", as a string (future proofing).
1. Copy the RTC defect number across, even though it is not valid.  It will be updated manually in the future.
1. Add a TODO comment above the annotation to say "raise an covering issue or remove annotation and import".
1. Convert Regex if present.

**Comment by hobbit1983** [comment]
@jadecarino this is now done I think so moving it to the correct swim lane :P
