### ISSUE TITLE
Document the new GitHubIssue Manager

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1033]
Document the new GitHubIssue Manager

1. Detail annotation
1. Detail CPS properties
1. Provide examples

**Comment by jadecarino** [comment]
I have been working with Caroline to start documentation of the GitHubIssue manager

**Comment by hobbit1983** [comment]
@jadecarino is there a PR for this to review?

**Comment by jadecarino** [comment]
@hobbit1983  Caroline has an open PR - https://github.com/galasa-dev/galasa.dev/pull/404 Looks like your review is pending

**Comment by hobbit1983** [comment]
Thanks - will review now

**Comment by hobbit1983** [comment]
@CaroMac I've requested changes on the PR for that issue.  Thanks for writing it up - it is a difficult concept to get across

**Comment by CaroMac** [comment]
@hobbit1983 Thank you for the review. The comments are very valid and useful. I will make the updates when I am back in the office next week.
