### ISSUE TITLE
Convert Priority annotation

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1034]
Add a conversion plugin to strip the com.ibm.cics.jatp.annotations.Priority annotation from the test,   both the import and the annotation itself.   Not required anymore

**Comment by lewisja1406** [comment]
I have added a new method to the source converter to remove an annotation. Simply put, the input parameter is the annotation in this case `com.ibm.cics.jatp.annotations.Priority` it then iterates through all annotations within the source which belong to the passed input parameter. It then removes it if it matches.

**Comment by lewisja1406** [comment]
PR raised in https://github.ibm.com/CICS/galasa-jat-conversion/pull/30

**Comment by hobbit1983** [comment]
Hey @lewisja1406 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/galasa-5dc3f56cf3f3b50001ac0432/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
