### ISSUE TITLE
Add conversion plugin for CSDInput and CSDInputs

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1035]
I believe the code in the SEM Manager is there and working correctly for CSDInput and CSDInputs, so all that is needed is to write the conversion plugin.

Essentially you can copy the SITGroup and SITGroups plugin and modify it for CSDInput.

Afterwhich,  test with a dummy project and check that it works correctly under Galasa after the conversion.

**Comment by hobbit1983** [comment]
@james-ashman if you are working on this work item can you log onto zen hub please and move it to the correct swim lane - just helps to keep tabs on what is being done - thx

**Comment by hobbit1983** [comment]
right - @james-ashman get that merged please sir

**Comment by hobbit1983** [comment]
@james-ashman can you close this work item if done please?
