### ISSUE TITLE
Perform automatic analysis of OSS inclusion for early warning

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#104]
Write 2 maven goals, as a CICS tool,  not a Galasa tool.

The first goal will extract all the dependencies from a maven project and it's sub modules.   Classify them as a "compile" dependency or an "inclusion" dependency.   "inclusion" means the jar is included in the artifacts Galasa distributes.  "compile" means only used during the build process.  This will include Eclipse projects.
Note,  this should include those artifacts that are in the assembly plugin and copy dependencies.

Build a YAML file with all the deps and versions.   Include what Pedigree authorisation is, you may need to translate the maven artifactid to a pedigree name, via another yaml file.   

The goal will be run several times against multiple parent projects.   So a second maven goal will need to be written to merge and remove duplicates.

Once the master YAML file is produced, this needs to be compared with the previous extraction that has been stored in a github repo, probably the projectmanagement repo.
If there are difference,  they should be highlighted and the goal should be failed.

**Comment by Roavill2** [comment]
WICKED CLI tool found that carries out this task. Work no longer required.
