### ISSUE TITLE
3270 Manager enhancements for Batch 01

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#1049]
Methods and annotations enhancements to enable conversion of batch 1 projects

    sendKey
    Key.*
    searchText(*)
    extractScreen
    sendTextWithEnter
    resetAndClearScreen
    detectVamp
    getScreenApplid
    connect
    searchForPattern
    ConnectApplid
    captureScreen
    sendKeyNoWait
    isConnected
    resetAndClearScreenIfConnected
    sendTextToLocation
    

more to come for B1

**Comment by lewisja1406** [comment]
Initial searchText code is into review. Need advice but the core functionality works. I will then move onto the further functions required for batch 1
