### ISSUE TITLE
No acknowledgement of WHICH method when a method is ignored by the framework

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1053]
When we have a method which is ignored by the framework the test log looks as follws.

`----------------------- ****************************************************************************************************
----------------------- *** Start of test class dev.galasa.simbank.tests.Plex2Test
----------------------- ****************************************************************************************************
19/07/2022 11:50:07.775 INFO  d.g.f.GenericMethodWrapper - Starting
----------------------- ****************************************************************************************************
----------------------- *** Start of test method dev.galasa.simbank.tests.Plex2Test#testSRR0Tran,type=Test
----------------------- ****************************************************************************************************
19/07/2022 11:50:07.784 INFO  d.g.f.GenericMethodWrapper - Ending
----------------------- ****************************************************************************************************
----------------------- *** Passed - Test method dev.galasa.simbank.tests.Plex2Test#testSRR0Tran,type=Test
----------------------- ****************************************************************************************************
19/07/2022 11:50:07.787 INFO  d.g.f.TestRunManagers - Ignoring method due to Target CICS Release (V730(Hobson - 5.6.0)) earlier than @CICSMinimumRelease(V750(Emerald - 6.2.0))
19/07/2022 11:50:07.805 INFO  d.g.f.TestClassWrapper - Ending
----------------------- ****************************************************************************************************
----------------------- *** Passed - Test class dev.galasa.simbank.tests.Plex2Test
----------------------- ****************************************************************************************************
19/07/2022 11:50:07.821 INFO  d.g.f.TestRunner - Starting Provision Stop phase
19/07/2022 11:50:07.821 INFO  d.g.f.TestRunner - Starting Provision Discard phase
19/07/2022 11:50:07.961 INFO  d.g.f.Framework - Shutting down the framework
19/07/2022 11:50:07.961 INFO  d.g.f.Framework - Framework shutdown`

My test looks as follows:

Plex2Test.java
  testSRR0Tran()
  testtest()

There is no indication as to what test is ignored just the fact that one has. We should change the invocation of the ignore method to happen after the test has started so we get the START OF TEST METHOD asterisk block

**Comment by jadecarino** [comment]
I believe to solve this there needs to be a change made in the framework (GenericMethodWrapper) as there is no logging if a method is ignored, we perhaps need to log a different kind of message to the console to indicate there was a method, but we have chosen to ignore:
Result ignored = managers.anyReasonTestMethodShouldBeIgnored(new GalasaMethod(this.excecutionMethod, null));
            if (ignored != null) {
                this.result = ignored;
                this.testStructureMethod.setResult(this.result.getName());
                return;
            }
            managers.fillAnnotatedFields(testClassObject);
            managers.startOfTestMethod(new GalasaMethod(this.excecutionMethod, (testMethod != null ? testMethod.excecutionMethod: null)));

            logger.info(TestClassWrapper.LOG_STARTING + TestClassWrapper.LOG_START_LINE + TestClassWrapper.LOG_ASTERS
                    + TestClassWrapper.LOG_START_LINE + "*** Start of test method " + testClass.getName() + "#"
                    + excecutionMethod.getName() + methodType + TestClassWrapper.LOG_START_LINE
                    + TestClassWrapper.LOG_ASTERS);
