### ISSUE TITLE
Galasa Eclipse Run Editor SEM/CICS Stored Artifact view needs tidying

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1056]
The SEM->CICS view in a galasa test run editor view in Eclipse is really convoluted when you have several CICS regions and perform shutdown and startups. This should probably mirror the same view that JAT had where there was a folder for each job and each SYSOUT / job output was under said tab.

See image below. The galasa view has a flat view with no tabs.

![image.png](https://images.zenhubusercontent.com/62c308c5f37136426fbb9f37/db616d30-e322-4d1a-8594-a6b63e1113cb)

**Comment by Michael-Baylis** [comment]
I agree

**Comment by lewisja1406** [comment]
There are a lot of random artifacts which are empty too.... This really needs to be looked at

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
