### ISSUE TITLE
CiP Testing of the Docker Manager for Release status

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#106]
This issue is to cover the sign off of the Docker Manager for release status.

If CiP are happy with documentation and the state of the Manager then this issue should be closed with comments covering what has been or has not been done.

**Comment by Michael-Baylis** [comment]
I don't believe addition CiP testing is required for this Manager.   The Beta level testing would only be repeated.

I also believe the reference page is sufficient documentation as anyone who knows Docker will understand the annotations and interfaces.  The general "how to write a test" topics will cover the Galasa specifics of using a manager.

**Comment by JonCollettIBM** [comment]
Hi
I don't represent CiP exactly..... but the testing that I have performed (within the remit of testing the doc from the perspective of a user unaquainted with JAT) was reading the new auto generated reference pages, which all appeared OK to me. 
As there are no additional doc changes or changes to the supplied Simbank tests, relating to Docker Manager, in this release and given Mike's statement above, I am happy to go to release and close this task.
