### ISSUE TITLE
Accessing the resources folder using artifact manager

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1063]
Found whilst converting Interval Control tests... in this example using

@SemTopology(model = "/sem/ThreeRegion.sem")

The implementation goes off to Artifact manager to get the test bundle resources. It then prefxies the path for the file with resources so we end up looking for /resources/sem/ThreeRegion.sem - again this is fine.

The problem is our maven project is setup like this... 

src/main/java (where our test code lies)
src/main/resources (where we have put ThreeRegion.sem)

Our artifact manager cannot find ThreeRegion.sem and the only way to fix this was to create a sub folder within src/main/resources to have ANOTHER resources folder. This then worked.

So we ended up with src/main/resources/resources/sem/ThreeRegion.sem 

We should look at why this is the case and clean this up so we don't need to have two resources folders. We should just be able to use the parent one.

**Comment by hobbit1983** [comment]
I've taken a look at this.  The root of the directory should be src/main/resources. However when artifactManager 'normalises' the filename it adds an extra 'resources' to the beginning of the path, causing the double resources/resources. If we do not normalise the path then things work as they 'should

**Comment by hobbit1983** [comment]
Looking at why this is.  Although in the source the path /src/main/resources exists, in the compiled bundle the content of the resources folder is at the root of the bundle.

**Comment by hobbit1983** [comment]
This appears to prove that point http://www.avajava.com/tutorials/lessons/where-do-i-put-resources-in-my-maven-project.html

**Comment by hobbit1983** [comment]
AHAH in JAT we weren't using proper maven projects and so never had a src/main/resources folder and instead by internal convention had a 'resources' folder in the root directory.  In that case it made 'sense' to have artefact manager add `resources` to the start of the path if it wasn't there.  However now we have 'proper' maven projects that needs to change.  Ive also checked that this is true for gradle projects

**Comment by hobbit1983** [comment]
rolled this out across all the managers and ready for integration test and a review

**Comment by hobbit1983** [comment]
well not quite - I have forgot to bump all the versions of affected managers, update release.yaml and also the copyright tool is not happy :(

**Comment by hobbit1983** [comment]
All contributed but has broke some stuff in the CICSTS Internal manager that I need to resolve - and build etc
