### ISSUE TITLE
Symbolics for areas such as ZosIpPort, HLQ, Test Name and other test meta data

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1064]

**Comment by hobbit1983** [comment]
@lewisja1406 @Jimbo4794 have spent a while discussing this.  We have the following design:

The SEMInternalManager in Galasa currently asks the questions of managers that it will need information from such as getting the hlq from z/OS Manager.  We will extend this to the managers that we know SEM will need information from and force SEM to ask the manager through the SPI.  In this specific case adding a new method i.e:
HashMap<String, Integer> :: zosIPPort.getProvisionedPortNumbers()
We will also change the @Port annotation to remove the symbolic attribute as it stands in JAT and replace it with @Tag which is used by other annotations.  The benefit of this approach is:
1. No leaking of internal provisioning information into the external code base
2. No cache of data in the framework of provisioned information
