### ISSUE TITLE
ID sign off of the Docker Manager for Release status

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#107]
This issue is to cover the signoff of the ID team that they are happy with the level of documentation for the Docker Manager.   Any tutorials, SimBank enhancements etc.

If ID are happy with the Manager, this issue should be closed with qualifying comments

**Comment by Michael-Baylis** [comment]
I don't believe we need any tutorials or simbank enhancements.   If you know Docker,  you will know instinctively what the manager is providing and what all the annotations and interfaces mean.

**Comment by CaroMac** [comment]
Happy with the current level. If new ideas for enhancements arise we can raise a new issue. Will therefore close this issue.
