### ISSUE TITLE
Document the examples via Javadoc

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1075]
A lot of the examples have a "story" behind them. For example the batch test shows how to use the batch manager but also why you SHOULDNT hard code the accounts. Can you please add Javadoc style comments to the top of the test classes to tell the story of each case to make sure bad practises are also highlighted.

**Comment by AaronJhaj** [comment]
Adding comments to BatchAccountsOpenTest

**Comment by AaronJhaj** [comment]
Added javadoc comments to BatchAccountsOpenTest and merged to main. 
Adding javadoc comments to the other simbank test classes.

**Comment by hobbit1983** [comment]
@AaronJhaj if this is in review - can you post a link to the PR that has a review on it so we can move this forward?
