### ISSUE TITLE
Test dataset load library not added to DFHRPL of SEM complex JCL

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1078]
When a @ZosProgram is compiled it goes to a load library of 

USERID.GALASA.RUNID.LOAD

This is not concatenated in the DFHRPL of the SEM complex JCL

**Comment by lewisja1406** [comment]
@Jimbo4794 Can we talk about this today at some point plz

**Comment by hobbit1983** [comment]
@Jimbo4794 @lewisja1406 what's the next step for this work item, was there an outstanding issue we still needed to resolve?

**Comment by lewisja1406** [comment]
Yes. So at the moment there is no issues with this particular code change. However if we want to do the ZosProgramHandler to control the compilation of programs etc then this implementation will not work as the load library probably won't be populated with the compiled program members and SEM will build the complex before this happens. 

One solution we spoke about was creating the dataset early on so even if its empty, we can still include it in the DFHRPL when SEM builds the JCL. (I believe this is what JAT does)

**Comment by hobbit1983** [comment]
This is the current scenario:

ZosProgramManager contains an attribute on the annotation for load lib.  If this is not specified then the default of `ZosManager.getRunDatasetHLQ() + ruined + ".LOAD"` is used.  

@StartOfTestClass ZosProgramManager loops through the ZosPrograms and compiles what it needs to.  As part of this compile, the load lib is tested and created if it doesn't already exist.  Thus if another manager tries to access the load lib BEFORE startOfTestClass then it will not already exist and cause failures.

All the CICS Managers (inc SEM and CICSTSProv) are not dependent on the ZosProgramManager.  

The Solution (IMO) is to make the SEMManager dependent on ZosProgram.  Require ZosProgram to allocate the loadlibs that it might use BEFORE @startOfTestClass and then in the SPI allow the SemManager to retrieve the list of loadlibs from zosProgram.  It might also be a good idea to ask for the loadlibs for programs that are CICS programs or similar.

**Comment by hobbit1983** [comment]
so if we agree on this I suggest we create a new issue to cover the changes described above and implement them for iteration 2?  @lewisja1406 @Jimbo4794 @jadecarino do you agree?

**Comment by lewisja1406** [comment]
I agree with the proposed solution. As I am not massively factored in, in iteration 1 this is something I could tackle before iteration 2? Let me know whats best

**Comment by jadecarino** [comment]
Happy with that solution nothing in there I disagree with
