### ISSUE TITLE
Go/NoGo for WebUI

### ISSUE THREAD

**Issue by NohWayJose** [galasa-dev/projectmanagement#108]
Quick due dilligence to make sure customers will be happy to work with a web UI rather than IDEs.
(tempered by Galasa team's resource constraints for producing IDE plugins)

I expect they will be OK with WebUI but must check

Set aside time in Sponsor user calls to ask

**Comment by Michael-Baylis** [comment]
Needs to be clear that the WebUI is for automation runs only.

Development and local running of tests still remain in the IDE of choice.  We will likely have a option to submit runs, monitor and view results in the IDEs,  but everything else is likely to be in the WebUI,  like configuration and resource management.

**Comment by lubelg** [comment]
Had so many positive responses to all Galasa interactions that I believe we can close this as done - 'Go'
