### ISSUE TITLE
TestRunHeartbeat updated by another process during local run

### ISSUE THREAD

**Issue by lewisja1406** [galasa-dev/projectmanagement#1080]
Around 1/4 times of running a Galasa test locally, I am seeing the following issue interupt and terminate a test run.

```
18/08/2022 13:35:32.748 FATAL Thread-1 dev.galasa.framework.TestRunHeartbeat.setHeartbeat - The run heartbeat has been updated by something else
18/08/2022 13:35:32.749 FATAL Thread-1 dev.galasa.framework.TestRunHeartbeat.setHeartbeat - Cannot allow provision discard to run as this could affect the other engine
```

This causes the test to abort and no clean up occurs. We need to investigate the underlying cause as there is no diagnostics to help understand what may be updating the test. This is happening very often and will be a problem for JAT-Galasa.

**Comment by Jimbo4794** [comment]
Looks like it was network latency from Lewis not using the proper network on site, so was using a slow Wifi and a VPN which was taking longer than 10s in some instances, which was enough to make RESMON clean up the run.
