### ISSUE TITLE
Document WebAppIntegrationTest

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1095]
Document this simbank test - Aaron has sent notes on how he got this running.

**Comment by hobbit1983** [comment]
@Jimbo4794 what's blocking this?

**Comment by CaroMac** [comment]
Additional info re doc - First pass documentation complete and reviewed by Aaron. Possible changes required due to changes that Aaron is continuing to make. Final review then required.

**Comment by CaroMac** [comment]
going to review with Aaron on Tues and see if additions / changes are needed. Some work will need to wait until the infrastructure is complete (this work is currently blocked). So I will remove it from this sprint.
