### ISSUE TITLE
Move Core Manager to new Manager template structure

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1099]

**Comment by CaroMac** [comment]
New Manager template structure is here -
https://deploy-preview-365--galasa.netlify.app/docs/managers/manager-name

Example of new template used for GitHub Manager is here -

https://deploy-preview-404--galasa.netlify.app/docs/managers/github-manager#configuring

**Comment by CaroMac** [comment]
This issue is associated with the work on the credentials properties documentation. The idea is that this will help understand how to set up the core Manager in general but also tie in with the content on using the credentials properties.

**Comment by CaroMac** [comment]
Updated here https://deploy-preview-412--galasa.netlify.app/docs/managers/core-manager in PR https://github.com/galasa-dev/galasa.dev/pull/412

**Comment by CaroMac** [comment]
@hobbit1983 have updated and requested re-review. thank you.

**Comment by hobbit1983** [comment]
re-reviewed

**Comment by CaroMac** [comment]
reviewed and approved so will close and publish
