### ISSUE TITLE
Clean, document and improve the Tekton tasks and pipelines

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1108]

**Comment by hobbit1983** [comment]
@jadecarino @AaronJhaj Is this not done?

**Comment by hobbit1983** [comment]
@jadecarino @AaronJhaj Is this not done?

**Comment by jadecarino** [comment]
@hobbit1983 Apologies Will I have only just seen your comment above. Yes I'd class this as done, we have created generic tasks for everything we need, and I have documented them all on the automation repo, so closing this issue.
