### ISSUE TITLE
Move regression testing pipeline into CronJob managed in ArgoCD

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1114]
We should move the regression testing pipeline out of Jenkins, as jenkins engine has a static installation of galasactl which needs to be manually upgraded.

- Create cron job to run regression testing
- Develop galasabld command to take Json test output and report to Slack channel

**Comment by jadecarino** [comment]
@Jimbo4794 Can we close?

**Comment by hobbit1983** [comment]
@jadecarino yes I think this can close
