### ISSUE TITLE
zOS File method to retrieve and parse the current dataset attributes

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#112]
```
existingDataset.getDatasetOrganization()
existingDataset.getRecordFormat()
existingDataset.getRecordlength()
existingDataset.getBlockSize()
existingDataset.getUnit()
existingDataset.getSpaceUnit()
existingDataset.getPrimaryExtents()
existingDataset.getSecondaryExtents()
existingDataset.getDirectoryBlocks()
```
All these methods retrun null unless explicity set by their setters counterpart. It would be good for these methods to return the value returned by existingDataset.getAttibutesAsString(), if the dataset exists

**Comment by Michael-Baylis** [comment]
Need some form of "refresh" or "loadAttributes" method as the manager to get the current settings.

**Comment by DavidXRoberts** [comment]
done
