### ISSUE TITLE
Explore how to install the Galasa plugin into Neon

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#114]
Can't install into any release of IDz.  14.1 and 14.2 are neon based.

Need to bring a SCR and Jetty plugin.   Or jury rig it somehow.

Need to figure out how the same p2 site can be used for Neon and Oxygen+

**Comment by GeraldMit** [comment]
This can be closed. IDz 14.1 and 14.2 are both now End-of-Service, and Eclipse 4.6.3 (Neon) is archived.

**Comment by techcobweb** [comment]
Thanks Gerald. Closing.
