### ISSUE TITLE
Setup Galasa Core/Complete Build

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1147]
## Story
As a galasa developer, I want to trigger the chain of build pipelines to reflect source code changes throughout the project.

## Background
Refer to existing complete-build and runtime-build (main build) for help if needed.

The chain should stop at obr-generic if triggered from just a 'main' build.
A 'complete' build should be triggered manually, repos beyond obr-generic shouldn't be built every time there is a change to a repo.

Use a 'when' condition on the branch to determine whether a main or a complete build is happening. If branch=main, don't call eclipse from obr, that will stop the chain at obr-generic.

Use the tkn-cli task and refer to the completed pipelines/documentation for how to write the tkn command.

## Tasks
- [x] wrapping > gradle
- [x] gradle > maven
- [x] maven > framework
- [x] framework > extensions
- [x] extensions > managers
- [x] managers > obr (All completed as part of previous work item)
It gets a little trickier after this point, as there isn't a 1-1 link between the pipelines, but it should be okay, as obr-generic doesn't need to call anything, so that chain can stop there.
- [x] obr > obr-generic
- [x] obr > eclipse
- [x] eclipse > isolated

**Comment by Jimbo4794** [comment]
We need to move the helm charts and setup the argocd to create the core build for branches from this repository

**Comment by hobbit1983** [comment]
@Jimbo4794 @jadecarino What does this work item encompass - and is it already done - or no longer needed

**Comment by jadecarino** [comment]
If we want the Core Build to essentially be what the 'complete build' was, we need the Eclipse and Isolated pipelines done, and a 'Core Build' PipelineRun set up to call the following pipelines in order: wrapping, gradle, maven, framework, extensions, managers, obr, eclipse, isolated

**Comment by AaronJhaj** [comment]
for a 'complete' build on your own branch, eclipse build needs simplatform build so I am adding a trigger from obr > simplatform > eclipse > isolated
This chain is only triggered if branch != main

**Comment by AaronJhaj** [comment]
isolated deployments seem to not work when performing a build on your own branch and get a 404 error

**Comment by AaronJhaj** [comment]
complete build working on own branch
