### ISSUE TITLE
Migrate Docker Builds

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1151]

**Comment by Jimbo4794** [comment]
Need to open more items for this per repo we migrate. Going forward we want every tekton pipelines to clone the automation repo so it can access the dockerfiles to do the appropiate build. SO we need to move all the dockerfiles, required accessories and common resources to the automation repo

**Comment by techcobweb** [comment]
@Jimbo4794 is this not done already ?
