### ISSUE TITLE
Test should end if before class method fails

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#116]
If the @BeforeClass throws an exception, the test should fail and not attempt to run any other methods, i.e. @Before @Test.

Need to compare behaviour of @After and @AfterClass with JUnit

**Comment by Michael-Baylis** [comment]
Yep,  been meaning to sort this out for a very long time

**Comment by Michael-Baylis** [comment]
If a BeforeClass fails,  execution will stop,   but all AfterClasses will execute
If a Before fails,   the test will stop,  but the Afters for that test method will execute, but not for later test methods, and of course the afterclasses will run.
