### ISSUE TITLE
document credentials properties

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1170]
Work with Anthony Clay to document credentials properties

**Comment by CaroMac** [comment]
updated in this PR https://github.com/galasa-dev/galasa.dev/pull/412 and viewable here https://deploy-preview-412--galasa.netlify.app/docs/writing-own-tests/binding-tests

**Comment by hobbit1983** [comment]
@CaroMac reviewed

**Comment by CaroMac** [comment]
@hobbit1983 have updated and requested re-review. thank you.

**Comment by hobbit1983** [comment]
re-reviewed

**Comment by CaroMac** [comment]
Reviewed and approved. Link issue resolved so will close and publish.
