### ISSUE TITLE
CompilationLocalJava11Ubuntu test using outdated maven central.

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1174]
The CompilationLocalJava11UbuntuIsolated and CompilationLocalJava11UbuntuMvp test pass as they are given a maven repo as a file. However, the CompilationLocalJava11Ubuntu test fails as it looking at maven central repo. The maven central repo is potentially out of date as the error from the test states it cannot find the constructor for the Zos3270Terminal containing the textScanner - suggesting the version for the Zos3270Terminal manager needs to be updated in maven central.

**Comment by hobbit1983** [comment]
releasing 0.25.0 will fix this

**Comment by AaronJhaj** [comment]
annotated this test class with the GitHubIssueManager. The test should pass with the release of 0.25.0 but until then it will fail due to maven central version.

**Comment by AaronJhaj** [comment]
re-opened as GithubIssue annotation won't work unless issue is open

**Comment by techcobweb** [comment]
Need to re-factor the test to make it useful for us.
@hobbit1983 believes 0.25.0 will fix it. Is this true ?

**Comment by AaronJhaj** [comment]
currently have a pr open https://github.com/galasa-dev/integratedtests/pull/170
However,  currently not been able to test the changes due to credential issues and eclipse issues

**Comment by jadecarino** [comment]
Trying to run this locally has proved more challenging that I thought. I have been attempting to run this test locally from my command line using the command below:
`java -jar /Users/jadecarino/.galasa/lib/0.25.0/galasa-boot-0.24.0.jar --localmaven file:/Users/jadecarino/.m2/repository --remotemaven https://development.galasa.dev/main/maven-repo/obr --bootstrap file:/Users/jadecarino/.galasa/bootstrap.properties --overrides file:/Users/jadecarino/.galasa/overrides.properties --obr https://development.galasa.dev/main/maven-repo/obr/dev/galasa/dev.galasa.uber.obr/0.26.0/dev.galasa.uber.obr-0.26.0.obr --obr mvn:dev.galasa/dev.galasa.inttests.obr/0.26.0/obr --test dev.galasa.inttests/dev.galasa.inttests.compilation.simbank.local.online.CompilationLocalJava11Ubuntu`

**Comment by AaronJhaj** [comment]
I have made changes to AbstractCompilationLocalSimBank.java which this tests inherits. A grade.properties file is created which holds the main/maven-repo/obr location so any changes that effect simbank will be captured rather than only looking at maven central, relying on changes to be released - which is what initially caused this test to fail.
