### ISSUE TITLE
Create build-pr (pr-xxx) Pipelines for all core Galasa repos

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1186]
- Wrapping
- Gradle
- Maven
- Framework
- Extensions
- Managers
- OBR
- Eclipse
- Isolated

**Comment by hobbit1983** [comment]
@jadecarino @AaronJhaj should this be story pointed by itself or should we break it down?

**Comment by AaronJhaj** [comment]
@jadecarino we could split this into two items. One for each of us detailing the pipelines we are working on individually then equally story point them?
@hobbit1983 we thought splitting the item up into its individual pipelines would make the board a bit messy. what are your thoughts?

**Comment by hobbit1983** [comment]
@AaronJhaj I would suggest splitting this into 2 items, however if it's all going to get done by the end of this iteration - it's not a problem.  It does however need to be story pointed

**Comment by AaronJhaj** [comment]
I have created a new issue #1190 that is blocking the completion of these pipelines regarding the gpg problem.

**Comment by jadecarino** [comment]
This issue has been broken up into smaller issues for each pipeline, so closing as not needed and removing from all sprints
