### ISSUE TITLE
Add missing 3270 fuctions

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#119]
The following key functions are not available in the 3270 Manager:
- [x] Erase End of Field *
- [x] Home *
- [x] New Line *
- [x] Back Tab
- ~~Insert (On/Off)~~
- ~~Delete~~
- [x] Left/Right/Up/Down
- ~~Reset~~

Other useful functions:
- Move cursor to location (x, y)
- Retrieve cursor location ()
- Retrieve text at cursor location (x, y, length)

Review function provided by the PCOMM API and where appropriate, add to the 3270 manager.

* Would greatly simplify CECI Manager

**Comment by Michael-Baylis** [comment]
Cursor Left/Right/Up/Down are now supported

**Comment by Michael-Baylis** [comment]
@hobbit1983 From a test script point of view,  I don't think we need to implement character insert on/off and delete do we,   the tests will most likely replace the entire content of the field, insert/delete would just complicate matters.  After all, we are not testing 3270 here.

**Comment by Michael-Baylis** [comment]
Reset won't be implemented as it is not a 3270 datastream function.   it is an emulator to block the keyboard if you attempt to type some in the wrong place.  We throw exceptions instead

**Comment by hobbit1983** [comment]
@Michael-Baylis agree we can ignore character insert, unless someone specifically needs it.  I would expect most people (as you say) to want to replace the whole field

**Comment by Michael-Baylis** [comment]
Erase EOF is now there

**Comment by DavidXRoberts** [comment]
Agree not to implement insert/reset/delete.

**Comment by Michael-Baylis** [comment]
Home, backtab and newline is complete
