### ISSUE TITLE
Galasa Simbank tests get error with eclipse  2022-09

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1201]
Confirmed that this error is seen by @hobbit1983 on both  Java and Java EE flavours of eclipse.

Attempting to run the SimBank IVT tests gives this error
![simbank error ](https://user-images.githubusercontent.com/47417716/194590496-ee7c7784-14f1-4ec8-b095-f32aa3f8f51b.png)

**Comment by eamansour** [comment]
The source of this issue has been identified - a change to the m2e-core library removed the `getVersion()` method from the `ArtifactKey` class, which explains the error (see https://github.com/eclipse-m2e/m2e-core/commit/c3ade997e33c06d9a5863aa4985446bdb71e49a2#diff-793802133e7afec3fa214b7866fc321fa7d6c69eacff4033094c6fe234a1111eL149-L151). Working on a fix.

**Comment by eamansour** [comment]
A fix has been delivered (see https://github.com/galasa-dev/eclipse/pull/47) and will be released as part of 0.27.0 - closing.
