### ISSUE TITLE
Enhancement request: view pass/fail status in Galasa Results view

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#1209]
It would be nice to be able to see at a glance whether a test run has passed or failed, in the Galasa Results view. 
This is an enhancement request to tag/highlight/show in the results lists which tests have passed and which have failed. This would save repeated opening/closing of results in order to find the last pass / last fail and we could get a picture of results at a glance whilst developing tests.

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
