### ISSUE TITLE
Create galasabld image

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1211]
Please create a galasabld image that we can use for our build pipelines. Have a look at argocd/tektonHelm/templates/bld/pipe-galasabld-build.yaml and argocd/tektonHelm/templates/bld/task-galasabld-build.yaml to see how the previous galasabld image was built.

- Create a galasabld-dockerfile and put with the other dockerfiles in the automation repo (see the installing galasabld part of the existing Dockerfile)
- You will need to create a pipeline/tasks to do this, which will include similar steps to the existing pipeline: clone the buildutils repo, run 'make all' which will execute the Makefile in buildutils, then build the image with the kaniko builder, and push to harbor

**Comment by jadecarino** [comment]
galasabld image builds successfully in a pipeline and is now pushed to harbor: https://harbor.galasa.dev/harbor/projects/3/repositories/galasabld/artifacts-tab 
The image will need to go through some sort of Build Verification Test and will have to be documented before closing this off.

**Comment by jadecarino** [comment]
Aaron has created a Dockerfile and pipeline to build a 'galasabld' image to allow us to use the galasabld CLI in pipelines. All seems okay on the surface, but would like to have used the image within a pipeline before closing this off as done.

**Comment by jadecarino** [comment]
Need to investigate what the different between these images are and why/where they are all used, as the build for galasabld potentially needs to build all of these if they are still needed. 
- galasa-build
- galasa-bld-binary
- galasa-bld-amd64
- galasa-bld-ibm-amd64

**Comment by hobbit1983** [comment]
Is this now done - what needs to be reviewed before it can be moved to complete

**Comment by jadecarino** [comment]
Aaron has created a galasabld image, I'd just like to run the OBR pipeline which uses it to confirm it does what it needs to
