### ISSUE TITLE
Create Extensions main build pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1216]

**Comment by jadecarino** [comment]
YAML for this pipeline is written, however blocked from running it as the Framework pipeline needs to have ran first so that the galasa-framework:main image is in harbor, and Framework pipeline blocked: https://github.com/galasa-dev/projectmanagement/issues/1234

**Comment by hobbit1983** [comment]
Hey @jadecarino is this now done?  If so can it be moved into the current sprint and closed?
