### ISSUE TITLE
SimBank output message overwrites without clearing old message 

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#122]
Following the Galasa.dev walkthrough instructions to transfer money between two accounts.
Action 1, I made my transfer value larger than the balance in the paying account. The return message correctly identified lack of funds (a long string)
Action 2, I made a transfer with a value less than the payer account bal. The return message correctly reported a successful transfer
Outcome: the end of the earlier (long string) message was still visible, following the final character of the later (short string) message
![image.png](https://images.zenhubusercontent.com/5e45650eee4f44318eb1897c/f95a85c2-de8f-4e41-8411-5bfe03270d3c)

(Mac Pro, Host on Demand)

**Comment by Michael-Baylis** [comment]
I have fixed this,   but waiting for the p2 servers to restart to allow testing.
