### ISSUE TITLE
Upgrade version of external Kubernetes cluster - by 14th December

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1233]
## Story
As a member of the galasa dev team I want the cluster to be up to date so that our external cluster remains, and the services we run on it remain supported.

## Tasks
- [x] Research what is involved between v22 and v23 in api changes
  - And does it effect us
- [x] Upgrade cluster
- [x] Check everything healthy

**Comment by jadecarino** [comment]
**Must be done by 14th December**

**Comment by techcobweb** [comment]
I guess we will still be hosting some deployments on this cluster, so still have to do this, even if the majority of the working build has migrated to the internal cluster ?

**Comment by jadecarino** [comment]
Discussion with James yesterday: James does not think there will be any changes needed for the upgrade. I will confirm this and if so tick off the first task.

I think I should add a second task for the actual upgrade of the cluster that is done on IBM Cloud. Potentially to avoid disruption it would be a good idea to do this next sprint, on an agreed date?
