### ISSUE TITLE
Investigate the speed of our Kubernetes cluster 

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1234]
When running the Framework PR build, I noticed that the pipeline ran awfully slow, at it's quickest it ran (and failed) in 30 minutes, and at its longest it reaches a PipelineRunTimeout after 1 hour.

We need to investigate why the external cluster is so slow and how we can remediate this, as getting another node is the least preferable option.

- Investigate if there are any unnecessary services that are using resources
- Investigate if we can set limits to help speed things along

**Comment by jadecarino** [comment]
We are going to move the builds back on to the old cluster for now. This item of work can be put on hold until a time in future if we wanted to put the builds on to the new external cluster.

**Comment by techcobweb** [comment]
We came to a conclusion on this one, so closing this item.
