### ISSUE TITLE
3270 Terminal timeout if no logon

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#124]
We get the following trace after about 3 mins if a 3270 terminal is not logged on:
```
09/03/2020 09:33:55.541 ERROR Thread-2 dev.galasa.zos3270.internal.comms.NetworkThread.run - Problem with Network Thread
dev.galasa.zos3270.spi.NetworkException: TN3270E message Data-Type -1 is unsupported
        at dev.galasa.zos3270.internal.comms.NetworkThread.processMessage(NetworkThread.java:106)
        at dev.galasa.zos3270.internal.comms.NetworkThread.run(NetworkThread.java:66)
```

Assumption is a timeout. In a long running test that doesnt use the terminal straight away this is an issue.

Possible fix is to have a `dontNotConnect` field in the annotation and then the user can connect up manually inside the test. Possibily want to add a message to the stack above to warn any users who encounter this issue

**Comment by Michael-Baylis** [comment]
@Jimbo4794 Has this been sorted now?

**Comment by Jimbo4794** [comment]
Yep all completed
