### ISSUE TITLE
New External Functionality : Execute a galasa test using `galasactl` - without installing DockerOperator or Ecosystem.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1258]
## Story
As a product tester trying to use galasa to write tests, I want to execute a test from the command-line without installing galasa in either a DockerOperator or Ecosystem environment, so that it's easier to get started, and easier to create initial simple automation.

## Background
Currently you can do this with syntax like this: (please correct if I'm wrong)
```
java -jar <galasa-obr> -jar <test-obr> ... -Dbootstrap=... ????
```
It would be far easier if the galasactl tool would encapsulate this mechanism, so a test can be launched in a much easier way with a basic galasa non-deployed setup.

eg:
```
galasactl run ...
```

## Tasks
?
```

**Comment by hobbit1983** [comment]
One thing we would have to consider is that in all the documentation and samples we do not talk about creating an OBR project and instead rely on the workspace OBR that is generated automatically by the galasa launcher in eclipse.  so to support galasactl doing this we would also need to provide/discuss obr projects in the doc

**Comment by techcobweb** [comment]
Closing as this is a duplicate of story #1322, and the other story has more detail inside.
