### ISSUE TITLE
SSHClient messages 'closing SSH session' appearing throughout test run logs 

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#1281]
I'm seeing a number of the following message entries, e.g.,
`22/11/2022 16:51:09.517 DEBUG d.g.i.s.SSHClient - No command issued after 60000 milliseconds, closing SSH session `
in my test run logs, even though it all works and no commands are (knowingly) left hanging - all have responses.

Tests will typically issue many commands to both z/OS USS and Linux as they run through. These messages begin to appear around 60s after the first set of commands are issued, then continue to appear throughout the rest of the test run / run log.  I'm not sure whether I need to close something after issuing each command, or whether it's something else. 

These messages do not cause the tests to fail at all; they just populate the console output and run log and look a little unsightly, making me wonder whether I'm missing something in the command structures. I'm also unsure whether these are resulting from USS or Linux commands, or both.

**Comment by hobbit1983** [comment]
Hi Jason,
So I've done some research on this.  Whenever a test runs a command it drives an underlying SSHClient connection.  The first time a connection is driven we store the constructed session object within a keep-Alive thread that runs and check periodically if that session has been used within the timeout value.  If it has then we cleanup the connection by disconnecting it.  If the SSHClient is re-used then we will re-drive the connection logic again.  

This behaviour allows multiple commands to re-use the connection and also avoids the tester having to close down unused sessions.  However I can see that the debug error gives a different impression.  

We could change the message to TRACE so it's not as prominent, or we could re-word it perhaps "SSH Session unused for 60000milliseconds, freeing it". what are your thoughts?

**Comment by hobbit1983** [comment]
@jasonrhughes interested to know your thoughts

**Comment by jasonrhughes** [comment]
Many thanks for looking into this, Will. 
I think anything that makes it less prominent (so a new user is less likely to think they may have done something wrong) would be really good. Either of your suggestions would be fine, or perhaps a combination of both? ;) 
(Perhaps a slight variation on your re-wording, along the lines of:
"SSH session unused for 60000 milliseconds, disconnecting now to free it."   ?)

**Comment by hobbit1983** [comment]
Fixed by https://github.com/galasa-dev/managers/pull/829
