### ISSUE TITLE
Few problems in WebAppInt Test

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1291]
## Describe the bug
During setup and execution of the web app int test I noticed a few problems that we need to rectify

## Steps to reproduce
1. When defining the CPS properties for the gecko driver it says we should use the following property `selenium.LOCAL.driver.FIREFOX.path=<path/to/geckodriver>`. Local should not be uppercased
2. When running the socat image the command is incorrect.  the port should be 2375 and not 2376 in all cases
3. When building the docker image for the web application, the user is asked to clone the sim bank repository, giving the git clone command would be useful
4. The user is then advised to to build and test the docker image.  It would be useful to give the user the URL `http://localhost:8080/galasa-simplatform-webapp/simbank` and the image that they should see when they visit that page

**Comment by CaroMac** [comment]
Thank you Will, taking a look

**Comment by CaroMac** [comment]
updated and sent for rereview
