### ISSUE TITLE
Bump snake yaml to 1.31

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1300]
From MEND scan from DfG - snakeyaml needs to be bumped from 1.30 to 1.31

**Comment by techcobweb** [comment]
Lets bump this to 1.32 to avoid a further MEND issue which will occur soon.

**Comment by hobbit1983** [comment]
1.33 is available so bumping to that

**Comment by hobbit1983** [comment]
PR building - needs approval
