### ISSUE TITLE
ALPHA: Create Galasa Docker Ecosystem builder

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#131]
To make it easier for customers to create a Galasa Ecosystem under Docker a Java program should be written to ask the user for replies so that artifacts can be created for the user to use.  A bit fluffy I know, but you will see why.
The following points need to be kept in mind:-
1) This same program will eventually be used for Kubernetes/OpenShift/Shell(windows, linux/amd64/z)
2) The responses from the user needs to captures in a YAML file so if they rerun the program, the YAML file can be preloaded
3) For Docker based ecosystem,  the output can be a shell script or Docker Compose files.
4) Eventually, k8s output could be yaml or helm.
5) Eventually, shell output can be shell scripts appropriate for the OS
6) The program must be able to run standalone "java -jar xxx" or "docker run -it galasadev:buildeco"
7) As many of the replies must have defaults as possible.

**Comment by Roavill2** [comment]
Programming of main java class for capturing user configuration near complete. Some updates to defaults required to reflect updated information in Kubernetes files rather than runtime (outdated). Currently working on point 3 - output to shell script - going to split out into two shell scripts to be executed - setup and update of setup.

**Comment by Roavill2** [comment]
Shell scripts are functional. Update script works to update the configuration properties file that the docker set up script then uses. Docker set up script currently sets network up, creates volumes and pulls down/creates containers. Having some issues pulling down galasa specific docker images, currently working on that
