### ISSUE TITLE
Authentication: galasactl logs in to ecosystem with access token

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1321]
## Story

As a galasa test-case developer I want to be able to log into the galasa cluster using an access token so that my follow-on commands are authenticated to run commands against that cluster.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background

We want to get users to log into the Galasa ecosystem they are targeting with tests, or queries about previous runs, so we can verify they are who they say they are.

**Syntax**

`galasactl auth login`
(which assumes that the token can be obtained from the `${GALASA_HOME}/galasactl.yaml` file

The bearer token is stored in $GALASA_HOME/bearer-token.json behind the scenes.

## Notes:

@Jimbo4794 did a createan  example which talks to Dex. Code is here: https://github.ibm.com/CICS/cics-cit-utils/tree/main/cicsk8s

We can't use that as it stands up a local http server, and we can't guarantee that users on laptops are able to do that, and have traffic reach it.

### Log out of galasa

`galasactl auth logout` - clears the file $GALASA_HOME/bearer-token.json

Output: None.

### REST API
- [x] REST API to log in using a token added. Gives back a JWT. Auth is a new servlet.
- [x] REST services demand a valid JWT and insist on it, returning a 401 Unauthorized HTTP response if one has not been provided (do this by using a Servlet Filter that checks an Authorization header for a valid bearer token)
- [x] Add custom header to allow the servlets to know whether the requests are coming from the CLI or eclipse so the CLI ones can be authenticated and eclipse ones left alone.
- [x] Update the openapi.yaml document with new Authentication API
- [x] Add 401 Unauthorized HTTP Response to all endpoints in the OpenAPI specification.

#### Login command
- [x] galasactl login command added
- [x] `galasactl local init` creates `$GALASA_HOME/galasactl.yaml`
- [x] Refresh token, client ID, and client secret are drawn from the galasactl.yaml file in `$GALASA_HOME`
- [x] JWT returned from API server is stored in a `$GALASA_HOME/bearer-token.json` file
- [x] Switch from `galasactl.yaml` to `galasactl.properties` for consistency with other `$GALASA_HOME` files

#### Logout command
- [x] galasactl logout command added
- [x] galasactl logout deletes token file (if that where it was drawn from), or blanks the environment variable (if it was drawn from there).

### Other commands
- [x] CLI commands should draw from the $GALASA_HOME/bearer-token.json file and error if it does not exist
- [x] Pass the bearer token to the API calls

### Doc updates
- [x] README updates

### Webui
- [x] Update modal from personal access token creation to include the new `galasactl.properties` contents (client-id, secret, access-token) for users to copy instead of just displaying the refresh token

### Separate scope
- Auth servlet layer needs to generate a gRPC client for Dex 
  - in the build-locally.
  - in the automated build.

### Scope moved to story 1341
- Install the ecosystem Helm chart on a cluster and make sure the installed ecosystem is reachable
- IVT tests use CLI to login and logout.

`galasactl auth login --host http://galasa-api.example.com --token XXXXXXX`
or
`galasactl auth login --bootstrap http://galasa-api.example.com --token XXXXXXX`
or
`galasactl auth login --token XXXXXXX`
(which assumes that the $GALASA_BOOTSTRAP environment variable can be used to find the host)

**Comment by jadecarino** [comment]
- Moved Environment/MockEnvironment to other package
- Unit tests seem to be very large, not about testing a 'unit' anymore

**Comment by techcobweb** [comment]
@eamansour I believe the blocker to merging these changes is that the CLI won't run unless the server is enabled with authentication.

I am wondering if we should inititially try to access the auth server, and if it's not available, continue anyway without a token. That way we could merge the code and the CLI would still work even though the auth server isn't in place ?

Can authentication be turned 'off' on the deployment with a flag for now, so we can merge the changes we have so far, but not have them 'active' ?

Worried about code in branches getting 'stale'.

Also, it's clear now that we need to have the UI talk only to the auth rest service, not directly to dex... can you pls raise a follow-on story to detail those changes pls ?

**Comment by eamansour** [comment]
Follow-on story raised https://github.com/galasa-dev/projectmanagement/issues/1568

I've made the change to allow the CLI to continue without a token if the auth service is unavailable and have opened PRs for the CLI and the auth service changes (https://github.com/galasa-dev/cli/pull/151 and https://github.com/galasa-dev/framework/pull/442). It's worth pointing out that the CLI builds will fail until the changes to the framework's openapi.yaml are delivered.

**Comment by techcobweb** [comment]
Thanks for raising the story.
