### ISSUE TITLE
Add documentation to convey  that galasactl is now supported on MaxOSX on arm64 architecture machines

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1324]
Add row to the table in the Getting Started section of Using the Galasa CLI to note that galasactl is now supported on MaxOSX on arm64 architecture machines.

**Comment by techcobweb** [comment]
@Caromac is this one complete now ? I don't see it in the public site or the recent preview sites... We need the entry in the table when we talk about installing the galasactl tool.

**Comment by CaroMac** [comment]
It is complete. I have added it to this PR https://github.com/galasa-dev/galasa.dev/pull/560  as I think there was a problem with the previous one which wasn't showing.
