### ISSUE TITLE
Archive the kubernetes operator repository

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1328]
## Story
As a developer exploring galasa, I don't want to see github repositories which hold content that will never be developed or supported further, so I can avoid confusion in what I might read there.

## Background
The kube operator being deprecated, it can be marked as such.

## Tasks
- [x] Archive the kube operator code repository

**Comment by jadecarino** [comment]
Completed as part of https://github.com/galasa-dev/projectmanagement/issues/1432
