### ISSUE TITLE
Install issue with Galasa Framework 0.5.0 Missing Requirement

### ISSUE THREAD

**Issue by thebarge0** [galasa-dev/projectmanagement#133]
Attempting to install into a new CICS Explorer 5.5.2 installation (using the eclipse menu add new software option).  

I get the following errors:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Galasa SimBank 0.5.1.202003101211 (dev.galasa.simbank.feature.feature.group 0.5.1.202003101211)
  Missing requirement: Galasa Framework 0.5.0 (dev.galasa.framework 0.5.0) requires 'java.package; org.apache.commons.lang3 [3.1.0,4.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Galasa Eclipse 0.5.1.202003101036 (dev.galasa.eclipse 0.5.1.202003101036)
    To: osgi.bundle; dev.galasa.framework 0.0.0
  Cannot satisfy dependency:
    From: Galasa SimBank 0.5.1.202003101211 (dev.galasa.simbank.feature.feature.group 0.5.1.202003101211)
    To: org.eclipse.equinox.p2.iu; dev.galasa.simbank.ui [0.5.1.202003101211,0.5.1.202003101211]
  Cannot satisfy dependency:
    From: Galasa SimBank 0.5.1.202003101211 (dev.galasa.simbank.ui 0.5.1.202003101211)
    To: java.package; dev.galasa.eclipse 0.0.0

**Comment by hobbit1983** [comment]
Hi - so the problem here is that CICS explorer isn't a full Java IDE and so lacks some of the requirements of the plugin.  Currently the Galasa eclipse extension can only be installed into eclipse for Java developers (Oxygen or above)

**Comment by davenice** [comment]
Hey - CICS Explorer isn't quite a "proper" Eclipse but it should contain 99% of a full Eclipse ... and the good news is that it's feasible to add the rest if needed!

The key is to add the Eclipse 4.8 (Photon) update site to your list of update sites (I googled and found the URL https://download.eclipse.org/releases/photon/). Once you've done that have another go at installing Galasa - when you're installing there's a tick box that says "Contact all update sites during install to find required software" - this will allow Eclipse to pull anything extra from the Photon update site.

I had a quick test here and it worked fine for me! (I'm on CICS Explorer 5.5.0.6, but it should work for you as well).

**Comment by hobbit1983** [comment]
Excellent stuff Dave, thank you @thebarge0 hope this helps you

**Comment by thebarge0** [comment]
That worked. Thank you
