### ISSUE TITLE
Galasa maven-plugin warnings when building

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1331]
## Defect
As a developer learning how to write and build tests, when I create an example using galasactl, and build it using maven, I see some worrying-but-harmless warning messages which I would like supressed so that I don't worry about them.

The warnings are:
```
[WARNING] Could not find artifact dev.galasa:dev.galasa.framework:json:testcatalog:0.25.0
[WARNING] Could not find artifact dev.galasa:dev.galasa:json:testcatalog:0.21.0
[WARNING] Could not find artifact dev.galasa:dev.galasa.core.manager:json:testcatalog:0.25.0
[WARNING] Could not find artifact dev.galasa:dev.galasa.artifact.manager:json:testcatalog:0.25.0
[WARNING] Could not find artifact org.assertj:assertj-core:json:testcatalog:3.11.1
```

## To reproduce
Run the following:
```
galasactl project create --package dev.galasa.example.banking --features payee,account --obr
cd dev.galasa.example.banking
mvn clean install
```

The warnings appear near the end of the log.

**Comment by hobbit1983** [comment]
so this is the galasa maven plugin attempting to merge a test catalog from the obr - which is fairly stupid thing for it to do.  We probably need to add code to allow the plugin to not attempt processing a test catalog from an obr

**Comment by techcobweb** [comment]
It's not fatal, just a warning, which is fairly benign, but users aren't to know that, and will probably ask what's going on.

**Comment by techcobweb** [comment]
Fixed recently. So closing this defect now.
