### ISSUE TITLE
Create snapshot pipelines

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1345]
- [x] (triggered from buildutils main build) snapshot galasabld main > prod
   Look at existing snapshot-galasabld PipelineRun
- [x] (triggered from cli main build) snapshot galasactl main > prod
   Look at existing snapshot-galasactl PipelineRun
- [x] snapshot main > code coverage (this then triggers run-codecov)
   Look at existing snapshot-codecov PipelineRun
- [x] (triggered from inttests main build) snapshot inttests main > prod
   Look at existing snapshot-inttests PipelineRun

**Comment by techcobweb** [comment]
Is this required for releasing ? What tangible benefits do these pipelines provide ? What's the benefit ?
