### ISSUE TITLE
Create presentation for GSE UK Virtual 2023

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1351]
Creating this item to track that I will be spending some time during this sprint creating my presentation for GSE UK Virtual 2023 and rehearsing it.

Tasks:
- [x] Write session abstract
- [x] Write speaker bio
- [ ] Create slide deck
- [ ] Film demonstration video
- [ ] Create rough script
- [ ] Rehearse (Will and Lewis)

**Comment by techcobweb** [comment]
How did it go @jadecarino ?
Is there a recording ? and/or materials put somewhere in Box ?

**Comment by jadecarino** [comment]
It went really well thank you @techcobweb . There is a recording that will be uploaded to Youtube but this won't be for another couple of weeks yet. I do have my slideshow that I used that I can add to our Box folder with speaker notes etc in case anyone wants to use the material in future.
