### ISSUE TITLE
Add troubleshooting for LPAR errors

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1354]
Each LPAR has a certain number of slots that are allocated to it. When the slots are used, no more tests can be allocated to that LPAR. If the LPAR is part of a cluster,  then Galasa switches to another LPAR. 
If you are running test cases locally that target an LPAR that is offline,  you might get an "Insufficient capacity for images..." error or similar. To resolve this problem,  delete any failed test runs and clear he content of the _dss_ file in ~/.galasa/ and run the tests again.

**Comment by CaroMac** [comment]
Will add to the following topic: https://galasa.dev/docs/writing-own-tests/binding-tests#gatsby-focus-wrapper in the cluster section.

**Comment by techcobweb** [comment]
What's stopping us from closing this item please ? Looking at the description it's not clear what's remaining before we can close this out ?

**Comment by CaroMac** [comment]
published and closed
