### ISSUE TITLE
Spike: Discussioin of Gradle Plug-in Use

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1359]
## Tasks
- [x] Discuss the issues outline in Story 1 and raise issues if necessary.
- [x] Discuss the issues outline in Story 2 and raise issues if necessary.

## Story 1
As a galasa developer, I want to run security scans on the repositories, so that I can avoid security flaws in Galasa, whilst also not having to create a new security scanning tool.
### Background
Following on from #1000, a point was raised about the security-scanning of Galasa, and the fact the it currently uses the pom.xml files to gather data about dependencies for vulnerability scanning. As Gradle does not use pom.xml files how would we ensure that the scans continue to work?

## Story 2
As a galasa developer, I want to have the option to choose whether to build Galasa using Maven or Gradle, so that I can perform local builds using the build tools I am more familiar with.
### Background
Following on from #1000, a point was raised about the ongoing support of Maven and Gradle and whether we would be supporting on, the other or both for development and builds of Galasa? This is going to determine our build strategy going forward and will impact the way in which we currently build/test Galasa.

**Comment by techcobweb** [comment]
To address "story 2" : We should build all galasa components with Gradle.

However, galasa testcases should be buildable using either maven or gradle depending on what the customer wants to use. We need to support both in that scenario.

This is slightly different to showing them how to do either, which the `galasactl project create` tooling should do with a --maven or --gradle flag, or both. See story https://github.com/galasa-dev/projectmanagement/issues/1333

**Comment by techcobweb** [comment]
We should change the one remaining part of the galasa build process which uses maven (the uber-obr build) to use the gradle galasa build instead. Not sure if that story have been raised yet.

**Comment by techcobweb** [comment]
Gradle can find dependencies

> gradle -q dependencies --configuration scm

------------------------------------------------------------
Root project 'dependencies-report'
------------------------------------------------------------

scm
\--- org.eclipse.jgit:org.eclipse.jgit:4.9.2.201712150930-r
     +--- com.jcraft:jsch:0.1.54
     +--- com.googlecode.javaewah:JavaEWAH:1.1.6
     +--- org.apache.httpcomponents:httpclient:4.3.6
     |    +--- org.apache.httpcomponents:httpcore:4.3.3
     |    +--- commons-logging:commons-logging:1.1.3
     |    \--- commons-codec:commons-codec:1.6
     \--- org.slf4j:slf4j-api:1.7.2

A web-based, searchable dependency report is available by adding the --scan option.

**Comment by techcobweb** [comment]
@KirbyKatcher you were going to raise other stories on the back of this ? Can you pls put their numbers in the description ? Then close this issue as done I guess... ?
