### ISSUE TITLE
Design WebUI, so Trish & Tilly can manage finished test runs

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#136]
Trish & Tilly (Tester & Test lead/architect) will be able to explore and select tests and set of tests (manually or selected by a common meta attribute) and review the final disposition of the selected  tests, explore further and start to take appropriate actions, where needed to fix issues or optimise the test environment or app or test code.

**Comment by lubelg** [comment]
Completed a first pass at alternative approaches to targeting specific tests

[https://app.zenhub.com/files/220212715/a74a2453-9f85-432c-a57e-20691c192f90/download](https://app.zenhub.com/files/220212715/a74a2453-9f85-432c-a57e-20691c192f90/download)

**Comment by lubelg** [comment]
Currently prototyping in Adobe XD

**Comment by lubelg** [comment]
Moved prototype to Sketch on advice, because of integration with Invision, which provides remote interaction, so will greatly assist with design validation. Filters nearly done (though I would like to also explore the a) feasibility, b) utility and c) resource/time constraints to create a custom control for date-time specification (seems it's possible in React, but need a dev to look further into it) - I can prototype it easily enough.

**Comment by lubelg** [comment]
I'm currently trying out some alternative date-time pickers from react, to work out the one with the best fit for ease of use for picking date/time ranges easily

**Comment by NohWayJose** [comment]
I have incorporated most of the sugestions made at the prototype playback. I'm just working on the gnarlier problem of working with the 'artifact trace' (for the want of a better name)

**Comment by NohWayJose** [comment]
I have design validation meetings set up for 3/6/20 with Colruyt & USAA (Rabobank look like they'll follow but a week or so later)

**Comment by lubelg** [comment]
Will Burroughs & I have been finalising the BoxNote design specification - now finished
