### ISSUE TITLE
Upgrade couchDB

### ISSUE THREAD

**Issue by JeevanNaikOP** [galasa-dev/projectmanagement#1363]
## Describe the bug
Galasa ecosystem is using couchDB:2.3.1 , I tried upgrading by overriding the version, But not worked.

We had to bring down couchDB due to security compliance. We are no longer able to use Galasa with Jenkins.

### Use the latest couchdb version when installing a fresh ecosystem
- [x] Check that we are using the latest couchdb version
- [x] Change to latest if we are not
- [x] Update helm chart to use this version and make sure we can use that to deploy and run tests...
- [ ] Upgrade prod deployed test system to the latest version of couchbd
- [x] Beef-up security aspect of the RAS extensions project, to access couchDB to create databases and tables.
Currently using basic HTTP auth.

### Upgrade existing galasa ecosystem installs to use the latest couchdb version (migration).
- [ ] What actions need to be performed on a one-off incrimental basis ?

**Comment by techcobweb** [comment]
Thanks for raising this issue. Which version of Galasa are you using please ?

**Comment by techcobweb** [comment]
Current version is 3.3.1 so we should move up in 0.26.0 of galasa

**Comment by jadecarino** [comment]
https://github.com/galasa-dev/extensions/blob/main/galasa-extensions-parent/dev.galasa.ras.couchdb/src/main/java/dev/galasa/ras/couchdb/internal/CouchdbRasStore.java
2.3.1 hardcoded in here

**Comment by hobbit1983** [comment]
https://artifacthub.io/packages/helm/couchdb/couchdb

**Comment by techcobweb** [comment]
When we discussed this story in a scrum we said to treat it as two parts. Installing on a fresh system, and uplifting existing systems to use the latest version.

**Comment by techcobweb** [comment]
Blocked. Can't deliver any of this until eclipse doesn't access couchDB directly.

**Comment by KirbyKatcher** [comment]
Security issues has been identified with v3.3.2, therefore the upgrade will need to be to v3.3.3 as a minimum

**Comment by KirbyKatcher** [comment]
Increased priority on ticket due to impact from security issues below :

**Apache CouchDB < 3.2.3 / 3.3.x < 3.3.2 Information Disclosure
Apache CouchDB < 3.3.3 Privilege Escalation**
