### ISSUE TITLE
Remove eclipse equivalent of 'galasactl local init'

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1368]
## Story
Now that was have the command 'galasactl local init' in the CLI, we can remove the equivalent functionality from Eclipse so that every user has the same starting experience and not be hindered by eclipse issues to initialise Galasa on their machine

**This story should only be done once the 'galasactl local init' command has been documented**

## Tasks
- [ ] Remove the similar functionality from the eclipse plugins. Disable the menu item.
- [ ] Update the eclipse documentation to remove the bit about using the environment setup wizard functionality.

**Comment by techcobweb** [comment]
Note: We don't want to do this until it's clear the documentation story #1367 is complete.

**Comment by techcobweb** [comment]
We are removing eclipse from the Galasa deliverables, so this issue is no longer needed.
