### ISSUE TITLE
Eclipse with Galasa 0.25 - Error on initialise frame work

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1370]
## Describe the bug
A new 22-06-06 Eclipse with Galsasa 0.25.  

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2022-06 (4.24.0)
Build id: 20220609-1112
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: IBM Corporation
Java runtime version: 11.0.17+8
Java version: 11.0.17

Initialise framework fails with

## Steps to reproduce
1 Windows 11 
2 Download and install eclipse 22-06-06 ( Either Java EE or Java EE with Web)
3 Install zia p2 Galsasa into eclipse
4 Set the Galasa properties - See Screenshot
5 Set up Galasa workspace
6 Initialise Galasa Frame work - Bug appears.  See screenshot

Log in console
Initialising the Galasa Framework
Configuration Property Store is file:///C:/Users/097775866/.galasa/cps.properties
Searching for CPS providers
Found CPS Provider dev.galasa.cps.etcd.internal.Etcd3ConfigurationPropertyRegistration
Found CPS Provider dev.galasa.framework.internal.cps.FpfConfigurationPropertyRegistration
Selected CPS Service is dev.galasa.framework.internal.cps.FpfConfigurationPropertyStore
Dynamic Status Store is file:///C:/Users/097775866/.galasa/dss.properties
Searching for DSS providers
![Galasa settings](https://user-images.githubusercontent.com/47417716/219092058-133eff14-6ae4-456d-8b3a-9e0f9f2102a2.png)

Found DSS Provider dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStoreRegistration
Found DSS Provider dev.galasa.framework.internal.dss.FpfDynamicStatusStoreRegistration
Selected DSS Service is dev.galasa.framework.internal.dss.FpfDynamicStatusStore

## Expected behavior
I expected the framework to initialise
![Galsasa Error](https://user-images.githubusercontent.com/47417716/219092068-fd642e58-39da-41c6-b566-c0d1131b0c1a.png)

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.

**Comment by hobbit1983** [comment]
Thanks @ChrisAtkinson1 can you attach the content of the bootstrap.properties file please.  Also I note that you have a bad value in the OBR version field - this should be left blank or have a specific version i.e 0.25.0 written in there

**Comment by ChrisAtkinson1** [comment]
That file is empty.

**Comment by techcobweb** [comment]
@eamansour Is this still a problem on the 0.27.0 pre-release version ?

**Comment by eamansour** [comment]
This is likely still a problem since the recent eclipse fixes were focused on resolving a different issue. I haven't been able to reproduce this issue on macOS, so will need to try it out on Windows.

**Comment by techcobweb** [comment]
I tried galasa 0.26.0 on eclipse 2022-06 and it worked fine.

We know 0.27.0 works ok on 2022-09 or beyond, perhaps you could upgrade galasa or eclipse and try it again please @ChrisAtkinson1 ?

**Comment by techcobweb** [comment]
Offhand, no idea. Will investigate. There have been some build changes recently which may have upset things perhaps ? @jadecarino @AaronJhaj

**Comment by techcobweb** [comment]
Just tried to import the simbank samples...
<img width="598" alt="image" src="https://github.com/galasa-dev/projectmanagement/assets/77053/8820f5c3-df08-4acf-898f-c1f24bb5c88f">
Seemed to work fine...
<img width="309" alt="image" src="https://github.com/galasa-dev/projectmanagement/assets/77053/da1e42b1-89bb-4f34-a315-a5894f7b7ef2">

So... that's 0.26.0 on eclipse 2022-06

What version of eclipse + galasa are you using ? If it's not 2022-09/0.27.0 then perhaps you can move to those levels to confirm there are still issues ?

**Comment by ChrisAtkinson1** [comment]
That's blank 

![image](https://github.com/galasa-dev/projectmanagement/assets/47417716/0279dc2c-1c81-4b9f-ab31-8671f0adbb80)

**Comment by ChrisAtkinson1** [comment]
![image](https://github.com/galasa-dev/projectmanagement/assets/47417716/fd5c968f-4818-4068-b2b4-cc01b9bf4a63)

**Comment by ChrisAtkinson1** [comment]
![image](https://github.com/galasa-dev/projectmanagement/assets/47417716/8da8ab98-8b64-44a8-b219-55eaec3c14d0)

**Comment by eamansour** [comment]
Hi @ChrisAtkinson1, you should be able to find the simbank tests if you navigate to `File > New > Example` in Eclipse, which will open a `New Example` dialog. I just tried it on Eclipse 2023-03 / 0.27.0 and I can see the test projects (see below).

Looking at the empty dialog you posted (and correct me if I'm wrong), but I think you might be trying to import the simbank projects through the dialog that opens after selecting the `Import projects...` option in the project explorer, rather than the `New Example` dialog.

Hope this helps!

<img width="577" alt="simbank-2023-03" src="https://github.com/galasa-dev/projectmanagement/assets/47121388/ad79a863-9c28-4f9b-b8a0-c62fd8771e7c">

**Comment by ChrisAtkinson1** [comment]
Thanks that worked

**Comment by ChrisAtkinson1** [comment]
After running the simbank installs for manager then tests.  Trying to run the simbank IVT results in this error

[Simbank.zip](https://github.com/galasa-dev/projectmanagement/files/11565989/Simbank.zip)

**Comment by eamansour** [comment]
Looks like you might be using Java 17 or above - switching to Java 11 should fix it.

If you go to the "JRE" tab in the run configuration that you created to run the IVT, you can change the Java version by checking the "Alternate JRE" option and selecting Java 11 from the dropdown (see below for an example).

![Image](https://github.com/galasa-dev/projectmanagement/assets/47121388/344cdb56-e1a7-43fc-9650-5a0c4f4f7a15)

If you don't see Java 11 listed in the dropdown, you can add an installed JDK by clicking the "Installed JREs" button to the right of the dropdown and then you can either add the installed JDK with the "Add" button or let Eclipse search a directory to find the JDK using the "Search" button in the dialog that opens (see below).


![Image](https://github.com/galasa-dev/projectmanagement/assets/47121388/e5a37e69-47d0-465f-afc7-e73a7e7fe69d)

**Comment by techcobweb** [comment]
@eamansour Good answer.

As this issue has sat around for a while in review state, I will close it. 
Please re-open if this problem persists ...

**Comment by ChrisAtkinson1** [comment]
It's broken running Simbank and Java in .28 version using MVN

Can initialise enviroment and workspace.

Run maven install 

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/C:/temp/GLTest/Eclipse2303/eclipse/plugins/org.eclipse.m2e.maven.runtime_3.8.701.20230209-1606/jars/maven-slf4j-provider-3.8.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

**Comment by hobbit1983** [comment]
@ChrisAtkinson1 does this really break simbank and cause either the sample application or the test to fail in some way?  or is it just a warning that - yes - we should work around - but doesn't cause something to break/fail

**Comment by ChrisAtkinson1** [comment]
That's as far as it gets.  Nothing else happens

**Comment by ChrisAtkinson1** [comment]
That's  the run output

**Comment by techcobweb** [comment]
`--localmaven file:/C:/Users/097775866/.m2/repository/` and `file:/C:/temp/GLTest/GLWS2303/.metadata/.plugins/dev.galasa.eclipse/workspace.obr` look wrong.

**Comment by techcobweb** [comment]
On windows, should be `file:///C:/Users` or something like that ?

**Comment by hobbit1983** [comment]
@ChrisAtkinson1 that looks like you are running with a JRE that isn't java 11 - can you check please?

**Comment by ChrisAtkinson1** [comment]
Compiler 

![image](https://github.com/galasa-dev/projectmanagement/assets/47417716/4be2f5bb-f578-4c30-9eca-62c18c45f829)

Run config for running test

![image](https://github.com/galasa-dev/projectmanagement/assets/47417716/6345f9dd-30cc-498d-8ae0-6abc88e2d7b0)

Not sure if I should set something else ?

**Comment by hobbit1983** [comment]
In the run launcher dialog there is a JRE tab, what's in there?

**Comment by ChrisAtkinson1** [comment]
It's as per the second screen shot

**Comment by ChrisAtkinson1** [comment]
Is the p2 site being updated ? Or does the .21 version not match the .29 release ?

Bundle-Name: Galasa Tester Programmer Interface (TPI)
Bundle-SymbolicName: dev.galasa
Bundle-Version: 0.21.0
Created-By: 1.8.0_292 (AdoptOpenJDK)
Export-Package: dev.galasa;uses:="javax.validation.constraints";versio
 n="0.21.0",dev.galasa.api.ras;version="0.21.0",dev.galasa.api.run;ver
 sion="0.21.0",dev.galasa.api.runs;uses:="dev.galasa.api.run";version=
 "0.21.0"

**Comment by ChrisAtkinson1** [comment]
I guess the later.

![Screenshot 2023-07-07 160527](https://github.com/galasa-dev/projectmanagement/assets/47417716/eb57e751-2b29-4597-bd22-b9a3b3f55431)

**Comment by ChrisAtkinson1** [comment]
All fixed in .29
