### ISSUE TITLE
Spike: Replace direct access to etcd with access to the API server

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1373]
## Story
As a galasa ecosystem user, I want to use the API server to access CPS properties, so that I do not need a direct connection to the etcd server to access the CPS.

## Background
Currently, the framework directly accesses etcd to retrieve CPS properties from an ecosystem when initialising, which causes issues when trying to use Ingress as etcd uses gRPC. The Eclipse plugin also accesses etcd to retrieve test streams, which will need changing.

Replacing the direct use of the etcd server with the use of the framework's RESTful API would remove the need to expose the etcd server externally and hide the internal use of etcd when users try to initialise the framework and submit tests to an ecosystem with Eclipse.

**This story is an investigation to find out what components of Galasa directly access etcd.**

## Tasks
- [x] Investigate what Galasa components directly access etcd
- [x] Raise a story (or multiple stories) to replace the direct use of the etcd server with the use of the API server when running Galasa in an ecosystem

**Comment by techcobweb** [comment]
Is this the only place we access etcd ? To set up a stream we document how to do it using uploading a file to etcd ? Do we have to prioritise a story which allows crud of a stream via the rest API also ? (story https://github.com/galasa-dev/galasa.dev/issues/449)

**Comment by eamansour** [comment]
The Eclipse plugin also directly accesses etcd - story updated. I’m not aware of anything else that does the same, so we’ll need to investigate.

While it would be very useful to be able to interact with streams via the REST API before starting on this story, it’s more of an enhancement than a prerequisite to this story since we can still exec into the etcd pod running in an ecosystem to create and configure streams using `etcdctl` commands in the meantime.

**Comment by eamansour** [comment]
Investigated further - the projects that directly access etcd are:

- Extensions (defines CPS services) 
- Framework (retrieves properties from CPS)
- Eclipse plugin (retrieves test stream properties from CPS)
- Managers (several managers retrieve properties from CPS)
- Simplatform (simbank manager - retrieves properties from CPS)
