### ISSUE TITLE
Authentication: Framework to use the API server to retrieve CPS properties when running outside of kubernetes

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1379]
## Story
As a galasa ecosystem user, I want to use the API server to access CPS properties in the framework, so that I do not need a connection to the etcd server when running in an ecosystem.

## Epic
This is part of epic https://github.com/galasa-dev/projectmanagement/issues/1474

## Background
Following on from https://github.com/galasa-dev/projectmanagement/issues/1373 - Currently, the framework directly accesses etcd to retrieve CPS properties from an ecosystem.

Replacing the direct use of the etcd server with the use of the framework's RESTful API would remove the need to expose the etcd server externally and hide the internal use of etcd when users try to initialise the framework. This would also resolve issues related to etcd’s use of gRPC when trying to use an ecosystem that uses Ingress.

We could create an `APIConfigurationPropertyStore` class that implements the `IConfigurationPropertyStoreService` interface to allow the projects to select the API server as the CPS service when running in an ecosystem, which would mean the existing projects that access etcd directly would not need to undergo any major changes.

## Tasks
- [ ] Implement an `APIConfigurationPropertyStore` class as described above to use the API server to retrieve properties from the CPS when running in an ecosystem to replace direct requests to etcd
- [ ] Test to ensure the API calls are being made as expected

**Comment by techcobweb** [comment]
I think this may slow things down a LOT. The running of tests inside the ecosystem needs to be fast, and lots of calls are made to get CPS properties. 

When the test is running outside of the ecosystem, it can be slower, as that's really development, or only running a few tests with the local JVM method. In those cases all calls should be going through the REST API.

So I'm not sure this story isn't the wrong way around. Shouldn't it be "when running outside of an ecosystem" ?

**Comment by techcobweb** [comment]
This story is complete.
