### ISSUE TITLE
Authentication: Eclipse Plugin to use the API server to retrieve CPS properties instead of going to etcd directly

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1380]
## Story
As a galasa ecosystem user, I want to use the API server to access CPS properties from the Eclipse plugin, so that I do not need a connection to the etcd server when running in an ecosystem.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background
Following on from https://github.com/galasa-dev/projectmanagement/issues/1373 - Currently, the Eclipse plugin retrieves properties to interact with test streams.

Replacing the direct use of the etcd server with the use of the framework's REST API would remove the need to expose the etcd server externally and hide the internal use of etcd when users try to use the Eclipse plugin and want to submit tests to an ecosystem. This would also resolve issues related to etcd’s use of gRPC when trying to use an ecosystem that uses Ingress.

## Tasks
- [ ] Replace the eclipse plugin's direct use of etcd with calls to the API server to retrieve properties from the CPS rather than etcd
- [ ] Test to ensure the API calls are being made as expected

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
