### ISSUE TITLE
release notes for 0.26.0

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1393]
- [x] update landing page button
- [x] update 0.25.0 references where applicable to 0.26.0
- [ ] add release notes to include 
  - [x] Initialise your development environment with `galasactl local init`
  - [x] Launch a test within a local JVM using `galasactl runs submit local`
  - [x] 3270 images are generated in the RAS results store
  - [x] Create example project using `galasactl project create` now supports `--maven` and `--gradle` flags to control which build system the caller wants to use.
  - [x] upgraded SnakeYAML to v1.33. This is a java library for parsing yaml files.
  - [x] Doc on Getting started using the CLI to:
    - [x] initialise your local environment
    - [x] create a project
    - [x] run a test locally
  - [x] Various doc updates / enhancements to existing content

**Comment by CaroMac** [comment]
[] Doc on Getting started using the CLI to:
   [] initialise your local environment
   [] create a project
    ] run a test locally
[] Various doc updates / enhancements to existing content

**Comment by CaroMac** [comment]
Updates made, will submit for review via PR if nothing more needs adding.

**Comment by techcobweb** [comment]
I assume that as release 0.26.0 is out there, and the release notes are visible, we can close this one out.
