### ISSUE TITLE
ALPHA - Create sample tests to run against the real CICS Catalog Manager application

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#143]
Although SimBank is an excellent quick start sample, it is not real.  We need a "live" set of sample tests to prove Galasa does work in the real world.  The CICS Catalog Manager seems to be the easiest of the CICS sample applications to use as it has 3270 and web and is backed by VSAM.

**Comment by hobbit1983** [comment]
@Michael-Baylis Is this still needed now that we have the tests for Genapp?

**Comment by Michael-Baylis** [comment]
Nope
