### ISSUE TITLE
REST API: queries with no from date should be rejected as invalid and not defaulted

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1445]
When accessing a historic run from the API ras/run without specifying a from date there are no results returned.

example from local API instance

http://127.0.0.1:8080/ras/run?page=1&sort=to:desc&runname=U89
```json
{
  "pageNum": 1,
  "pageSize": 100,
  "numPages": 1,
  "amountOfRuns": 0,
  "runs": []
}
```
http://127.0.0.1:8080/ras/run?page=1&sort=to:desc&from=2023-04-20T12:09:59Z&runname=U89
```json
{
  "pageNum": 1,
  "pageSize": 100,
  "numPages": 1,
  "amountOfRuns": 1,
  "runs": [
    {
      "runId": "cdb-18edac576214d186d682b4589600485e",
      "testStructure": {
        "runName": "U89",
        "requestor": "unknown",
        "status": "finished",
        "result": "UNKNOWN",
        "queued": "2023-04-26T15:36:53.133881Z",
        "startTime": "2023-04-26T15:36:53.388768Z",
        "endTime": "2023-04-26T15:36:53.404212Z"
      }
    }
  ]
}
```

The issue exists due to the API being used to run a WebUI which only looked at the last 24 hours of runs. I believe this sort of contraint should be handled in the reuesting application and not defaulting in the API.

To resolve this:
- [ ] Remove defaulting from the `from` parameter when a runname is supplied
or 
- [ ] Remove default value of the `from` parameter 
- [ ] Error if the From is missing.

**Comment by techcobweb** [comment]
closing as if overlaps with
