### ISSUE TITLE
CLI `runs get` to support --result

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1446]
## Story
As a tester I want to be able to use the command-line to find out the list of failing tests on an ecosystem, so I can see if I have chase-up work to do.

## Background
`galasactl runs get` needs to support the --result parameter so that test runs which completed with a certain result are listed, but runs which completed with different states are not.

--result accepts a comma-separated list of result values.

Supported values are:
- Passed
- Failed
- EnvFailed
- PassedWithDefects
- FailedWithDefects
- Unknown

The parameters are accepted regardless of upper/lower-case.

--result parameter and --active parameter are mutually exclusive

### CLI
- [x] CLI accepts the new parameter without complaining
- [x] CLI validates the parameter, rejecting any result values which are not supported
- [x] accepted result values are case insensitive, and converted to lower-case for the query to the servlet.
- [x] CLI builds the correct servlet URL and calls it.
- [x] --result parameter and --active parameter are mutually exclusive
- [x] unit testing along the way is expected.
- [x] Updates to the README.md 
- [ ] Pull request to update the galasa-dev docs.

### Servlet
- [x] servlet accepts --result as a query parameter
- [x] servlet validates the query parameter value
  - [x] multiples allowed
  - [x] case ignored
  - [x] non-supported result values rejected rather than ignored, with a decent error message.
  - [x] --result parameter and --active parameter are mutually exclusive
- [ ] IVT test ?
- [x] openapi.yaml updates
- [x] check REST api docs rendered OK

**Comment by AaronJhaj** [comment]
Don't think we need to make any servlet changes. Validate the --result argument they user provides is a valid result type and then convert that to the actual result casing to send to servlet.
My implementation is take the user input and convert to lowercase. have a map that has the lowercase result as the key and the actual result type as the value e.g key:"passed" value:"Passed". then we send the value in the api call so no servlet work is needed?
