### ISSUE TITLE
Galasa OBR gradle plugin fails in Gradle v8

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1454]
## Describe the bug
Building a galasa project with an obr with gradle v8 fails with an error

## Steps to reproduce
1. Use galasactl to create a blank new gradle project 
2. cd into the new project directory
3. run `gradle build` using gradle v8

## Expected behavior
The build should run, instead we get the error:
```
FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.<init>(Lorg/gradle/api/provider/Provider;)V (loaded from file:/opt/homebrew/Cellar/gradle/8.1.1/libexec/lib/plugins/gradle-dependency-management-8.1.1.jar by MixInLegacyTypesClassLoader(legacy-mixin-loader)) called from class dev.galasa.gradle.obr.ObrPlugin (loaded from file:/Users/tomslattery/.gradle/caches/modules-2/files-2.1/dev.galasa/dev.galasa.gradle.impl/0.15.0/a1faaaca04936fa8b258265128dbdf10f129c8d1/dev.galasa.gradle.impl-0.15.0.jar by InstrumentingVisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:root-project[:]:project-com.ibm.cics.exampletests.obr(export)})).
```

I think the API for gradle may have changed between 7 and 8

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.

**Comment by techcobweb** [comment]
We support Gradle v8 so this should all be fine now.
