### ISSUE TITLE
Eclipse plugin forces Creds and RAS to be in ~/.galasa

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1488]
## Describe the bug
Tests run from eclipse plugin are forced to use ~/.galasa as location for CREDS and RAS

## Steps to reproduce
Set up a new galasa home folder to be anywhere but ~/.galasa and point eclipse in the preferences to point to it.  Run a test.  Both the RAS and CREDS will default back to ~/.galasa and not your intended location

## Expected behavior
RAS and CREDS location should obey GALASA_HOME and the location of the bootstrap

**Comment by hobbit1983** [comment]
The issue here is that the eclipse launcher creates its own overrides file and populates it with two parameters to force the CREDS and RAS location.  The value for these parameters is set to be based on the user home directory.  The framework does not need this and so they can be deleted

While doing this we will also add the property to allow a local run to create png images

**Comment by techcobweb** [comment]
Needs testing in a pipeline build to make sure it's good.
