### ISSUE TITLE
Create release pipeline to delete all 'release' and 'prerelease' branches on the repos

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1495]
## Story
As a developer releasing Galasa, I want to clone all the repos main branch to a 'prerelease' or 'release' branch as per the release docs.
Currently we get an error when running the clone scripts as these branches existed from the last release.
This means you have to manually delete these branches before running the clone scripts.
This should be automated and ran prior to the clone scripts in the release process.

## Tasks
- [ ] Write pipeline/script to delete branches
- [ ] update release docs

**Comment by techcobweb** [comment]
@AaronJhaj Didn't we just do this work on Thursday last week ?
