### ISSUE TITLE
CLI: --requestor should default to the current user.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1506]
## Bug

`galasactl runs submit --requestor` should default to the current user. It doesn't.
It defaults to "" / blank... which gets interpreted as 'unknown'

We should be using the current user name.

**Comment by techcobweb** [comment]
This should default to take the identity from the access token. A root user isn't too helpful...

**Comment by techcobweb** [comment]
Not merged yet due to build failures.

**Comment by KirbyKatcher** [comment]
build failures are cause by the ivts trying to access the test results without a --requestor specified
