### ISSUE TITLE
Gradle 8.2 fails to build galasa 

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1514]
See - https://github.com/galasa-dev/cli/issues/122

Version 7 apparently works but that's over 2 years old

from cli Issue 122

I upgraded my Windows gradle to 8.2

Fails to build with

C:\temp\GLTest\com.ibm.cics.test.runtimes>gradle build publishToMavenLocal
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.<init>(Lorg/gradle/api/provider/Provider;)V (loaded from file:/C:/Gradle/gradle-8.2/lib/plugins/gradle-dependency-management-8.2.jar by MixInLegacyTypesClassLoader(legacy-mixin-loader)) called from class dev.galasa.gradle.obr.ObrPlugin (loaded from file:/C:/temp/gradle/caches/modules-2/files-2.1/dev.galasa/dev.galasa.gradle.impl/0.15.0/a1faaaca04936fa8b258265128dbdf10f129c8d1/dev.galasa.gradle.impl-0.15.0.jar by InstrumentingVisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:root-project[:]:project-com.ibm.cics.test.runtimes.obr(export)})).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 30s

**Comment by hobbit1983** [comment]
@ChrisAtkinson1  I think this is a duplicate of #1454 if you agree can you close this pleas?

**Comment by ChrisAtkinson1** [comment]
Yes
