### ISSUE TITLE
Unable to Create JVM servers in CICS

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1515]
Ideally need this implemented 

dev.galasa.cicsts.CicstsManagerException: Not developed yet
	at dev.galasa.sem.internal.SemCicsImpl.getJavaHome(SemCicsImpl.java:482)

Although that could be badly hard coded around.

This is fundamental

dev.galasa.cicsts.CicstsManagerException: Not developed yet
	at dev.galasa.sem.internal.SemCicsImpl.getJvmProfileDir(SemCicsImpl.java:477)

Without the CICS Region having a JVMProfileDir set that can be written to and picked up by CICS.  No jvmprofiles can be pulled into the CICS CEDA resource to create a JVMServer.

Recreate.

Have a test with

	@CicsRegion(cicsTag = "A")
	public ICicsRegion myRegion;

Then code these to get the errors above.

	String javaHome = myRegion.getJavaHome();
	String profileDir = myRegion.getJvmProfileDir();

### Tasks
- Implement the following methods that are currently not implemented in the SEM manager:
  - [x] `getJavaHome()`
  - [x] `getJvmProfileDir()`
  - [x] `getUssHome()`
- [x] Test that the above methods work as intended in a Galasa test that uses the SEM manager

**Comment by ChrisAtkinson1** [comment]
I think that the solution is something like a link between

1) Code in Galasa manager needs to be able to get java / javadir

2) SEM needs to provide a DFHJAUTH library in CICS and the JVMProfileDir to the CICS zFS Temporary Directory in Galasa.  And Galasa needs to know what that is.

**Comment by techcobweb** [comment]
Eamon has finished the changes for this, but will deliver them in Tom Slattery's build infrastructure rather than the open source version, which will be removed shortly.

**Comment by eamansour** [comment]
The changes have now been delivered in Tom's internal infrastructure, so closing this issue - feel free to re-open if there are any concerns.
