### ISSUE TITLE
Need ability to choose SEM Model

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1516]
Currently I can only appear to build a single region.

@SemTopology()

Need abililty to choose a model.

EG Two Regions, CPSM Plex etc.

Some could be central - with others user created ( or copied from JAT for Conversion )

**Comment by hobbit1983** [comment]
@ChrisAtkinson1  Can we move this to an internal repository please Chris as SEM is not supported externally

**Comment by techcobweb** [comment]
The open source code can't ship sem, so it's an internal-to-CICS manager.
@Tom-Slattery what changes to the external open source are needed to support the above ?

**Comment by techcobweb** [comment]
Closing as this isn't something we can solve in the open source project, unless we have specific limitations in the provisioning steps we support.
