### ISSUE TITLE
Simbank IVT fails with JAVA JDK v17 but Eclipse no longer supports Jdk under 17

### ISSUE THREAD

**Issue by ApurvaS28** [galasa-dev/projectmanagement#1518]
I tried to run the Simbank IVT with V17  jdk and it fails .Can you please help me fixing this.

06/07/2023 17:06:33.825 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Building Felix Framework...
java.lang.NoSuchMethodException: sun.misc.Unsafe.defineAnonymousClass(java.lang.Class,[B,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at org.apache.felix.framework.util.SecureAction.getAccessor(SecureAction.java:1134)
	at org.apache.felix.framework.util.SecureAction.<clinit>(SecureAction.java:86)
	at org.apache.felix.framework.Felix.<clinit>(Felix.java:114)
	at org.apache.felix.framework.FrameworkFactory.newFramework(FrameworkFactory.java:30)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:98)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:210)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:122)
java.lang.NoSuchMethodException: sun.misc.Unsafe.defineAnonymousClass(java.lang.Class,[B,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at org.apache.felix.framework.util.SecureAction.getAccessor(SecureAction.java:1134)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:998)
	at org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender.<clinit>(ClassPathExtenderFactory.java:55)
	at org.apache.felix.framework.ExtensionManager.<clinit>(ExtensionManager.java:152)
	at org.apache.felix.framework.Felix.initializeFrameworkProperties(Felix.java:4881)
	at org.apache.felix.framework.Felix.<init>(Felix.java:405)
	at org.apache.felix.framework.Felix.<init>(Felix.java:355)
	at org.apache.felix.framework.FrameworkFactory.newFramework(FrameworkFactory.java:30)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:98)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:210)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:122)
06/07/2023 17:06:33.943 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Initializing Felix Framework
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.<clinit>(URLHandlers.java:119)
	at org.apache.felix.framework.URLHandlersActivator.start(URLHandlersActivator.java:69)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:825)
	at org.apache.felix.framework.Felix$SystemBundleActivator.start(Felix.java:5173)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:825)
	at org.apache.felix.framework.Felix.init(Felix.java:899)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:100)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:210)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:122)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @86be70a
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:103)
	... 11 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @86be70a
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:130)
	at org.apache.felix.framework.util.SecureAction.lambda$getAccessor$0(SecureAction.java:1145)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:998)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:78)
	... 11 more
06/07/2023 17:06:34.042 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Starting Felix Framework
06/07/2023 17:06:34.043 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Felix Framework started
06/07/2023 17:06:34.043 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Installing required OSGi bundles
06/07/2023 17:06:34.044 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.044 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/org.apache.felix.scr.jar
06/07/2023 17:06:34.121 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
06/07/2023 17:06:34.122 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.122 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/dev.galasa.framework.log4j2.bridge.jar
06/07/2023 17:06:34.273 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Installed  |     |dev.galasa.framework.log4j2.bridge (0.25.0-0ef2adf50a0fa4b5eba5699187162d77e05a70bc)
06/07/2023 17:06:34.273 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.273 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/log4j-api.jar
06/07/2023 17:06:34.330 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Installed  |     |dev.galasa.framework.log4j2.bridge (0.25.0-0ef2adf50a0fa4b5eba5699187162d77e05a70bc)
    3|Active     |     |org.apache.logging.log4j.api (2.17.1)
06/07/2023 17:06:34.330 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.331 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/log4j-core.jar
06/07/2023 17:06:34.455 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.25.0-0ef2adf50a0fa4b5eba5699187162d77e05a70bc)
    3|Active     |     |org.apache.logging.log4j.api (2.17.1)
    4|Active     |     |org.apache.logging.log4j.core (2.17.1)
06/07/2023 17:06:34.456 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.456 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/dev.galasa.framework.maven.repository.spi.jar
06/07/2023 17:06:34.510 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.25.0-0ef2adf50a0fa4b5eba5699187162d77e05a70bc)
    3|Active     |     |org.apache.logging.log4j.api (2.17.1)
    4|Active     |     |org.apache.logging.log4j.core (2.17.1)
    5|Active     |     |dev.galasa.framework.maven.repository.spi (0.21.0-a49e93162bc9f255c5274ab6615413434ac43e49)
06/07/2023 17:06:34.510 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.510 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/dev.galasa.framework.maven.repository.jar
06/07/2023 17:06:34.656 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.25.0-0ef2adf50a0fa4b5eba5699187162d77e05a70bc)
    3|Active     |     |org.apache.logging.log4j.api (2.17.1)
    4|Active     |     |org.apache.logging.log4j.core (2.17.1)
    5|Active     |     |dev.galasa.framework.maven.repository.spi (0.21.0-a49e93162bc9f255c5274ab6615413434ac43e49)
    6|Active     |     |dev.galasa.framework.maven.repository (0.22.0-0381e706d07affc3da6a956bd262d590dd24ea8e)
06/07/2023 17:06:34.660 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
06/07/2023 17:06:34.661 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/C:/Users/ApurvaSaxena/.p2/pool/plugins/dev.galasa.eclipse_0.29.0.202306141229/lib/galasa-boot.jar!/bundle/org.apache.felix.bundlerepository.jar
06/07/2023 17:06:34.720 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.25.0-0ef2adf50a0fa4b5eba5699187162d77e05a70bc)
    3|Active     |     |org.apache.logging.log4j.api (2.17.1)
    4|Active     |     |org.apache.logging.log4j.core (2.17.1)
    5|Active     |     |dev.galasa.framework.maven.repository.spi (0.21.0-a49e93162bc9f255c5274ab6615413434ac43e49)
    6|Active     |     |dev.galasa.framework.maven.repository (0.22.0-0381e706d07affc3da6a956bd262d590dd24ea8e)
    7|Active     |     |org.apache.felix.bundlerepository (2.0.2)
06/07/2023 17:06:34.720 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories - Loading OBR OSGi Bundle Repository file:/C:/Users/ApurvaSaxena/eclipse-workspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr
06/07/2023 17:06:34.739 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories - Loaded repository null from URI file:/C:/Users/ApurvaSaxena/eclipse-workspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr
06/07/2023 17:06:34.739 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -    dev.galasa.simbank.manager/0.0.1.SNAPSHOT
06/07/2023 17:06:34.746 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       reference:file:/C:/Users/ApurvaSaxena/eclipse-workspace/dev.galasa.simbank.manager/target/dev.galasa.simbank.manager-0.0.1-SNAPSHOT.jar
06/07/2023 17:06:34.746 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.manager
06/07/2023 17:06:34.746 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.manager
06/07/2023 17:06:34.748 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       requirements:
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa)(version>=0.21.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.artifact)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.docker)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.docker.spi)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.cps)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.752 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.creds)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.language)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.language.gherkin)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.http)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.http.spi)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.ipnetwork)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.simbank.manager.spi)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.textscan.spi)(version>=0.21.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.753 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos.spi)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.754 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.754 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270.spi)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.754 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=javax.validation.constraints)(version>=2.0.0)(!(version>=3.0.0))) optional=false
06/07/2023 17:06:34.754 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.apache.commons.logging)(version>=1.2.0)(!(version>=2.0.0))) optional=false
06/07/2023 17:06:34.754 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.apache.derby.jdbc)) optional=false
06/07/2023 17:06:34.754 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -    dev.galasa.simbank.tests/0.0.1.SNAPSHOT
06/07/2023 17:06:34.755 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       reference:file:/C:/Users/ApurvaSaxena/eclipse-workspace/dev.galasa.simbank.tests/target/dev.galasa.simbank.tests-0.0.1-SNAPSHOT.jar
06/07/2023 17:06:34.755 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.tests
06/07/2023 17:06:34.755 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.tests
06/07/2023 17:06:34.755 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       requirements:
06/07/2023 17:06:34.755 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa)(version>=0.21.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.756 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.artifact)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.756 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.core.manager)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.756 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.http)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.756 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.selenium)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.756 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.simbank.manager)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.756 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270.spi)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zosbatch)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.apache.commons.logging)(version>=1.2.0)(!(version>=2.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.assertj.core.api)(version>=3.11.0)(!(version>=4.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.openqa.selenium)(version>=0.25.0)(!(version>=1.0.0))) optional=false
06/07/2023 17:06:34.757 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories - Loading OBR OSGi Bundle Repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
06/07/2023 17:06:34.758 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:213)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:122)
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:889)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:122)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:210)
	... 2 more
Caused by: java.net.MalformedURLException: unknown protocol: mvn
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:94)
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:887)
	... 4 more
06/07/2023 17:06:34.758 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
06/07/2023 17:06:34.776 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Felix framework stopped
06/07/2023 17:06:34.907 ERROR dev.galasa.boot.Launcher.main - Exiting launcher due to exception
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:213)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:122)
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:889)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:122)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:210)
	... 2 more
Caused by: java.net.MalformedURLException: unknown protocol: mvn
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:94)
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:887)
	... 4 more

**Comment by hobbit1983** [comment]
@ApurvaS28 thanks for taking a look, can you confirm that in the launcher you are selecting a Java 11 JRE?

**Comment by ApurvaS28** [comment]
Hi Will ,

Here it says JRE11.


***@***.***

Thanks & Regards
Apurva Saxena
CICS System Programmer-Mainframe
Phone:91-7523862924
E-mail: ***@***.******@***.***>
Webex: https://kyndryl.webex.com/meet/apurva.saxena
***@***.***

From: Will Yates ***@***.***>
Sent: Thursday, July 6, 2023 5:18 PM
To: galasa-dev/projectmanagement ***@***.***>
Cc: Apurva Saxena ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [galasa-dev/projectmanagement] Simbank IVT fails with JAVA JDK v17 but Eclipse no longer supports Jdk under 17 (Issue #1518)

@ApurvaS28 thanks for taking a look, can you confirm that in the launcher you are selecting a Java 11 JRE? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@ApurvaS28<https://github.com/ApurvaS28> thanks for taking a look, can you confirm that in the launcher you are selecting a Java 11 JRE?

**Comment by ApurvaS28** [comment]
Hi Will ,

Any update on the issue ?

Thanks & Regards
Apurva Saxena
CICS System Programmer-Mainframe
Phone:91-7523862924
E-mail: ***@***.******@***.***>
Webex: https://kyndryl.webex.com/meet/apurva.saxena
***@***.***

From: Apurva Saxena
Sent: Thursday, July 6, 2023 5:21 PM
To: galasa-dev/projectmanagement ***@***.***>; galasa-dev/projectmanagement ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [galasa-dev/projectmanagement] Simbank IVT fails with JAVA JDK v17 but Eclipse no longer supports Jdk under 17 (Issue #1518)

Hi Will ,

Here it says JRE11.


***@***.***

Thanks & Regards
Apurva Saxena
CICS System Programmer-Mainframe
Phone:91-7523862924
E-mail: ***@***.******@***.***>
Webex: https://kyndryl.webex.com/meet/apurva.saxena
***@***.***

From: Will Yates ***@***.******@***.***>>
Sent: Thursday, July 6, 2023 5:18 PM
To: galasa-dev/projectmanagement ***@***.******@***.***>>
Cc: Apurva Saxena ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [galasa-dev/projectmanagement] Simbank IVT fails with JAVA JDK v17 but Eclipse no longer supports Jdk under 17 (Issue #1518)

@ApurvaS28 thanks for taking a look, can you confirm that in the launcher you are selecting a Java 11 JRE? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@ApurvaS28<https://github.com/ApurvaS28> thanks for taking a look, can you confirm that in the launcher you are selecting a Java 11 JRE?

**Comment by ApurvaS28** [comment]
Hello ,
Is there any update on this ?

Thanks 
Apurva

**Comment by techcobweb** [comment]
We've had to restrict the galasa runtime to only support Java 11 for now.

**Comment by mahsa2017** [comment]
this fix mentioned 2 weeks ago I tried and it didnt resolve my issue is still there

**Comment by techcobweb** [comment]
Also, We are archiving eclipse and removing it from the Galasactl system. The command-line tools are doing everything which eclipse can do, and galasactl can run in a terminal window within eclipse/intellij/vscode...

Suggest you move to using the galasactl tool as soon as you are able.
