### ISSUE TITLE
retrieveColourAtPosition() method in Galasa does not retrieve colour

### ISSUE THREAD

**Issue by FMerrison** [galasa-dev/projectmanagement#1525]
We are trying to use the retrieveColourAtPosition() method from Galasa to be able to retrieve color from the Mainframe terminal screens and then validate the color we retrieved is valid. However the method is only able to retrieve color from our initial screen and when we navigate to a different screen the retrieveColourAtPosition() is not able to retrieve color from the new screen. Instead of retrieving a color value it only returns a null value.

**Comment by techcobweb** [comment]
I asked @eamansour to take a look, and he says that @hobbit1983 started to look at this last week... No idea how that investigation is progressing so I've asked @eamansour to reach out and clarify the situation.

Move this issue to the release backlog until we can see what needs doing, at which point we can move it into the iteration I hope.

**Comment by hobbit1983** [comment]
Asked the customer for an update

**Comment by hobbit1983** [comment]
NB this is using 0.26.0 version of zos3270 manager

**Comment by techcobweb** [comment]
Seems that the 3270 stream provided by the customer didn't have any color in, so there was none to find.
They expected Green to be there, as that's what they saw from the Eclipse viewer.
Unfortunately, the eclipse viewer colors text as green by default, so you see something which isn't actually there !
This issue can be closed now @eamansour ?

**Comment by techcobweb** [comment]
This issue can be closed now @eamansour ?

**Comment by eamansour** [comment]
Yes, I don’t think there’s anything else that needs to be done on our side for this item. We can always re-open this issue if it needs looking at again in the future.
