### ISSUE TITLE
OMP require all galasa code to contain a different copyright statement.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1527]
## Story
As an auditor for the open mainframe project, I want Galasa source code to pass our copyright scanning tool, so we can sanction the Galasa project joining the OMP as an official project.

## Background

The OMP want us to change all our code to use this copyright header:

```
/*
 * Copyright contributors to the Galasa project
 *
 * SPDX-License-Identifier: EPL-2.0
 */
```

We need to automate this to do a massive find-replace of all our copyright headers for files.

Something like the following process:

- Develop the tool to substitute copyright messages at the top of files.

- Check out a Galasa repository.
- Create a branch.
- Call the utility to transform all the file copyright statements.
- Make sure the code builds locally still.
- Make sure no huge comments with lots of detail have been deleted.
- Check-in, push, PR, merge

- Repeat for all the important Galasa repositories

- Proposal is to create the tool in the automation repo

### Prep tasks

- [x] @hobbit1983 to check with the OMP folks that the proposed copyright header is OK.
- [x] create and unit test the tool
- [x] run the tool against the first repo (managers) and check it works.
- [x] update the bot
- ~~check that the bot accepts the first repo changes.~~ Scope moved to https://github.com/galasa-dev/projectmanagement/issues/1543
- [x] repeat for all the other repositories:

### Applying the tool tasks
- [x] extensions
- [x] managers
- [x] simplatform
- [x] framework
- [x] galasa.dev
- [x] helm
- [x] playground - nothing to change
- [x] #1534 
- [x] isolated - nothing to commit
- [x] eclipse
- [x] maven
- [x] gradle
- [x] wrapping
- [x] buildutils
- [x] TSC -only 2 .md files
- [x] webui
- [x] webui-old - ARCHIVED 
- [x] kubernetes-operator - ARCHIVED
- [x] argocd - ARCHIVED
- [x] vscode - ARCHIVED
- [x] examples - ARCHIVED
- [x] build - ARCHIVED
- [x] tekton-build - ARCHIVED
- [x] integratedtests
- [x] projectmanagement
- [x] security-scanning - ARCHIVED
- [x] githubapp-copyright -ARCHIVED
- [x] test-release - No changeable files
- [x] docker - ARCHIVED
- [x] scheduler - ARCHIVED
- [x] docker-operator - ARCHIVED
- [x] extended-catalog - ARCHIVED
- [x] gitopscreds - ARCHIVED
- [x] ansible- ARCHIVED
- [x] testapp - ARCHIVED
- [x] bulktests- ARCHIVED
- [x] common-build- ARCHIVED
- [x] cli
- [x] obr

**Comment by hobbit1983** [comment]
We would also need to update the copyright bot to check for the new header over the old one.  I've also emailed LF back for further information

**Comment by hobbit1983** [comment]
@techcobweb Received confirmation that LF are happy with the proposed header

**Comment by techcobweb** [comment]
Thanks very muchly @hobbit1983

**Comment by techcobweb** [comment]
Mission accomplished. Done.
