### ISSUE TITLE
Retire the tests which use Java16... it's not supported.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1529]
## Story
As a galasa developer I don't want to see tests run using Java 16 because galasa doesn't support Java16, and we get fluff obscuring the tests which we are interested in on the slack report.

## Background
Java16 is no longer supported, so we shouldn't be running integration tests using it.

## Tasks
- [ ] Remove the Java16 tests from the overnight IVT test run list

**Comment by techcobweb** [comment]
@hobbit1983 said he would do this one.

**Comment by hobbit1983** [comment]
I will indeed - just waiting on the PR to build
