### ISSUE TITLE
Galasactl runs submit defaulting to version 0.27.0 OBR

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1535]
## Describe the bug
I am using Galasactl version 0.29.0 CLI to run a set of galasa tests locally which are using the 0.29.0 version of the Galasa BOM. The tests fail to run because Galasactl is defaulting to running with version 0.27.0 of the boot jar and OBR. This persists if I clear out the ~/.galasa/lib folder and allow it to redownload the default version of Galasa boot jar.

## Steps to reproduce
1. Run tests using 0.29.0 without specifying OBR
2. Error will be in error log

Log:

`2023/07/25 14:35:24 Galasa CLI - Submit tests (Local)
2023/07/25 14:35:24 Galasa home is '/Users/tomslattery/.galasa'
2023/07/25 14:35:24 Creating file of type jar at /Users/tomslattery/.galasa/lib/0.27.0/galasa-boot-0.27.0.jar
2023/07/25 14:35:24 Created file /Users/tomslattery/.galasa/lib/0.27.0/galasa-boot-0.27.0.jar OK.
2023/07/25 14:35:24 Creating file of type properties at /Users/tomslattery/.galasa/bootstrap.properties
2023/07/25 14:35:24 File /Users/tomslattery/.galasa/bootstrap.properties exists, no need to create it then.
2023/07/25 14:35:24 Creating file of type properties at /Users/tomslattery/.galasa/overrides.properties
2023/07/25 14:35:24 File /Users/tomslattery/.galasa/overrides.properties exists, no need to create it then.
2023/07/25 14:35:24 Creating file of type properties at /Users/tomslattery/.galasa/cps.properties
2023/07/25 14:35:24 File /Users/tomslattery/.galasa/cps.properties exists, no need to create it then.
2023/07/25 14:35:24 Creating file of type properties at /Users/tomslattery/.galasa/dss.properties
2023/07/25 14:35:24 File /Users/tomslattery/.galasa/dss.properties exists, no need to create it then.
2023/07/25 14:35:24 Creating file of type properties at /Users/tomslattery/.galasa/credentials.properties
2023/07/25 14:35:24 File /Users/tomslattery/.galasa/credentials.properties exists, no need to create it then.
2023/07/25 14:35:24 Using group name '11a69f16-3bc0-40f5-9306-981050fd58dd' for test run submission
2023/07/25 14:35:24 JvmLauncher: GetRunsByGroup(groupName=11a69f16-3bc0-40f5-9306-981050fd58dd) entered. 
2023/07/25 14:35:24 JvmLauncher: GetRunsByGroup(groupName=11a69f16-3bc0-40f5-9306-981050fd58dd) exiting. isComplete:true testRuns returned:0
2023/07/25 14:35:24     Selected test class 'dev.galasa.sdv.tests/dev.galasa.sdv.tests.featureA.TestClassOne'
2023/07/25 14:35:24 Added test /dev.galasa.sdv.tests/dev.galasa.sdv.tests.featureA.TestClassOne to the ready queue
2023/07/25 14:35:24 JvmLauncher: SubmitTestRuns entered. group=11a69f16-3bc0-40f5-9306-981050fd58dd classNames=[dev.galasa.sdv.tests/dev.galasa.sdv.tests.featureA.TestClassOne] requestType=CLI requestor= stream= isTraceEnabled=false
2023/07/25 14:35:24 Properties file /var/folders/3h/yxw5xnq92cz5cwt8d1cjvkb80000gn/T/galasa-1796325182overrides.properties written containing this:
framework.request.type.LOCAL.prefix=L
framework.resultarchive.store=file:////Users/tomslattery/.galasa/ras
zos3270.terminal.output=json,png
2023/07/25 14:35:24 Launching command '/Library/Java/JavaVirtualMachines/jdk-11.0.18+10/Contents/Home/bin/java' '[-jar /Users/tomslattery/.galasa/lib/0.27.0/galasa-boot-0.27.0.jar -Dfile.encoding=UTF-8 -DGALASA_HOME="/Users/tomslattery/.galasa" --localmaven file:////Users/tomslattery/.m2/repository --remotemaven https://repo.maven.apache.org/maven2 --bootstrap file:////Users/tomslattery/.galasa/bootstrap.properties --overrides file:////var/folders/3h/yxw5xnq92cz5cwt8d1cjvkb80000gn/T/galasa-1796325182overrides.properties --obr mvn:dev.galasa.sdv/dev.galasa.sdv.obr/0.0.1/obr --obr mvn:dev.galasa/dev.galasa.uber.obr/0.27.0/obr --test dev.galasa.sdv.tests/dev.galasa.sdv.tests.featureA.TestClassOne]'
2023/07/25 14:35:24 JVM test started. Spawning a go routine to wait for it to complete.`

**Comment by techcobweb** [comment]
The VERSION file in CLI wasn't updated. So an old obr was being searched for.
The bleeding-edge code uses version 0.30.0 of the OBR.
