### ISSUE TITLE
DFG-specific files should not live in github.com they need moving to github.ibm.com and the build process needs to change.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1538]
## Story
As an external contributor to Galasa, I don't want to see any files in Galasa source code which relate to the IBM Distribution for Galasa (DFG) product, as it's confusing.

## Background
All files, including those containing IBM licensing were moved from github.ibm.com to github.com. As Galasa is an open source project, we need to ensure that no file attributes ownership to IBM on our external site at github.com

We should create a separate repository in github.ibm.com to house IBM-specifics, 
and have a separate build process which takes the MVP build, and unpacks/re-packs it to stamp IBM-ness into it.

The build process for the DFG can then be separate from the build process for the rest of the open source code, and scanning ...etc can later be moved over to the DFG build process.

The isolated/MVP artifacts can then be open-source centric.

Automated mend scanning needs to be added  to this pipeline.

We need the ability to do 'dry run' builds 

### Isolated repository / DfG
- [x] Remove from Isolated repository: PR open https://github.com/galasa-dev/isolated/pull/50
   - [x] ./mvp/resources/IBM Distribution for Galasa 1.0 Notices.html
   - [x] ./mvp/resources/README.txt
   - [x] ./mvp/resources/licenses/LA_de
- [x] Create the github.ibm.com repository which holds the DfG Licenses, README, and Notices
- [x] Create the github.ibm.com repository which represents the DFG end product
- [x] Write the build process to take the MVP build and unpack/re-pack/re-sign artifacts. Build process needs to inject IBM-ness wherever it's needed, IBM-versions stored in the internal DFG repo, and open-source versions in the open-source github.com repositories.
   - [x] Create Secret for github-enterprise-credentials to let us clone a repo from GHE in the pipeline (functional ID apparently in Vault) and pass a GH_TOKEN to the GH CLI - needs a username, password and personal access token
   - [x] Find a way to get the latest Galasa version and pass it into the pipeline so you can download the galasa-mvp-zip from the development.galasa.dev repo
   - [x] Build pipeline injects IBM-ness and then pushes to the CICS/distribution-for-galasa repo, and opens a PR, to kick off MEND scan
   - [x] Add a trigger from the branch-isolated pipeline to the distribution-for-galasa pipeline: PR open https://github.com/galasa-dev/automation/pull/381
   - [x] Transfer pipeline to galasa-build from jcarino namespace
   - [x] Merge changes to Isolated
   - [x] Merge changes to Automation
   - [x] Clear up branch maven repo

### Eclipse repository:
- [x] Update provider name in the following files (which contain: `provider-name="IBM"` near the top of page):
   - [x] `./dev.galasa.eclipse.feature/feature.xml`
   - [x] `./dev.galasa.simbank.feature/feature.xml`
   (which contain: `provider-name="IBM"` near the top of page)
- Is this really needed ? Can't we just change these to be Open source things ?

**Comment by jadecarino** [comment]
Blocked as we are not able to make a personal access token for GHE as we can't log into GHE with the galasa team credentials, without setting up MFA. Need access to the galasa email address to set up MFA.

**Comment by jadecarino** [comment]
https://github.com/galasa-dev/isolated/pull/50
https://github.com/galasa-dev/automation/pull/381

**Comment by jadecarino** [comment]
Blocked as the Mend scan repo is a private GitHub repository so the Galasa team account can't clone it even when authenticated. It needs to be given access to the repository.

**Comment by jadecarino** [comment]
@techcobweb Hi Mike - just an FYI, I have created issue #1682 which includes scope of creating the updated build process and Mend scan process for DfG using the Mend Unified Agent. I'll try to get the last boxes ticked off for this by making the Eclipse changes, then I suggest we change the scope of this item to be just that DfG files are removed from github.com as the build process Holly and I created needs to change.

**Comment by techcobweb** [comment]
Sounds good to me

**Comment by jadecarino** [comment]
According to this Eclipse doc here: https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Ffeature_manifest.html about feature manifest files, the 'provider-name' is an `optional display label identifying the organization providing this component. Intended to be translated.` so we can either just remove it or I don't see an issue with replacing 'IBM' with 'Galasa'.
