### ISSUE TITLE
Doc: Not obvious which MacOSX download required

### ISSUE THREAD

**Issue by matcomer** [galasa-dev/projectmanagement#1539]
## Describe the bug
I'm new to Galasa trying for the first time and trying to figure out which download I require

## Steps to reproduce
2 items to highlight

First item:
1. https://galasa.dev, select get started, it takes me automatically to 'Getting started using Eclipse'. Unless you are intentionally wanting to direct people to use Eclipse, it would be preferential to take you to 'Introduction and architecture' by default

Second item:
1. From: https://galasa.dev/docs/cli-command-reference/cli-command-reference I am wanting to install Galasa as first time user
2. I have a Mac but am not sure whether I need galasactl-darwin-amd64 or galasactl-darwin-arm64.
I have tried looking at 'About this Mac' to see what I have and can see it is an Intel processor - but was none the wise which download is applicable. A friendly colleague advised me I need amd64. However for people like me who are new in this space, some extra comments/ guidance would be very useful in getting going

**Comment by techcobweb** [comment]
Note: We are changing the name of the executable to galasactl-darwin-x86_64 if that makes it easier. Then `uname -m` will tell you which version you need to use.

Would that make it clearer @matcomer ?

**Comment by matcomer** [comment]
Thanks @techcobweb, yes that would be helpful
