### ISSUE TITLE
docs: GALASA_HOME improvements

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1552]
## Story
As a galasa user I want a section in the docs which details what the concept of Galasa 'home' is, and where it can be found.

## Background

The docs describe ~/.galasa as the home of Galasa, and then say that `GALASA_HOME` can over-ride that.

I think we need to explain that Galasa has a 'home' folder. And that `GALASA_HOME` points to it. And if `GALASA_HOME` is not set, then the home folder is `~/.galasa`

ie: Describe it as the other way around... then we can refer to a nice section which talks about Galasa home in the logical/abstract sense, rather than having to repeat this ~/.galasa or GALASA_HOME stuff all over the place ?

This came up because @eamansour and I were trying to put a link to the docs inside a UI panel, to indicate where the $GALASA_HOME/bearer-token.json can be found.

Lets discuss further if this isn't enough detail...

cc: @CaroMac

**Comment by CaroMac** [comment]
I have made improvements as part of the Getting Started restructure which is now merged in vNext if you can review and let me know if that is ok. https://vnext.galasa.dev/docs/initialising-home-folder
