### ISSUE TITLE
CLI: Support linux-arm64 architecture for galasactl tool

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1553]
## Story
As a mac laptop user, I want to run the galasactl tool within a virtual linux container, so I can launch tests there.

## Background
Some IBM-internal customer requested that the galasactl tool be made available within the linux-arm64 environment.

This is useful when hosting a VM container on a mac m1 machine for example.

Might need a mention in the download-and-install docs.

On linux, just as on the mac, a command `uname -m` will return the machine architecture.

If it returns 'x86_64' then use the 'amd64' version of the tool. If it returns 'arm64', use the 'arm64' version of the tool.

Apparently, even if you are using a mac, you might get back this "x86_64", which means run the "amd64" version of the tool, so our docs need an update for the mac text also.

## Tasks
- [x] Add build architecture to makefile.
- [x] docs

**Comment by techcobweb** [comment]
cc: @CaroMac just to make sure you got this detail...

**Comment by Wyvinar** [comment]
Goind to add the linux-amd64 and windows-amd64 to the x86_64 structure as well.
