### ISSUE TITLE
Update Galasa logo on website for OMP

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1557]
## Story
As a web developer, I want to change the existing logo and text, so that the logo and text include OMP.

## Background
As part of the move to an OMP project, a change is requested for the logo used on the galasa.dev website. Options for the new logo were shared on the galasa-devs slack channel. 

## Tasks
Questions / considerations around this change include: 

How the new logo will be created / shared eg one or more svgs from OMP?
How the new logo will impact the current layout of the existing website
Considerations around readability / accessibility
Who will implement the new logo and when, who did the implementation on other OMP project websites? 

Please add other thoughts / concerns / considerations

**Comment by techcobweb** [comment]
We are expecting to receive a graphics package with more images inside for different sizes, icon-only, ...etc. variations on the theme. This will be created by someone in the OMP and sent to us. @hobbit1983 will be receiving that. Not arrived yet.

We did tell the OMP we want the "first one" of their logo choices.

They are drafting the OMP project landing-page, so we don't have to worry about that it seems. That links off to our docs.

**Comment by CaroMac** [comment]
I pinged Joe W earlier and he just responded with this link https://github.com/openmainframeproject/artwork/tree/main/projects/galasa a few moments ago which looks like the artwork. I have added it to the website but currently it is rendering incredibly small.

**Comment by CaroMac** [comment]
So I have got the logo rendering in a larger size. In order for it to show clearly on the banner I had to change the font to white.  I now need confirmation regarding the new artwork though. For example, Zowe do not have "Open Mainframe Project" as part of the logo on their doc website eg https://docs.zowe.org/stable/user-guide/install-overview - they only have it on [zowe.org](http://zowe.org/). So could it be that the Galasa logo remains the same and we have Galasa with a capital G? Does the name need to move alongside the icon and have a capital? If so I will need the svg for that and confirmation it is ok to have it in white so that it shows up.

**Comment by CaroMac** [comment]
Found a white logo here https://github.com/openmainframeproject/artwork/blob/main/projects/galasa/horizontal/white/galasa-horizontal-white.svg so that is ok. Just whether to include the additional text or not for the doc site.

**Comment by CaroMac** [comment]
published!

**Comment by techcobweb** [comment]
Think this is done now. Closing out.

**Comment by hobbit1983** [comment]
@CaroMac @techcobweb thank you folks. This looks awesome
