### ISSUE TITLE
CLI needs command unit tests

### ISSUE THREAD

**Issue by Wyvinar** [galasa-dev/projectmanagement#1558]
As a developer I want to be comfortable making changes to CLI commands by using tests previously written to make sure I'm not breaking anything.

We are currently using cobra to create and detect flags, so far these flags have not been tested when they probably should be.

Found this useful reference: https://gianarb.it/blog/golang-mockmania-cli-command-with-cobra
Summary (where cmd is the command you wish to run. This will need to be instantiated before use):
- cmd.Execute() - can be used to exectute commands outisde the terminal.
- cmd.SetOut() - can be used to retrieve the output of the command.
- cmd.SetArgs([]string{"--your_flag1", fmt.Sprintf("--your_flag2=%s", your_string_value)} - can be used to set the flags and their values for the command.
Must use the SetOut() and SetArgs() functions before the Execute().

**Comment by techcobweb** [comment]
Done. Now in main.
