### ISSUE TITLE
Docs : Viewing test run results --requestor explanation needs correction

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1559]
Current docs have this in the "Viewing test run results" section:

```
--requestor | Use the --requestor option to view results of test runs that were submitted to the ecosystem by a specified user. The default is the current user name that is specified in the access token.
```

That default clause is not true.

For the runs get, the --requestor flag being missing means 'I want results from any requestor'.
If you specify the --requestor flag it's a filter on all those available for the runs get command.

## Background:

As an aside, in the other places, where the --requestor can be specified (like `galasactl runs submit`), the --requestor parameter does default to your current user id.

**Comment by techcobweb** [comment]
cc: @CaroMac ^^

**Comment by CaroMac** [comment]
chatted with Mike and closed this as it is published.
