### ISSUE TITLE
HTTP Client has no documentation

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#157]
Although this is in BETA there should be some doc for it

**Comment by cxharris** [comment]
Available for review here: https://next--galasa.netlify.app/docs/managers/http-client-manager

**Comment by hobbit1983** [comment]
Looks good Clive, do any over the Javadoc comments need updating?

**Comment by cxharris** [comment]
Let me check - and thanks for reminding me.

**Comment by cxharris** [comment]
I think *this* issue can close but I've opened issue #283 to record the fact that the JavaDoc needs improving.
