### ISSUE TITLE
Exploring SimBank (CLI)

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1578]
## Story
As a tester, I want to explore Galasa SimBank from the CLI, so that I can understand more about Galasa. I also want to view results locally.

## Background
In the Eclipse section we have a topic about how to explore Galasa SimBank and use a 3270 emulator. We need the equivalent section in the CLI

## Tasks
- [ ] Document exploring SimBank in CLI
- [ ] Document viewing results locally

**Comment by techcobweb** [comment]
Approved to be merged.
Caroline has simbank tests running in the CLI.
Re-testing prior to merge needs doing.

**Comment by techcobweb** [comment]
merged in vnext.
Mike to review for a last look before merging into prod.
