### ISSUE TITLE
Run LinuxFoundation (LF) Security Scans

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/projectmanagement#1586]
Start to get the Linux Foundation to run periodic security scans for the Galasa Repos.

Steps:

- [ ] Get the Repos linked via the LF App to the security bot.
- [ ] Check whether the scans have run.

**Comment by techcobweb** [comment]
From Louisa to Jeff Shapiro:
> Hey Jeff,

> I’ve added the galasa-dev repository to the security portal on the control panel for the projects. The current status is showing that it’s tried to scan all the repos and they’ve all failed. Also, Galasa doesn’t appear on the Security portal ([here](https://security.lfx.linuxfoundation.org/#/)).
 
> Would love your help to understand how the security scanning works and whether there’s a way that we can retry scans.
 
>Many thanks,
>Louisa

**Comment by techcobweb** [comment]
From Jeff S:

> Hi Louisa,

> The best way to get help with this is to submit a support ticket on the LFX Support page:
[https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4](https://urldefense.proofpoint.com/v2/url?u=https-3A__jira.linuxfoundation.org_plugins_servlet_desk_portal_4&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=sh-bFXwwn0eKcT6GdXdKZXoOAPBmhYAJmiJe8NgG6Ws&m=vaPWcOsSt1NFgs8KXa7yBCWMnomGs1aozXLlgTtQ7zXBIqygwfH8m9niIyyXTeGm&s=8F5545HlLkbIqoMlJhnnmDurDWBjz6Tm1u6kVJKVXMI&e=)

> Then select the best option from the menu on the left on the support page, hope this helps!

> Thanks, Jeff

**Comment by louisa-seers** [comment]
Updated a support ticket: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-21333

**Comment by techcobweb** [comment]
Checked the site today, and no changes. Galasa tile is still missing.

**Comment by louisa-seers** [comment]
Derrick Dobson commented:

Hello Louisa, sorry for the delay on this. You need a manifest file in the directories that are scanned. This is from Snyk "Snyk uses your project manifest file to analyze your projects for vulnerabilities. When you import a project for monitoring, Snyk scans the project to locate the manifest file and then remembers where that file is. Snyk then scans your project again whenever a webhook event occurs and also on a regular basis based on your configurations, based on the manifest file at its originally identified location."

We are still working on another issue though. I would suggest looking at some help docs from Skyk if needed. 

Thank you.

---

Looks like we may have to look through the docs here: https://docs.snyk.io/?_gl=1*13h4r66*_ga*MTI0MTMwMTcwNC4xNzAwNDc0Nzg1*_ga_X9SH3KP7B4*MTcwMDQ3NDc4Ni4xLjEuMTcwMDQ3NDc5Ni4wLjAuMA..

**Comment by techcobweb** [comment]
Blocked currently due to copyright and licenseing content being in the open source repos.

**Comment by louisa-seers** [comment]
Latest comments on the Jira issue:

Derrick Dobson - Thursday 28 December 11:19 AM

> Hello Louisa Seers, following up on this, were you able to get the manifest files added? Thank you.

Louisa Seers - Friday 29 December 14:15

> Hi Derrick, I think we have two conflicting issues going on which has meant this is slow progress. We're tracking it through this issue: https://github.com/galasa-dev/projectmanagement/issues/1586.
None of our team have any experience with Snyk so we don't really know what we're doing. Do you have any examples of Snyk manifest files or where they sit? The documentation isn't overly clear on how to set it up without a CLI.

**Comment by techcobweb** [comment]
Snyk can work in CLI or Github integration modes. It looks for Makefiles, gradle and maven files to build dependency tree information.
... those are the 'manifest' files I believe
Or is Derek talking about extra .snyk rules files which are also used, to ignore some warnings and set policies up.. etc... ?
Using snyk with Github integration seems powerful and easier than adding it into our build processes using the CLI.

I had a 'play' with the free snyk account (limited scans and little reporting) and got to this point just by adding the public github repos: https://app.snyk.io/invite/link/accept?invite=96c7e5f6-9bdd-47a3-86f5-226283cb2c62&utm_source=link_invite&utm_medium=referral&utm_campaign=product-link-invite&from=link_invite

So I'm still wondering what else we need to do to enable this really ?

**Comment by louisa-seers** [comment]
I have sent your comments back to Derek, I'll see if we can get a call with him to talk it through - all a bit disjointed at the moment. Will update you as soon as I hear more.

**Comment by louisa-seers** [comment]
This has been updated and we now have visibility of the Galasa security dashboard.

**Comment by techcobweb** [comment]
These appear to be working now. See the LF/OMP pages and drill into the Galasa content.

**Comment by techcobweb** [comment]
And we have enabled snyk ourselves anyway. And codeQL scans. And Dependabot.
