### ISSUE TITLE
Gherkin: Scenario Outline and Examples functionality in feature file and combination of keys - backtab

### ISSUE THREAD

**Issue by karth4u** [galasa-dev/projectmanagement#1589]
## Story
i) As an automation tester, we would require passing multiple sets of test data for a user scenario using Scenario Outline and the Examples section in the feature file. 
Please find the example given below.:
```
Feature: Calculator
  As a user
  I want to use a calculator to add numbers
  So that I don't need to add myself

Scenario Outline: Add two numbers <num1> & <num2>
    Given I have a calculator
    When I add <num1> and <num2>
    Then the result should be <total>

Examples:
    | num1 | num2 | total |
    | -2 | 3 | 1 |
    | 10 | 15 | 25 |
    | 99 | -99 | 0 |
    | -1 | -10 | -11 |
```

ii) To do Backtab operation on CICS screen, Shift+Tab keys functionality needs to be added to automate the user scenarios.

**Comment by hobbit1983** [comment]
To clarify part ii, is this to add the existing backtab capability that exists in Terminal to be invokable through gherkin?

**Comment by karth4u** [comment]
Yes, to add the existing backtab capability through Gherkin.

**Comment by hobbit1983** [comment]
Added a PR for the backtab gherkin capability

**Comment by hobbit1983** [comment]
https://github.com/galasa-dev/framework/pull/427 should be the PR to add the example variables into the framework.  However there is a merge conflict there that will need to be resolved.  Will check on monday

**Comment by karth4u** [comment]
Thank you, for the immediate action on the new feature requests.

**Comment by hobbit1983** [comment]
OK will take a look at this update

**Comment by techcobweb** [comment]
@hobbit1983 What's the latest status of this one please ?

**Comment by hobbit1983** [comment]
Just taken a look,  CLEAR support is already in the gherkin code, once the attached PR is merged then this should be closable @karth4u do you agree?

**Comment by karth4u** [comment]
> Just taken a look, CLEAR support is already in the gherkin code, once the attached PR is merged then this should be closable @karth4u do you agree?

**Comment by karth4u** [comment]
Hi Will, 
The expected behavior is to clear the text displayed on the CICS screen for a chosen field for example: a lable name followed by the old value that should be cleared and enter the new value for the lable field. 

If we use CLEAR that is defined in the gherkin, it will clear the entire CICS screen and populates the cursor at the start position.

**Comment by techcobweb** [comment]
This story is marked as 'in review' What needs to happen before we can close it ? or re-queue it for attention please ?

**Comment by techcobweb** [comment]
The example in the story doesn't relate at all to Galasa. Can we have a more relevant example please ?

What does part (ii) actually mean ? the context insn't conveyed very clearly...

**Comment by techcobweb** [comment]
@hobbit1983 Now that 0.31.0 has shipped, is this closeable ?

**Comment by techcobweb** [comment]
@hobbit1983 Now that 0.31.0 has shipped, is this closeable ?
