### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1591]
I upgraded my Windows gradle to 8.2

Fails to build with

C:\temp\GLTest\com.ibm.cics.test.runtimes>gradle build publishToMavenLocal
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.<init>(Lorg/gradle/api/provider/Provider;)V (loaded from file:/C:/Gradle/gradle-8.2/lib/plugins/gradle-dependency-management-8.2.jar by MixInLegacyTypesClassLoader(legacy-mixin-loader)) called from class dev.galasa.gradle.obr.ObrPlugin (loaded from file:/C:/temp/gradle/caches/modules-2/files-2.1/dev.galasa/dev.galasa.gradle.impl/0.15.0/a1faaaca04936fa8b258265128dbdf10f129c8d1/dev.galasa.gradle.impl-0.15.0.jar by InstrumentingVisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:root-project[:]:project-com.ibm.cics.test.runtimes.obr(export)})).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 30s

**Comment by techcobweb** [comment]
This issue got lost for a bit as it was raised directly against the CLI repo.
It has now been moved to the projectmanagement repo so it appears on our KanBan board.

**Comment by techcobweb** [comment]
Is this still an issue for you @ChrisAtkinson1 ?

Galasa uses gradle 6.9.2 for everything currently, so this might be due to that.

Does this issue go away if you down-grade your gradle version ?

**Comment by ChrisAtkinson1** [comment]
I does work at 6.9.2 - which is almost 2 years old now.

**Comment by ChrisAtkinson1** [comment]
Note the DOCS on galasa.dev

`All Galasa versions are compatible with Gradle releases 6.8.x and later.`

**Comment by CaroMac** [comment]
Apologies, I noticed that the other day and have a PR in review where I have updated it to say All Galasa versions are compatible with Gradle 6.x.x releases. Meeting with Mike shortly so can published the correction once I have checked it with him.

**Comment by techcobweb** [comment]
Publication have been changed to be more specific. Gradle 6-7.x should work, v8 won't work as they changed the API in an incompatible way.
