### ISSUE TITLE
CLI : tests exercise galasactl properties get/set/delete

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1602]
## Story
As a galasa developer I want to see test results on every build to show that the galasactl properties commands all work still, so I have a warm feeling that my build didn't break anything.

## Background
We are missing such tests in the test-galasactl-ecosysyem scripts. Need to add them.

## Tasks
- [x] Add tests to list, create, update, get, and delete properties to the test-galasactl-ecosysyem script in the CLI repo.
- [x] Test against the ecosystem.
- [x] Merged.

**Comment by Wyvinar** [comment]
Thought comments: 
- should creating and deleting a namespace also be tested?
- should namespace + property name be randomly generated or just property name?
