### ISSUE TITLE
CLI: incorrect cli go module name

### ISSUE THREAD

**Issue by jt-nti** [galasa-dev/projectmanagement#1608]
## Describe the bug

The module name is currently

```
github.com/galasa.dev/cli
```

however it should be

```
github.com/galasa-dev/cli
```

to match the GitHub repository path.

## Steps to reproduce

1. Run `go install github.com/galasa-dev/cli/cmd/galasactl@latest`
2. See error

```
go: github.com/galasa-dev/cli/cmd/galasactl@latest: version constraints conflict:
        github.com/galasa-dev/cli@v0.29.0: parsing go.mod:
        module declares its path as: github.com/galasa.dev/cli
                but was required as: github.com/galasa-dev/cli
```

## Expected behavior

Able to use `go install` without errors.

**Comment by techcobweb** [comment]
Well spotted. We'll do that as soon as the release 0.30.0 is done.
