### ISSUE TITLE
Eclipse Plugin: NullPointerException thrown when initialising Galasa

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1613]
## Describe the bug
When initialising Galasa using the Eclipse plugin (version 0.30.0, tested on Eclipse 2023-03), a NPE is thrown (see below for the stack trace), preventing users from running tests.

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at dev.galasa.framework.FrameworkInitialisation.locateConfigurationPropertyStore(FrameworkInitialisation.java:377)
	at dev.galasa.framework.FrameworkInitialisation.<init>(FrameworkInitialisation.java:115)
	at dev.galasa.framework.FrameworkInitialisation.<init>(FrameworkInitialisation.java:68)
	at dev.galasa.eclipse.framework.management.InitialiseFrameworkJob.run(InitialiseFrameworkJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

After a brief look into the source of this issue, it looks like a recent change to how FrameworkInitialisation locates GALASA_HOME has caused this (see https://github.com/galasa-dev/framework/commit/ea443c04d107548a5e1b649fa9ef1e3821579abf). The framework looks for a `framework.galasa.home` property within bootstrap.properties, and uses this value to locate the CPS. If this property doesn't exist, then `galasaHome` will be null.

In FrameworkInitialisation:
```
this.galasaHome = bootstrapProperties.getProperty("framework.galasa.home");
```

In locateConfigurationPropertyStore:
```
Path path = Paths.get(this.galasaHome , "cps.properties");
```

## Workaround
As a temporary workaround for this issue, add the following property to your `bootstrap.properties` file in your Galasa home directory:

```
framework.galasa.home=/path/to/galasa/home
```

Example for macOS:

```
framework.galasa.home=/Users/<user>/.galasa
```

Also ensure that the value of "Bootstrap URI" in Eclipse Preferences > Galasa is pointing to the correct `bootstrap.properties` file in your Galasa home directory. Keep the `file://` prefix in this URI.

When initialising the framework, the NPE will not be thrown.

Alternatively, you could use the [CLI](https://github.com/galasa-dev/cli) to run tests.

## Steps to reproduce
1. Install 0.30.0 of the Eclipse Plugin
2. Click on Galasa > Initialise Galasa Framework
3. Encounter NPE (for the stack trace, go to Window > Show View > Error Log, then double-click on the latest failure)

## Expected behavior
The Galasa framework initialises with no error.

# Tasks
- [x] Fix the framework code
- [ ] Confirm that the eclipse code does not suffer this issue now.

**Comment by techcobweb** [comment]
Might this explain issue [CLI can list available streams#1615](https://github.com/galasa-dev/projectmanagement/issues/1615) ?

**Comment by techcobweb** [comment]
The code which previously dealt with GALASA_HOME was moved into the boot jar. But eclipse doesn't use the boot jar, so it needs re-adding to the base framework code.

**Comment by techcobweb** [comment]
See https://github.com/galasa-dev/framework/pull/464
