### ISSUE TITLE
CLI: property created using galasactl resources apply/create/update -f xxx.yaml

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1619]
# Story
As a galasa ecosystem admin I want to apply a yaml file to the ecosystem so that it is easy to set the configuration of the ecosystem from an automated CI/CD pipeline, using checked-in resource files.

# Background
Support this syntax:
```
$ galasactl resources create -f xxx.yaml
```
Such that xxx.yaml contains:
```
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
  name: my.property
  namespace: myNamespace
data:
  value: xxxxx
```

The REST call used is POST `/.../resources`
such that the payload is this:
```
{
  {
    action: "apply"
    data: [{
      apiVersion: galasa-dev/v1alpha1
      kind: GalasaProperty
      metadata:
        name: my.property
        namespace: myNamespace
      data:
        value: xxx
    }]
  }
}
```

Returns:

200:
```
<no payload. Everything worked>
```

If it's a create... 
The REST call used is POST `/.../resources`
such that the payload is this:
```
{
  {
    action: "create"
    data: [{
      apiVersion: galasa-dev/v1alpha1
      kind: GalasaProperty
      metadata:
        name: my.property
        namespace: myNamespace
      data:
        value: xxx
    }]
  }
}
```

Returns:

200:
```
<no payload. Everything worked>
```

400:
```
[
  {
    error_code: 
    error_message: GALxxxE: could not create property my.property in namespace myNamespace because it already exists.
  } 
]
```

File can have multiple properties defined in the yaml, separated by `---`

# Background
- [x] new endpoint/servlet
- [x] Incorrect apiVersion: galasa-dev/v1alpha1 needs to fail with 400 Bad input
- [x] Incorrect kind: GalasaProperty needs to fail, with a list of valid kinds that the endpoint understands (currently only GalasaProperty)
- [x] Missing name/namespace/value cause 400 BAD input with explanations why.
- [x] Servlet supports the "create" action 
  - [x] Create action fails if the property already exists
- [x] Servlet supports the "update" action
  - [x] Update action fails if the property does not already exist
- [x] Servlet supports the "apply" action
- [x] OpenAPI rest interface defined, such that the payload is an opaque json object. eg: AnyValue: {} See https://stackoverflow.com/questions/32841298/openapi-what-schema-to-accept-any-complex-json-value

- [x] CLI has the command.
- [x] File specified gets read and used, or error if not found/bad format.
- [x] Try to minimise the amount of checking done in the CLI, as the servlet has to do all that anyway.
- [x] CLI should not need to know the format of the yaml file. It should just take the yaml and convert it into json to 
    - [x] pass to the api
- [x] File can have multiple properties inside, with `---` separators, and they all get used.
- [x] CLI supports apply
- [x] CLI supports create
- [x] CLI supports update
- [x] README updates
- [x] galasa.dev website docs updates

**Comment by techcobweb** [comment]
Savvas says: Docs need closing-out.

**Comment by CaroMac** [comment]
this PR https://github.com/galasa-dev/galasa.dev/pull/740 contains 1617, 1619, 1687, and 1651 - they all were using the same files so have done them in one PR.
