### ISSUE TITLE
Incomplete Spool Retrieval for Batch when JCL was multiple PROCS

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1632]
## Describe the bug
If I am submitting a piece of JCL which has multiple PROCS, e.g:
```
//*---------------------------------------------------------------------
//*
//* COBOL COMPILEPROGRAM
//*
//*---------------------------------------------------------------------
//COBOL    EXEC PGM=IGYCRCTL,REGION=0M,
// PARM='MAP,OFFSET,SQL'
//STEPLIB  DD DISP=SHR,DSN=IGY.V6R3M0.SIGYCOMP
//         DD DISP=SHR,DSN=CEE.SCEERUN
//         DD DISP=SHR,DSN=CEE.SCEERUN2
//         DD DISP=SHR,DSN=DSN.V12R1M0.SDSNLOD2
//         DD DISP=SHR,DSN=DSN.V12R1M0.SDSNLOAD
//SYSLIB   DD DISP=SHR,DSN=CEE.SCEESAMP
//         DD DISP=SHR,DSN=DSN.V12R1M0.SDSNSAMP
....
//*---------------------------------------------------------------------
//CHECK001 IF RC LE 4 THEN
//LKED     EXEC PGM=IEWL,REGION=0M,
// PARM='LIST,XREF,RENT,MAP'
//SYSLIB   DD DISP=SHR,DSN=CEE.SCEELKEX
//         DD DISP=SHR,DSN=CEE.SCEELKED
//         DD  DISP=SHR,DSN=DSN.V12R1M0.SDSNLOAD
//SYSLIN   DD *
  INCLUDE SYSLIB(DSNELI)
//         DD DISP=(OLD,DELETE),DSN=&&SYSLIN
//         DD *
  NAME ++PGMNAME++(R) 
//SYSUT1   DD UNIT=SYSALLDA,BLKSIZE=1024,                  
//            SPACE=(1024,(200,20))
//SYSPRINT DD SYSOUT=*
//SYSLMOD  DD DISP=SHR,DSN=++SYSLMOD++(++PGMNAME++)
//CHECK001 ENDIF
```
The  when I receive the downloaded spool from the job, I can only see one :
![image](https://github.com/galasa-dev/projectmanagement/assets/55880188/2514e7d9-bafb-477d-92d4-f102b2797ffc)
The stranger behaviour is that the COBOL_SYSTPRINT actually contains the output from LKED, so i can no longer see the COBOL_SYSPRINT

## Steps to reproduce
Submit batch job with multiple procs.

## Expected behavior
I would expect to see COBOL_SYSTPRINT and LKED_SYSTPRINT within the pool

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.

**Comment by techcobweb** [comment]
As I'm out for a few days (back next Tues), I think asking @eamansour to look at this makes sense. Cleared that with Roger first, and just asked Eamon on slack...

**Comment by Jimbo4794** [comment]
Thanks

**Comment by eamansour** [comment]
Found out why this is happening - the batch manager's `addSpoolFile` updates the content of a spool file if the DD name associated with the spool file already exists:
```
//the outline of the spool may already exist.  BUT the content might not - if it exists then update it
for(IZosBatchJobOutputSpoolFile spool : spoolFiles){
    if(ddname.equals(spool.getDdname())){
        spool.setRecords(records);
        return;
    }
}
//if we get here then the spool doesn't already exist so add it
spoolFiles.add(new ZosBatchJobOutputSpoolFileImpl(...));
```
Here, the COBOL step uses the DD name "SYSPRINT" and so does the LKED step, so the output from COBOL is overwritten with the output from LKED. Will need to look into why this was added.

**Comment by eamansour** [comment]
Fix merged into main and will be delivered as part of 0.31.0.
