### ISSUE TITLE
Delete unusued Jenkinsfiles throughout the codebase

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1639]
When looking through the code base this week, I noticed a few files which are no longer used and should no longer be checked into the project, such as Jenkinsfiles for the old pipelines.

- [x] extensions x2 files 
  - [x] Jenkins mentioned in README
- [x] managers
  - [x] Jenkins mentioned in githubdocs script
  - [x] Jenkins mentioned HttpManagerIVT
- [x] maven
- [x] integratedtests x2 files

**Comment by techcobweb** [comment]
Suggest @Wyvinar does this one ?

**Comment by jadecarino** [comment]
I agree

**Comment by techcobweb** [comment]
@Wyvinar what's the status of this story please ?
