### ISSUE TITLE
'galasactl runs submit local --debug' failed with GAL1057E

### ISSUE THREAD

**Issue by drimmeer** [galasa-dev/projectmanagement#1648]
## Describe the bug
When I tried to debug my sample test case using Galasa CLI command, starting the JVM failed, with errors:

> 		2023/11/24 16:04:03 Don't have enough information to find the structure.json in the RAS folder.
> 		2023/11/24 16:04:03 waiting for the JVM to complete within a go routine.
> 		2023/11/24 16:04:03 Failed to wait for the JVM test to complete. exit status 2
> ....
> 		GAL1057E: The run identifier could not be detected in trace output of the child process
> 

## Steps to reproduce
1. On my Mac's Terminal, I issued command:
2.		galasactl runs submit local --debug --log - \
		--obr mvn:my.galasa.cics1/my.galasa.cics1.obr/0.0.1-SNAPSHOT/obr \
		--class my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1Extended

3. The command failed with the error as shown in '**### Additional context**'

## Expected behavior
The JVM is started, waiting for the Java Debugger to attach to it.

## Additional context
(Please note that running the same command **without the --debug** option **worked** well).

> 2023/11/24 16:19:21 Galasa CLI - Submit tests (Local)
> 2023/11/24 16:19:21 Galasa home is '/Users/myName/.galasa'
> 2023/11/24 16:19:21 Creating file of type jar at /Users/myName/.galasa/lib/0.30.0/galasa-boot-0.30.0.jar
> 2023/11/24 16:19:21 File /Users/myName/.galasa/lib/0.30.0/galasa-boot-0.30.0.jar exists, no need to create it then.
> 2023/11/24 16:19:21 Creating file of type properties at /Users/myName/.galasa/bootstrap.properties
> 2023/11/24 16:19:21 File /Users/myName/.galasa/bootstrap.properties exists, no need to create it then.
> 2023/11/24 16:19:21 Creating file of type properties at /Users/myName/.galasa/overrides.properties
> 2023/11/24 16:19:21 File /Users/myName/.galasa/overrides.properties exists, no need to create it then.
> 2023/11/24 16:19:21 Creating file of type properties at /Users/myName/.galasa/cps.properties
> 2023/11/24 16:19:21 File /Users/myName/.galasa/cps.properties exists, no need to create it then.
> 2023/11/24 16:19:21 Creating file of type properties at /Users/myName/.galasa/dss.properties
> 2023/11/24 16:19:21 File /Users/myName/.galasa/dss.properties exists, no need to create it then.
> 2023/11/24 16:19:21 Creating file of type properties at /Users/myName/.galasa/credentials.properties
> 2023/11/24 16:19:21 File /Users/myName/.galasa/credentials.properties exists, no need to create it then.
> 2023/11/24 16:19:21 Using group name '8cffd5fb-f149-4ec8-a077-fd20453ba5dd' for test run submission
> 2023/11/24 16:19:21 JvmLauncher: GetRunsByGroup(groupName=8cffd5fb-f149-4ec8-a077-fd20453ba5dd) entered. 
> 2023/11/24 16:19:21 JvmLauncher: GetRunsByGroup(groupName=8cffd5fb-f149-4ec8-a077-fd20453ba5dd) exiting. isComplete:true testRuns returned:0
> 2023/11/24 16:19:21     Selected test class 'my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1'
> 2023/11/24 16:19:21 Added test /my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1 to the ready queue
> 2023/11/24 16:19:21 JvmLauncher: SubmitTestRun entered. group=8cffd5fb-f149-4ec8-a077-fd20453ba5dd className=my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1 requestType=CLI requestor=myName stream= isTraceEnabled=false
> 2023/11/24 16:19:21 Properties file /var/folders/xq/23znt8gd1lg5pbkyrd47b83h0000gn/T/galasa-4208350102overrides.properties written containing this:
> framework.request.type.LOCAL.prefix=L
> framework.resultarchive.store=file:////Users/myName/.galasa/ras
> zos3270.terminal.output=json,png
> 2023/11/24 16:19:21 Launching command '/Library/Java/JavaVirtualMachines/ibm-semeru-certified-11.jdk/Contents/Home/bin/java' '[-agentlib:jdwp=transport=dt_socket,address=*:2970,server=y,suspend=y -jar /Users/myName/.galasa/lib/0.30.0/galasa-boot-0.30.0.jar -Dfile.encoding=UTF-8 -DGALASA_HOME="/Users/myName/.galasa" --localmaven file:////Users/myName/.m2/repository --remotemaven https://repo.maven.apache.org/maven2 --bootstrap file:////Users/myName/.galasa/bootstrap.properties --overrides file:////var/folders/xq/23znt8gd1lg5pbkyrd47b83h0000gn/T/galasa-4208350102overrides.properties --obr mvn:my.galasa.cics1/my.galasa.cics1.obr/0.0.1-SNAPSHOT/obr --obr mvn:dev.galasa/dev.galasa.uber.obr/0.30.0/obr --test my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1]'
> 2023/11/24 16:19:21 JVM test started. Spawning a go routine to wait for it to complete.
> 2023/11/24 16:19:21 Don't have enough information to find the structure.json in the RAS folder.
> 2023/11/24 16:19:21 waiting for the JVM to complete within a go routine.
> 2023/11/24 16:19:21 Failed to wait for the JVM test to complete. exit status 2
> 2023/11/24 16:19:21 Don't have enough information to find the structure.json in the RAS folder.
> 2023/11/24 16:19:21 Interrupting the timing service sleeping. Test run  completed.
> 2023/11/24 16:19:22 Message received from JVM launch thread: DONE
> 2023/11/24 16:19:22 Don't have enough information to find the structure.json in the RAS folder.
> 2023/11/24 16:19:22 goroutine 1 [running]:
> github.com/galasa.dev/cli/pkg/errors.LogStackTrace()
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/errors/debug.go:18 +0x38
> github.com/galasa.dev/cli/pkg/errors.NewGalasaError(0x140000d8700, {0x0?, 0x14000188d18?, 0x100ed553c?})
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/errors/errorMessage.go:66 +0xb4
> github.com/galasa.dev/cli/pkg/launcher.(*LocalTest).waitForRunIdAllocation(0x140000ea900, 0x140001cc060)
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/launcher/localTest.go:163 +0xe8
> github.com/galasa.dev/cli/pkg/launcher.(*LocalTest).launch(0x140000ea900, {0x1400008c480, 0x54}, {0x1400019c200, 0x13, 0x20})
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/launcher/localTest.go:96 +0x26c
> github.com/galasa.dev/cli/pkg/launcher.(*JvmLauncher).SubmitTestRun(0x140001c4000, {0x140000bc4e0, 0x24}, {0x140000fc640, 0x48}, {0x100ef1388, 0x3}, {0x140000a6be0, 0x8}, {0x0, ...}, ...)
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/launcher/jvmLauncher.go:237 +0x49c
> github.com/galasa.dev/cli/pkg/runs.(*Submitter).submitRun(0x14000189cd8, {0x140000bc4e0, 0x24}, {0x140000b8420, 0x1, 0x1}, 0x7c?, 0x1017050c0?, 0x0?, 0x0?, ...)
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/runs/submitter.go:306 +0x250
> github.com/galasa.dev/cli/pkg/runs.(*Submitter).executeSubmitRuns(0x14000189cd8, {0x1e, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x140000bc4e0, ...}, ...}, ...)
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/runs/submitter.go:147 +0x504
> github.com/galasa.dev/cli/pkg/runs.(*Submitter).executePortfolio(0x140001c4000?, 0x1400003000a?, 0x640?, {0x1e, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/runs/submitter.go:94 +0x60
> github.com/galasa.dev/cli/pkg/runs.(*Submitter).ExecuteSubmitRuns(0x0?, {0x1e, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x140000bc4e0, ...}, ...}, ...)
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/runs/submitter.go:72 +0xc4
> github.com/galasa.dev/cli/pkg/cmd.executeSubmitLocal(0x14000197000?, {0x14000199570?, 0x4?, 0x100ef16b0?})
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/cmd/runsSubmitLocal.go:146 +0x384
> github.com/spf13/cobra.(*Command).execute(0x1016ff960, {0x14000199500, 0x7, 0x7})
> 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x53c
> github.com/spf13/cobra.(*Command).ExecuteC(0x1016fdde0)
> 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x310
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
> github.com/galasa.dev/cli/pkg/cmd.Execute()
> 	/workspace/git/trigger-cli-release-qvp84/cli/pkg/cmd/root.go:50 +0x40
> main.main()
> 	/workspace/git/trigger-cli-release-qvp84/cli/cmd/galasactl/main.go:13 +0x1c
> 
> 2023/11/24 16:19:22 Failed to submit test my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1 - GAL1057E: The run identifier could not be detected in trace output of the child process
> GAL1093E: Failed to submit test (bundle: my.galasa.cics1.jln1, class: my.galasa.cics1.jln1.TestJln1). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
> 2023/11/24 16:19:22 JvmLauncher: GetRunsByGroup(groupName=8cffd5fb-f149-4ec8-a077-fd20453ba5dd) entered. 
> 2023/11/24 16:19:22 JvmLauncher: GetRunsByGroup(groupName=8cffd5fb-f149-4ec8-a077-fd20453ba5dd) exiting. isComplete:true testRuns returned:0
> 2023/11/24 16:19:22 GAL1093E: Failed to submit test (bundle: my.galasa.cics1.jln1, class: my.galasa.cics1.jln1.TestJln1). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
> GAL1093E: Failed to submit test (bundle: my.galasa.cics1.jln1, class: my.galasa.cics1.jln1.TestJln1). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
> 2023/11/24 16:19:22 Exit code is 1
> 
>

**Comment by techcobweb** [comment]
Can you try this please:

```
cd /Users/myName/.galasa
mkdir temp
cd temp
cat << EOF >> cps.properties
framework.request.type.LOCAL.prefix=L
framework.resultarchive.store=file:////Users/myName/.galasa/ras
zos3270.terminal.output=json,png
EOF

/Library/Java/JavaVirtualMachines/ibm-semeru-certified-11.jdk/Contents/Home/bin/java \
-agentlib:jdwp=transport=dt_socket,address=*:2970,server=y,suspend=y \
-jar /Users/myName/.galasa/lib/0.30.0/galasa-boot-0.30.0.jar \
-Dfile.encoding=UTF-8 \
-DGALASA_HOME="/Users/myName/.galasa" \
--localmaven file:////Users/myName/.m2/repository \
--remotemaven https://repo.maven.apache.org/maven2 \
--bootstrap file:////Users/myName/.galasa/bootstrap.properties \
--overrides file:////vUsers/myName/.galasa/temp/cps.properties \
--obr mvn:my.galasa.cics1/my.galasa.cics1.obr/0.0.1-SNAPSHOT/obr \
--obr mvn:dev.galasa/dev.galasa.uber.obr/0.30.0/obr \
--test my.galasa.cics1.jln1/my.galasa.cics1.jln1.TestJln1

rc=$?
echo "return code is $rc
```

**Comment by drimmeer** [comment]
Thank you.

I got this error when executing the commands got from you:

> zsh: no matches found: -agentlib:jdwp=transport=dt_socket,address=*:2970,server=y,suspend=y

**Comment by techcobweb** [comment]
The first sounds like you missed off the `\` characters to make it one command...

The second one means something is already using that port.

What does your bootstrap.properties file contain ?
How is your IDE set up ?

It's possible that you've set both up to be 'listeners' in server-mode, so both the IDE and the testcase JVM are trying to launch in the same mode, and listen for people connecting, but the IDE has got there first, so the testcase fails to create the listener on that port (you can only have one listener on one port at once).
Could that be the case perhaps ?
If so, you can turn either the IDE or the testcase to be a 'client' mode which tries to connect and talk to an open port which already has a listener attached.

If that's the case, then the error code shown by the galasactl tool is misleading at best, and needs to be more specific, that the JVM could not be launched I think.

**Comment by drimmeer** [comment]
Could you please help me out?
The major error is:


```
27/11/2023 11:50:41.274 DEBUG d.g.f.TestRunner - isRunOK: true runType: TEST
27/11/2023 11:50:41.274 DEBUG d.g.f.TestRunner - Test did not run OK... or runtype is not SHARED_ENVIRONMENT_BUILD
```

**Comment by drimmeer** [comment]
I found that now even my original command could be used to debug the Galasa test case!
So that means the root cause was that there was a JVM instance running, waiting for a Debugger.

So this ticket can be closed.
Thank you for your help!
