### ISSUE TITLE
Blog & Video: How to install the CLI and get started from scratch

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/projectmanagement#1654]
## Story
As a user, I want to understand how to get up and running with the CLI and I may not find this information directly through the website.

## Background
Any additional information that would help to explain the story.

## Tasks
- [ ] Write a blog and/or video to detail the step by step.

**Comment by techcobweb** [comment]
@louisa-seers I think this is already done here : https://www.youtube.com/watch?v=lwYOwJZ4Q8Q&t=513s ? or are we looking for something else ?

The docs in galasa-dev pretty much contain the same information, so any blog might duplicate lots of info.

**Comment by louisa-seers** [comment]
@jadecarino and I agreed that a blog would be really good to accompany this - I wouldn't worry too much about duplication as the audience may be different.

**Comment by CaroMac** [comment]
@louisa-seers @jadecarino Please can you include myself  in discussions around content going forward. I did actually think about writing up my experience of getting started using the CLI as a blog but in a way that would not mirror the website content. I do worry about duplication. The audience may not be that different and unless the content is written differently to the website it could create confusion about the best place to go to find information in the first instance, and if something changes or is written in an inconsistent way then the information provided in the two places could also become confusing.

**Comment by techcobweb** [comment]
What is under review here now ?

**Comment by louisa-seers** [comment]
@CaroMac - is this the blog you've sent for review to Mae through the OMP?

**Comment by CaroMac** [comment]
Hi, I have sent it over to Vera in the content team for review. She has the same laptop as me but with none of the pre req software installed so I asked her to review it from a blog and installing perspective before I sent it off to Mae. Sorry I should have added that info in a comment.

**Comment by CaroMac** [comment]
With Mae
