### ISSUE TITLE
Blog: What is Application Integration Testing?

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/projectmanagement#1657]
## Story
As a user, I want to understand what application integration testing is and how it can be useful to my organisation or work.

## Background
Any additional information that would help to explain the story.

## Tasks
- [ ] Write a blog on application integration testing.

**Comment by techcobweb** [comment]
@louisa-seers This is your top suggestion for articles. Is this something you are able to do ? or do we need to allocate someone in the team to work on this ? I'm pretty sure James/Will have this type of thing written up already somewhere, but it might be buried...

**Comment by louisa-seers** [comment]
Hey, the blogs/videos list isn't in any particular order of preference - any blogs are good. I wonder whether James or Will have slide ware I can grab from to write the blog. Let me have a look and/or have a chat to Will/James to see if they have anything I can use as inspiration! Happy to write the blog for this.

**Comment by louisa-seers** [comment]
I have submitted the blog to Mae for review.

**Comment by louisa-seers** [comment]
https://openmainframeproject.org/blog/what-is-application-integration-testing/
