### ISSUE TITLE
Simbank does not working with ZOC7

### ISSUE THREAD

**Issue by sayom88** [galasa-dev/projectmanagement#166]
Hello,

In the current Galasa's Simbank application,it seems it doesnt work with ZOC7. Kindly check.

Br,
Sayom

**Comment by Michael-Baylis** [comment]
Ok,   zoc7 is reponding with a terminal type of IBM-3279-2-E which we have not coded to accept.  Zoc7 should have retried with IBM-3278,  but not sure why not.
I need to understand what the differences are between 3278 and 9.   may be as simple as allowing 3279.

**Comment by Michael-Baylis** [comment]
closed by mistake

**Comment by Michael-Baylis** [comment]
I have added the 3279-2 2E and 3 devices to the acceptable list.   ZOC7 now works with the simbank application (although I couldn't get past the cics screen as couldn't figure out how to clear the screen).
The updates can be found in the plugin at https://p2snapshot.galasa.dev/
only the SimBank feature needs updating.
It will be in 0.7.0 targetted 30th April.
