### ISSUE TITLE
Release highlights and roadmap

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#167]
Suggested changes to design of front page to include link to sections on Release Highlights including roadmap and contributing pages.

**Comment by CaroMac** [comment]
Front page design, highlighting:

    Three Quick Start buttons, including the Releases button that is prefixed with V<release number>-
    Addition of a Release button on the main menu, which replicates the link in the Quick Start

![image.png](https://images.zenhubusercontent.com/5e971680326f9124fa876a8c/dc71a0ff-3ed8-487f-ae47-8ec623f4e75f)

Both the Quick Start Vx.y.z-Release Highlights button and the main menu Releases link will go to a content page like this (words & diagrams  TBD)

![image(1).png](https://images.zenhubusercontent.com/5e971680326f9124fa876a8c/02c0a1ed-3118-4bbe-ad03-4fdd18e2ef13)

**Comment by CaroMac** [comment]
From Greg : 
I've left the secondary menu options for licenses and contribute in to provoke discussion. As an open source project, I think we're obliged to publicise the licences - I guess they're in Git but no harm in replicating them on the site. The contribute option might be a good opportunity to link to a page describing how and why it's good to do that and maybe to link back into the docs particularly for how to write managers (especially ones to contribute back into the community)

**Comment by CaroMac** [comment]
From Greg Thu Mar 19th : Just asked Mike to give me a description of the roadmap, so I can make an SVG version from it

**Comment by CaroMac** [comment]
Note from Clive - need to check responsiveness of website is not affected post implementation

**Comment by lubelg** [comment]
I spoke to Mike last week or so and my understanding is that we'll not need the Galasa roadmap, as shown in the image above. Mike didn't want to show anything committing to 'future' work, in case things changed. I think there's no harm in bulleting current work that's in progress and therefore highly likely to be delivered. I think site visitors, who are adopting Galasa will want to know what's upcoming and likewise for those holding-off until functionailty they need is on the near horizon with at least some likelihood of delivery.

**Comment by lubelg** [comment]
Caroline and I talked through some of the details of the design (21st April '20) and I believe they will be implememented in the next few days

**Comment by pauline-andrews** [comment]
This issue per release, also to cover updating the list of Managers to current level (Alpha, Beta, Release).
