### ISSUE TITLE
Blog: First 6 Months as a TSC Chair for Galasa

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/projectmanagement#1681]
To write a blog that encapsulates the first 6 months in the Galasa project - what have we done, how did we get adoption?

**Comment by techcobweb** [comment]
@louisa-seers Where is the material published please ? Helps to put a link in here so we can find it based on the story ?

**Comment by louisa-seers** [comment]
Hey! I've submitted it to Mae to go on the OMP page. It doesn't include much about technical progress for Galasa though, wondered whether it was worth talking about whether we want to do one. It should be published here when it appears - https://openmainframeproject.org/news/blog/

I'll update when it's been uploaded so we can add it to the website.
