### ISSUE TITLE
CLI: change "galasactl resources apply/create/update" command to be galasactl apply/create/update

### ISSUE THREAD

**Issue by Akyiaa** [galasa-dev/projectmanagement#1684]
# Story
Linked to this story: https://github.com/galasa-dev/projectmanagement/issues/1619

The resources command has been implemented, but currently we have to add "resources" before apply/create/update and this should be changed such that the command can be written without "resources"

# Background
Currently the command is called like this:
```
$ galasactl resources create -f xxx.yaml
```

But we want to follow the kubectl fashion and not write "resources" as part of the command, such that the command is called like this:
```
$ galasactl create -f xxx.yaml
```

# Tasks
- [ ] Update cli commands
  - [ ] apply
  - [ ] create
  - [ ] update
- [ ] readme updates
- [ ] docs updates
- [ ] add tests to the `scripts/properties-test.sh`
  - galasactl properties delete --name xxx --namespace to delete the property. - it should work even if the property isn't present.
  - try updating a property using a pre-canned yaml file. It should fail.
  - create a property from a pre-canned yaml file.
  - get the yaml back and compare files (should match).
  - create the same property using a pre-canned yanml file. It should fail.
  - apply a second yaml file (which sets a different value).
  - get back and compare yaml files.
  - update the property back to what is was for the first yaml file
  - get back and compare yaml files.
  - delete the property using same cmd as above... it should work 
  - try to get the property back but it should fail as it's gone.

**Comment by techcobweb** [comment]
I think we should live with this now that it's done.
Next time the externals change, please can we discuss it before things get implemented, as there are reasons why the externals are specified in the stories...

**Comment by techcobweb** [comment]
lets not bother with this story now. Closing.
