### ISSUE TITLE
Ecosystem1 to re-deploy once the OBR project is built

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1689]
# Story
As a galasa developer I want the ecosystem deployed every time the main branch of the OBR project builds OK so that I can use up-to-date framework code in the ecosystem.

# Background
Currently it comes after the CLI builds, but that means if the CLI  build is broken, then the main galasa code doesn't get deployed until CLI works.

Would be much better to build the Galasa code, OBR, then helm + deploy, THEN build the CLI, as the CLI project build reaches out to the prod ecosystem (currently).

# Tasks
- [x] Change build order

**Comment by techcobweb** [comment]
cc: @eamansour

**Comment by eamansour** [comment]
This is complete - the helm pipeline triggers after obr-generic instead of triggering at the end of the pipeline chain.
