### ISSUE TITLE
CLI bug: resources update -f when a property doesn't exist fails to deliver error messages.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1692]
Create a new property name in a yaml file, and try to update it. It should fail (because the property doesn't exist yet), but the errors are not being formatted correctly:
>./bin/galasactl-darwin-arm64 resources update -f  my-properties.yaml
Error: json: cannot unmarshal string into Go value of type errors.GalasaAPIError

**Comment by Akyiaa** [comment]
- it should be trying to unmarshal the string into type `errors.GalasaAPIErrorsArray` instead of `errors.GalasaAPIError`

**Comment by techcobweb** [comment]
Right. Now that the parsing of errors in the better, I can see that the server is replying with this (from the cli log):
```
2023/12/15 10:13:13 sendResourcesRequestToServer Failed - HTTP response - status code:400 payload:[
  "{\"error_code\":5017,\"error_message\":\"GAL5017E: Error occured when trying to access property \u0027my.new.property\u0027. The property name provided is invalid.\"}"
```

- Http status is good. 400 Bad request.
- There is nothing wrong with the name of the property. Or should be nothing wrong. Why are we getting unicode characters returned in the string ? Something is uuencoding the json when it should be a byte array payload. ?

**Comment by Akyiaa** [comment]
Error handling and collation of errors list improved and merged: https://github.com/galasa-dev/cli/pull/189
