### ISSUE TITLE
CLI properties get/set/ and resources create/apply/update don't put enough detail in the log

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1694]
# Story
As a galasactl user, when Is see a failure when setting a property/getting a property, or using the resources APIs, I want to see enough detail in the debug log so that I can diagnose a problem with the functionality, enough to know whether it was the server
mis-behaving, or the client mis-behaving.

# Background 
We need more logging info in the client, like is it about to send something to the server ?
or it got something back from the server ?

Lets not log http payloads, but http responses and URLs we send stuff too would be helpful.

**Comment by Akyiaa** [comment]
more logging was added to the branch that the resources delete command is being worked `on.`

Properties Get now shows the cps properties returned from the api:
```
2024/01/03 10:06:32 GetProperties - Galasa Properties collected: [{ApiVersion:'galasa-dev/v1alpha1', Kind:'GalasaProperty', Namespace:'linux', Name:'image.GALLNX01.ipv4.hostname', Value:'9.20.206.13'}, ....., {ApiVersion:'galasa-dev/v1alpha1', Kind:'GalasaProperty', Namespace:'linux', Name:'image.GALLNX01.max.slots', Value:'12'}]
```

Properties Set:
```
2024/01/03 10:40:34 SetProperty - Galasa Property to update/create: ApiVersion:'galasa-dev/v1aplha1', Kind:'GalasaProperty', Namespace:'framework', Name:'user.test.example', Value:'value.example'
2024/01/03 10:40:34 updateCpsProperty - HTTP response status code: '400'
2024/01/03 10:40:34 createCpsProperty - HTTP response status code: '201'
```

Properties Delete:
For a failed path:
```
2024/01/03 11:21:32  deleteCpsProperty Failed - HTTP response - status code: '404' payload: '{...}'"
```
