### ISSUE TITLE
CLI: Get from non-existant namespace should cause an error ? Not return Total:0

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1705]
```
>./bin/galasactl-darwin-arm64 properties  get --namespace xyz123
Total:0
```
This might be debatable. Lets talk about it before deciding whether to change it or not.

**Comment by Akyiaa** [comment]
When a namespace with an invalid name is provided a 404 error is returned
```
> ./bin/galasactl-darwin-arm64 properties get --namespace 928
Error: GAL1096E: Could not query namespace results. Reason: '404 Not Found'
```

**Comment by Akyiaa** [comment]
This was resolved by using `checkNamespaceExists` in `handleGetRequest()` in `PropertyRoute.java` and updating relevant unit tests.
