### ISSUE TITLE
gson 2.10 illegal reflective access

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1716]
Noticed this in the building of the framework code:

➜ Using this command: gradle --build-cache --parallel     --console=plain     --warning-mode=all     -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/ibm-semeru-open-11.jdk/Contents/Home     -PsourceMaven=https://development.galasa.dev/main/maven-repo/obr/ -info     buildReleaseYaml build check jacocoTestReport     
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.ReflectionHelper (file:/Users/savvas/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10.1/b3add478d4382b78ea20b1671390a858002feb6c/gson-2.10.1.jar) to field java.time.Instant.seconds
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

So the new version of gson is doing something nasty ?

**Comment by techcobweb** [comment]
cc: @eamansour

**Comment by KirbyKatcher** [comment]
https://github.com/google/gson/issues/1807

Suggestion appears to need our own custom adapter to resolve this warning

**Comment by KirbyKatcher** [comment]
Create a GalasaGson Wrapper in framework to resolve issue

**Comment by KirbyKatcher** [comment]
Going to need GalasaGson Wrapper in extensions as well

**Comment by KirbyKatcher** [comment]
Need GalasaGson Wrapper in managers as well
