### ISSUE TITLE
Defect: Provision Stop phase skipped by TestRunner class

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1720]
## Describe the bug
The provision stop phase is currently unreachable code in the TestRunner class. Duplicating explanation from my PR here: https://github.com/galasa-dev/framework/pull/496 

"Currently, provision stop can only occur if the run type is not SHARED_ENVIRONMENT_BUILD. I think this is a mistake - Share Environment Builds are intended to keep the environment around after the test have been run. 

In the case where you are running a regular non-shared environment test run, the test environment will not have the Provision Stop phase run against it, but will later have Provision Discard run.

I was finding for my test environments the Provision Discard phase was timing out as the resources were being held onto because they had not been stopped due to Provision Stop being skipped. 

I have updated the test runner to be consistent in behaviour for both Provision Stop and Provision Discard, so that the environment is properly stopped and discarded for non shared environment runs."

## Steps to reproduce
1. Run a Galasa test (either locally or in ecosystem)
2. Download run log 
3. Search for "provision"
4. You should see that provision discard starts after the test passes WITHOUT running provision stop at all. This will pass in some cases, but there are situations where a resource cannot be discarded without first stopping it, in which case the test will pass but the environment will then time out before giving test results.

## Expected behavior
Detailed above. Merging the PR should fix the issue

## Additional context
None

**Comment by eamansour** [comment]
Fixed in https://github.com/galasa-dev/framework/pull/498
