### ISSUE TITLE
zOS TSO Command Manager and zOS UNIX Command Manager

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#173]
Add the TSO and UNIX command managers to the list of managers:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
zOS TSO Command Manager 
Beta
Provides the default implementation of the z/OS TSO Command Manager using ssh. Can only be used via the z/OS TSO Command Manager interface.
link - zos-tso-command-ssh-manager
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
zOS UNIX Command Manager 
Beta
Provides the default implementation of the z/OS UNIX Command Manager using ssh. Can only be used via the z/OS UNIX Command Manager interface.
link - zos-unix-command-ssh-manager
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by CaroMac** [comment]
have added these managers into the website
