### ISSUE TITLE
Web UI does not show "experimental" text in header banner

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1734]
# Story
As a galasa web UI user, I don't want to see 'experimental' in the header, as it makes me less confident of using Galasa.

# Background
We don't need the experimental marker now, as it's been working fine for 2-3 releases.

# Tasks
- [x] Remove the `(Experimental)` text from the UI panel.
- [x] Test
- [x] Re-deploy

**Comment by eamansour** [comment]
Done in https://github.com/galasa-dev/webui/pull/24
