### ISSUE TITLE
CECIManager expects associated terminal to have issued the ten CECI

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#174]
```
ceciTerminal.waitForKeyboard();
ceciTerminal.type("logon applid(CICS01)");
ceciTerminal.enter();
ceciTerminal.waitForTextInField("This is the CICS MRO Terminal Owing Region");
ceciTerminal.clear();
ceciTerminal.waitForKeyboard();
ceci.defineVariableText(ceciTerminal, variableName, variableContent);
```

The last line throws a CECIException `dev.galasa.cicsts.ceci.CECIException: Cannot identify terminal as CECI session`. 

Adding a line to enter the CECI transaction in the terminal fixes this problem.  Not sure if this is the expected behaviour or not, but it is not documented to say that the user should enter the txn, it would also be an easy thing for us to fix

**Comment by DavidXRoberts** [comment]
This is intentional. The basic design in #3 says "The tester will need to obtain a zOS3270 Terminal, signon onto the target CICS region and start the CECI transaction."

Also Javadoc-ed in the ICECI methods

**Comment by hobbit1983** [comment]
Yes I see that now that it's pointed out.  Isn't it simpler to say that the manager expects to be at a logged on, blank CICS screen, then the manager can issue the CECI command?

**Comment by Michael-Baylis** [comment]
I ummed and ahhhed about this for a while.  But decided that the CECI manager needs to be handed a terminal in a known state.   the only known state is the initial CECI screen.   A blank screen can be anything.
When we get the CICS Manager up and running, you will be able to initiate a CECI session direct from the ICICS, the CICS Manager can then do the work as it will know it is in the correct blank screen and also recognise failures,  like not authorised to start the CECI transaction etc.

**Comment by hobbit1983** [comment]
OK fair point - will close
