### ISSUE TITLE
Correct typo in Maven testcatalog plugin.

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1755]
The Galasa Maven testcatalog plug-in has a typo in it that is reflected in two other repos. I think this should probably be corrected as it's confusing - I went to correct the typo in the automation repo in the pr-integratedtests pipeline and the branch-integratedtests pipeline then realised the typo is in the plug-in itself so is actually referring to something. If I corrected the typo, I'd be removing the parameter that the plugin needs.

It says 'testcatatlog' instead of 'testcatalog'.

1. In the Maven repository
2. In the automation repsitory in pr-integratedtests and branch-integratedtests 
3. In the integratedtests repo in the pom.xml 

![Image](https://github.com/galasa-dev/projectmanagement/assets/65225359/b3053528-7243-4179-885e-8d827afae12a)

- [x] Create a way for the both the correct and misspelled plugin to be accepted
- [x] Change usages to accept correct spelling
    - [x] automation repo
    - [x] integratedtests repo

**Comment by jadecarino** [comment]
@techcobweb Hi Mike, I know we have lots of other things to be doing but thought this is a quick fix and should probably be corrected while someone is working in the Maven plug-in. Would this have repercussions though on anyone using it, would we break them by correcting this typo?

**Comment by techcobweb** [comment]
@jadecarino Maybe. The kindest thing to do is change the java code to accept either, favouring the well-spelled variant, and change all our usages to the new spelling.
