### ISSUE TITLE
CECIManager in a loop of death

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#176]
The following test method can cause CECIManager to fall into a loop
```
@Test
    public void basicCommandExecution()throws CECIException{
        String userVariable = "USERID";
        String command = "ASSIGN USERID(&" + userVariable + ")";

        ICECIResponse response = ceci.issueCommand(ceciTerminal,command);
        assertThat(response.getEIBRESP()).isZero();
        String user = ceci.retrieveVariableText(ceciTerminal, userVariable);
        logger.info("Retrieved user was: " + user);
    }
```

**Comment by DavidXRoberts** [comment]
It's not really in a loop of death. I think you'll find that if you let the test continue, it will complete. When the issueCommand method has issued the command, it grabs the response (RESP and RESP2) and then tabs through the fields, expands them and saves the value. ASSIGN has 110 fields to expand, so takes a looooooonnnnnggggg time to process. I've added a now method:
`issueCommand(ITerminal ceciTerminal, String command, boolean parseOutput)`
Ran a quick test for ASSIGN and reduces the time from nearly 2 mins to 6 seconds!
PR building now

**Comment by hobbit1983** [comment]
awesome - re-running tests

**Comment by hobbit1983** [comment]
setting parseOutput to false is speedy!

**Comment by hobbit1983** [comment]
So speedy - perhaps it should be the default.
