### ISSUE TITLE
Error when using Gherkin support with Examples

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1788]
## Describe the bug
When I use the EXAMPLES keyword in a gherkin test file I receive a stack trace error

## Steps to reproduce
1. Run the following gherkin feature file:
```
Feature: GherkinLog
  Scenario: Log Example Statement
    
    THEN Write to log "This is a log statement"

  Scenario: Log Statement Test
    
    THEN Write to log "This is a second scenario"
    

Examples:
|Item|Value|
|password|data|
|password2|data2|
```
You will get an error that contains:
`dev.galasa.framework.TestRunException: Manager already registered for statement: Write to log "This is a second scenario"`
Removing the Examples section removes the error

## Expected behavior
Test should run to completion

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.

**Comment by techcobweb** [comment]
PR https://github.com/galasa-dev/framework/pull/515 fixes this issue.

**Comment by techcobweb** [comment]
@hobbit1983 The PR hasn't been merged yet.
