### ISSUE TITLE
Update the CICS TS &  z/OS Manager CPS properties

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1791]
## Story
As a Galasa user, I want to know how to configure the CICS TS Manager & z/OS Manager in the CPS, so that I can provision CICS Regions for my Galasa tests.

## Background
I have seen several user questions in the galasa-users channel where users are struggling to get a CICS Region provisioned for their tests. Most often, it's because they haven't got sufficient properties in the CPS. I had a look and there is minimal doc about the CICSTS Manager properties required.

As a minimum, to get a CICS Region provisioned for your test, you need these 2 CPS properties in the `cicsts` namespace:
```
cicsts.provision.type=dse
cicsts.dse.tag.<TAG>.applid=<APPLID>
```

**Update:**
You also need these CPS properties in the `zos` namespace as a minimum, even if you haven't referenced a `@ZosImage` in your Galasa test (as it's the z/OS image the CICS Region is on...). You might need more z/OS related CPS properties depending on your test.
```
zos.dse.tag.PRIMARY.imageid=<IMAGEID>                             OR      zos.cluster.DEFAULT.images=<IMAGEID>
zos.image.<IMAGEID>.ipv4.hostname=<IP ADDRESS>
zos.image.<IMAGEID>.credentials=<CREDENTIALID>
```

I started with 0 CPS properties and built it up until I had these 5 properties, 2x cicsts and 3x zos, and that's the minimum that was needed to connect to the CICS Region. 

I'm not entirely sure it's the best idea to reference these specific z/OS properties from the CICS TS Manager doc though, as this isn't the only way to set the z/OS properties, it can be done many ways. So I wonder if just telling users the 2 essential CICS properties and then adding "Some z/OS properties might also be required to connect to the z/OS image which your CICS Region sits on (link to z/OS Manager doc)".

The z/OS Manager doc is however missing `zos.image.<IMAGEID>.ipv4.hostname=<IP ADDRESS>` and `zos.image.<IMAGEID>.credentials=<CREDENTIALID>`, so perhaps we can add these in another story.

## Tasks
- [x] Add a CPS property for `cicsts.provision.type=dse` into the documentation for CICS TS Manager as a minimum and explain this must be used if you are using the `cicsts.dse.tag.<TAG>.applid=<APPLID>` prop.
- [x] Reference z/OS Manager and state some z/OS properties might be needed
- ~Potentially reference that you will also need these `zos` properties too and link to the z/OS Manager doc~ Create new story for z/OS properties?

**Comment by CaroMac** [comment]
published
