### ISSUE TITLE
OMP Summer Mentorship Application 2024 - Github action build process

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/projectmanagement#1802]
# Background
The summer mentorship program allows people to apply to work on specific short-term projects.
The Galasa project can submit an idea to attract applications, and one person may be accepted.

They become a galasa contributor, and work with the team over the summer (2-3 months).

The application process requires some information to be sent. See below.

# Application Q&A

## Program Description
Galasa is an open-source Open Mainframe Project and Linux foundation incubator project. It is a ground-breaking tool used in test automation, to orchestrate the running of test cases with enterprise-level capabilities.

Galasa build infrastructure currently has a build process which is less than ideal. We are looking for someone interested in CI/CD pipeline technology to help create a brand new set of build pipelines using Github actions on public Github.

The work will be open source, visible to the world, will greatly enhance the productivity of the Galasa team, and make it far easier for others to contribute to the project in future.

Galasa is written in Go and Java, uses Docker, Gradle and Maven, and runs on laptops or kubernetes clusters, but no experiences with these technologies is necessary.

## Unmet Need – Problem to be Addressed
The Galasa build process currently uses Tekton, runs on IBM-internal systems, and needs to be more open. Build results are hard for non-IBM staff to see due to access of those build systems.

Galasa code is spread over 12+ github projects in the galasa-dev github organisation, so we need a new build pipeline constructed using Github Actions for each of these, capable of handling main-branch and feature-branch/pull-request builds.

## Proposed Deliverables
A set of github action files checked-in to the public Galasa projects, which compile and package galasa build artifacts using the github actions technology.

## Technologies
This project will use the following technologies:
- Github Actions
- Makefiles
- Gradle
- Maven
- Docker

## Anticipated Skills Required
Before applying, the mentee should be familiar with:
- Basic Github actions (will be improved greatly by working on this project)
- Basic Docker concepts (will be improved greatly by working on this project)

Next action: @jadecarino to review the mentor guide and Louisa to create a draft submission.

**Comment by louisa-seers** [comment]
Mentorship Program Title

Program Description:  Please provide a brief, detailed program description to be displayed to applicants.

Unmet Need – Problem to be Addressed:  Briefly describe the unmet need (or problem) and its significance.  (One or two sentences)

Proposed Deliverables:  Please describe the specific item(s) that would represent the successful completion of the program. (One or two sentences)

Technologies: List any technologies that will be utilized during the program, e.g. Java, COBOL, SQ. (at least one is required)

Anticipated Skills Required: List any skills the mentee should have before applying. (at least one is required)

**Comment by techcobweb** [comment]
@louisa-seers I've fleshed out the text in the main part of this issue.
What's the next step please ?

**Comment by louisa-seers** [comment]
I can submit it to the OMP, thank you Mike, I'll send anything else through if I get it!

**Comment by louisa-seers** [comment]
Actually, @jadecarino - looking at the form you should probably apply here: [link](https://urldefense.proofpoint.com/v2/url?u=https-3A__forms.gle_qDHD4ScPwFTsvqyAA&d=DwMFaQ&c=BSDicqBQBDjDI9RkVyTcHQ&r=ANUcOC2bwkS5TY4jYDb0rFdRg-3oa2mneFa0iIefQl8&m=6HZ1p9klMpF_j778BRBhmxeb584rh4w6NEKX7V17wOsurVjOnKIN7hfV60yBMLPv&s=1ogx406SZdKMniwqMw_dHHRdNQMdXQL1dBrfrxZUMpA&e=)

**Comment by jadecarino** [comment]
Mentorship submission form submitted on 22nd March. Mentor profile to be created on LFX.
