### ISSUE TITLE
Upper cap on number of WebDrivers in an ecosystem

### ISSUE THREAD

**Issue by rsomers1998** [galasa-dev/projectmanagement#181]
Similar to Docker Manager for Selenium Manager max slots

**Comment by Michael-Baylis** [comment]
@rsomers1998 Are you saying you want to restrict the max number of selenium tests that can run on a single desktop?   The title is unclear

**Comment by rsomers1998** [comment]
@Michael-Baylis I want to limit the number of active WebDrivers in an ecosystem. Set a maximum in the same way docker does with max slots.

**Comment by Michael-Baylis** [comment]
Not required as an Engine will need to be configured to run Selenium tests as they have to run on a server with a desktop.   So the limiting factor is the number of engines.   So this isn't required.
