### ISSUE TITLE
Upgrade Java to v17

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1823]
# Story
As a galasa test developer, I want to use a supported JVM level, and some features of Java (which were added after v11 was shipped) in my Galasa tests.

# Background
- The version of Java galasa supports is currently v11.
- According to https://www.ibm.com/support/pages/semeru-runtimes-support#lifecycle the JVM is out of service Oct 2024.
- We should keep things current by moving to v21 (skipping v17)

(These tasks are for creating pull requests, not merging, so these may not be done)
Maven:
- [x] integratedtests
- [x] cli/pkg/embedded/templates/projectCreate/parent-project/pom.xml
- [x] maven
- [x] simplatform
- [x] wrapping
- [x] Buildutils
- [x] Framework

Gradle:
 - [x] Framework
 - [x] managers
 - [x] obr
 - [x] webui
 - [x] extensions
 - [x] integratedtests

Other:
- [x] Automation
 - Update Dockerfile From references:
   -  [x] webapp (requires tomcat 11, jdk 21)
   - [x] openapi
   - [x] openjdk11-ibm
   - [x] openjdk11-ibm-gradle
   - [x] swagger
   - [x] simplatform-amd64
 - Update tekton pipelines
   - [x] automation
   - [x] cli
   - [x] codecoverage
   - [x] obr-generic
   - [x] run-tests? (uses `local.CoreLocalJava11Ubuntu`)
   - [x] simplatform (pr only)
 - Update tekton tasks
   - [x] gradle-build
   - [x] maven-build

**Comment by Wyvinar** [comment]
How I upgraded Gradle locally:
used sdkman to install Gradle 8.8 (`sdk install gradle 8.8`)
used the `sdk home gradle 8.8` command to find it's home
added [gradle-home]/bin to path (replacing the v6 path)

**Comment by techcobweb** [comment]
@KirbyKatcher Wondering if the objects that are built will still run on java 11. They need to...
If you find any reason they won't then could you pls come talk about it ?
I imagine the binary class files are targeting Java 1.8, but I'm wondering what we actually test...

Wondering if the ecosystem needs to target a different docker image to run in the container for tests, and whether the helm installer admin gets to say which version of Java they are running ?

It might be better if a cps property held the java version/docker image name which gets launched ?
Then tests could override it perhaps ? We probably need more discussion on this also.

For local build processes, I guess we don't have to do anything except pre-req Java 17, but for the build process, what other tests do we need to put in place to test Java 11 and 17 ?

Suggestions welcome @jadecarino @eamansour
