### ISSUE TITLE
Explain why ~/.galasa/overrides.properties needs editing

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#185]
In the docs in galasa.dev - on the _Getting started -> Installing the Galasa Eclipse plug-in_ in the section _Configuring Eclipse for Galasa_
A user (even me) can install the _Eclipse plugin_ by following the instructions but it is significant that the _Setup Galasa Workspace_  creates an 'empty' (even though it's not empty) overrides.properties file and then the next step is to populate it with some given content (a superset of what's in the 'empty' version)

My first question to Will was, "why not just pre-populate it with the correct content?".
Will's response, "To show that this is what is binding the test to the simbank instance".
In which case, the docs should explain the reasoning otherwise no one will know!

**Comment by Michael-Baylis** [comment]
The population is for running the SimBank tests only.   Normally usage will have an empty overrides.properties as the correct configuration will be in the Ecosystem CPS

**Comment by Michael-Baylis** [comment]
and as Will says,  part of the demonstration on how the binding works

**Comment by lubelg** [comment]
Thanks Mike, I understand that but if there's a manual step in the docs and Will says it's to demonstrate the necessary binding, then we must explain that and not leave it to inference.

**Comment by CaroMac** [comment]
Will update docs with further explanation
