### ISSUE TITLE
Galasactl projects function for listing Galasa tests in a package

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1857]
A common CI/CD infrastructure pattern is to build packages and run tests if they have received changes in a PR. A pipeline can be triggered by a list of files changed in a PR, and the pipeline would need to convert this into a list of tests that need to be run to verify that they work. 

Galasa packages can contain several Java files, some of which are tests that contain the @Test annotation, and some of which are utility classes that are not tests. However, there is currently no way to list all tests in a given package other than creating a custom utility to search for the @Test annotation in each file. It would be a useful for infrastructure if Galasactl had a way of listing only the tests in a package, preferrably in the class format needed to be input into a Galasactl runs prepare command - possibly this could be achieved using the test catalog?

I was imagining this being a feature that could be included in the "galasactl projects" command.

**Comment by techcobweb** [comment]
Surely if every bundle has a test catalog inside it, then we wouldn't need this ? as there would be something automation could scan/use ?
