### ISSUE TITLE
Provide vscode support in addition to eclipse 

### ISSUE THREAD

**Issue by rradclif** [galasa-dev/projectmanagement#187]
With the advent of the Z Open Editor for vscode and it's ability to run on Che developers may choose to use the vscode solution instead of an eclipse base IDE.  With Galasa support in vscode developers/testers could stay in the one environment they want to use.   This would also support if testers don't normally have an IDE but use a browser based solution, Che with the vscode support would be a good alternative.

**Comment by Michael-Baylis** [comment]
Introducing support for VScode was due for Milestone 6, we are currently on Milestone 3.   However, I have noticed more of the demos are being run from VSCode, so maybe we need to bring this forward.  Will discuss at the next team meeting.

**Comment by Michael-Baylis** [comment]
Initial support for VSCode support will be provided in 0.8.0.
Possible support may be:-
    A Launcher
    Submit tests to ecosystem
    Run editor view of local and automation tests.
Priority and what can be acheived in 0.8.0 will be discussed this Thursday
