### ISSUE TITLE
Running Galasa tests using Ecosystem cps.properties within Visual Studio 

### ISSUE THREAD

**Issue by ayushikumari3** [galasa-dev/projectmanagement#1874]
While running Galasa tests within Visual Studio using Ecosystem cps.properties as below-

galasactl runs prepare --stream main --class com.ibm.cics.test.
applicationservices.asyncservice.async/com.ibm.cics.test.applicationservices.asyncservice.async.TestFetchVariationExampl
e --portfolio output.yaml

We are getting error while retrieving Stream name like this- 
Error: GAL1029E: Stream 'main' is not found in the ecosystem. There are no streams set up. Ask your Galasa system administrator to add a new stream with the desired name.

It's likely that galasactl used the old framework.test.streams property to detect if streams are set up.

**Comment by techcobweb** [comment]
Version 0.33.0 stopped using the old `framework.test.streams` property. Instead it looks at all the CPS properties for `framework.test.stream.xxxx.repo`... where one `.repo` property should exist for every stream definition.

**Comment by ayushikumari3** [comment]
Yes using this , I am able to run Galasa test using Ecosystem cps.properties from Visual Studio

**Comment by CaroMac** [comment]
Doc updates regarding this are in progress - will publish as soon as complete.
