### ISSUE TITLE
Cache/Pull all CPS properties at the start of a run if using remote CPS

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1889]
# Story
As a galasa user running a local test, but using configuration on the galasa shared service, I want my local galasa to cache CPS properties, so that the overall test runs faster.

# Background

Currently when using a remote CPS properties store in an ecosystem it looks like I'm seeing 
```INFO  d.g.c.r.RestCPS - galasacps: over rest```

each time a CPS property needs to be retrieved. I've noticed since changing to remote CPS the test takes a lot longer to run, I think this might be the result of it doing many individual REST calls to the API server. Would it be better to consolidate all of this into a single call where it retrieves the entire CPS properties from the ecosystem at the start of the test in a single REST call and then uses that for the runtime of the test? This might speed up the test run a lot

# Solution
The 0.36.0 code has been enhanced to add optional caching. 

A new CPS property has been introduced:
```
# framework.cps.rest.cache.is.enabled
# The CPS over REST feature allows a local client to draw CPS properties from a remote Galasa service.
# It has a local cache of properties which can be turned on using the `framework.cps.rest.cache.is.enabled` property.
# Values:
# - `true` - enables caching of CPS properties on the client-side, with an agressive cache-priming which loads all
#    CPS properties into the cache at the start.
# - `false` - the caching will be disabled.
# Default value if missing from the CPS: `false`
```

So if it's enabled, there are two calls to the REST api
- One to see if caching is enabled.
- One to get all the CPS properties in bulk

So the implementation is essentially on a feature toggle, and we can see what difference it makes to the performance.

# Tasks remaining
- [x] implementation
- [x] docs in the generated `cps.properties` and `overrides.properties` when you do a `galasactl local init`
- [ ] external documentation

**Comment by techcobweb** [comment]
Yes it would speed tests up. Get them all and cache the values would be fine in theory.

Do you have any rough metrics between using REST vs the file system ?
How painful is it ?

The trouble would be when the CPS gets to hold a large number of properties.
There must be a balancing point when getting them individually is quicker.
No idea just yet what that balancing point might be however.

Of course, getting anything in the secure namespace (secrets) won't work regardless.

**Comment by techcobweb** [comment]
@jt-nti @CaroMac There are external documentation impacts as a result of this story. Probably in the area where we describe a common CPS on the server-side.
