### ISSUE TITLE
OnFailure annotation required to implemented

### ISSUE THREAD

**Issue by ayushikumari3** [galasa-dev/projectmanagement#1900]
This annotation will cause the method to be called whenever a 
 * @Test, @Initialise, @BeforeClass, @Before, @After or @AfterClass method has failed.
 * It will NOT be called if another @OnFailure method fails.

**Comment by techcobweb** [comment]
I think the answer to this is to write your own manager, which already has the ability to hook into lifecycle events.

Writing a manager isn't very hard, it's like a helper class but more aware of what the test using it is up to, and what the environment is doing.

**Comment by ayushikumari3** [comment]
Hi @techcobweb ,

Below are the few points which I think is important to consider as the @OnFailure annotation in the context of the Galasa framework is used to define actions that should be taken when a test fails.

Reasons for Implementing @OnFailure:-
1. Automated Failure Handling:
The @OnFailure annotation allows developers to specify custom logic that should be executed when a [@test](https://github.com/test), [@initialise](https://github.com/initialise), @BeforeClass, [@before](https://github.com/before), [@after](https://github.com/after) or [@afterclass](https://github.com/afterclass) method fails. This can include actions such as capturing logs, diagnostic information , or performing cleanup tasks.
2. Consistent Behavior:
By implementing @OnFailure, the framework ensures that all tests adhere to a consistent failure-handling strategy. This consistency helps in maintaining a standardized approach to dealing with test failures .
3. Enhanced Debugging and Reporting:
When a test fails, having predefined actions to gather additional information can greatly aid in debugging and diagnosing the issue.

Why Implementation is required by the Galasa Team:-
1. Framework Integration:
The Galasa team has a deep understanding of the framework’s architecture and can integrate the @OnFailure annotation seamlessly.
2. Extensibility:
The team can design the @OnFailure feature in a way that allows for easy extensibility and customization. Users can add their custom failure-handling logic as needed without compromising the framework’s integrity.

**Comment by Mark-J-Lawrence** [comment]
The Galasa AbstractManager provides the overridable function `performFailureAnalysis()`, which runs directly before the test class ends.
If this would suffice, we simply would need to create a manager that implements this function, and also looks for `@OnFailure` annotated methods, which it would run one after the other at the correct point in the test run lifecycle, & if one fails, the manager then handles the issue.

If this would suffice, then this issue can be closed.

**Comment by Mark-J-Lawrence** [comment]
Closing this as we currently plan to implement this internally
