### ISSUE TITLE
Stop a test running against a down-level version of the target system under test

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1909]
## Story
As a Galasa test developer, I want to be able to skip a Galasa test method from running if CPS properties do not match expected conditions, so that I only receive failing test results for valid test scenarios.

## Background
It is really important that we can automatically exempt certain tests from running if CPS properties do not match expected values. I think a good implementation of this would be a "conditions" annotation that is capable of performing comparisons, e.g.: 

``` 
@conditions({
    ProductVersion("cicsts.default.version").greaterThan("5.6.0"),
    CpsProperty("cicsts.provision.type").equals("sem")
})
```

This allows us to run tests in bulk without needing to worry that changes to the CPS properties will affect test results in a way that does not give us accurate information about the status of the feature under test.

**Comment by techcobweb** [comment]
I don't think you can easily do what you suggest.
You can't pass java logic in as a data field inside an annotation.

I believe `String`, `int`, `Integer` and `String[]` are the only types you are allowed to use as data passed through to the annotation. Pls correct if I'm wrong.

The data you passed in your example looks like java code, not a string, and we don't want to write a huge parser for this stuff.

Perhaps something like this?
```
@RunOnlyIfTrue(my.package.MyClass#checkConditions)
```
and in the `my.package.MyClass` we have this:
```
class MyClass {
  boolean checkConditions(IConfigurationPropertyStore cps) throws Exception {
  ...
}
```

or something which supplies the logic

**Comment by techcobweb** [comment]
After much discussion, we concluded that the CICS manager was the only place this should fit. In that we want conditions to be evaluated even before the test is scheduled.

@Tom-Slattery agreed we should close this requirement for now, and re-open if we later decide that it should be a galasa responsibility.
