### ISSUE TITLE
Save the overrides for a test run and make accessible

### ISSUE THREAD

**Issue by adamcoulthard** [galasa-dev/projectmanagement#1919]
## Story
As an ecosystem administrator, I want to be able to see what overrides a user passed to a test run, so that I can understand what was different to the default incase of failures.

## Background
From the REST API I would like to be able to obtain what overrides were passed to the test.  At the moment it's possible to see all the cps properties that were used for the test (note that it just lists everything).  It would be good if we could also save what the overrides were as well.

## Current behaviour
`cps_record.properties` file is deposited as an artifact of each run.
It contains the list of properties that the test run tried to get, and the value returned and used.
eg:
```
framework.continue.on.test.failure=*** MISSING ***
...
framework.request.prefix.maximum=*** MISSING ***
framework.request.type.LOCAL.prefix=L
test.prop.1=1234
framework.resultarchive.store.include.default.local=*** MISSING ***
framework.run.testbundleclass=dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee
```

The `*** MISSING ***` value indicates that the value was asked for, but it hasn't been set into the CPS.

Problems with this:
- You can't see which values were from the base CPS settings, or which ones were from overrides.
- You can't see what the override values were used
- You can't see what the override values were not used
- You can't see what base cps property values were used
- You can't see what the total list of overrides were that were passed into the test
- You can't see the values of the base cps before they were over-ridden

## Proposed solution

```
# A list of properties used by the test run, and where the values came from.
framework.request.prefix.maximum=*** MISSING ***
framework.request.prefix.maximum._source=missing
framework.request.type.LOCAL.prefix=L
framework.request.type.LOCAL.prefix._source=cps
test.prop.1=1234
test.prop.1_source=overrides
framework.resultarchive.store.include.default.local=*** MISSING ***
framework.resultarchive.store.include.default.local._source=missing
framework.run.testbundleclass=dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee
framework.run.testbundleclass._source=overrides
```

**Comment by adamcoulthard** [comment]
@techcobweb just been thinking about this more and this would be really useful for requiring tests as well.  At the moment a piece of automation could queue the test up and if I want to rerun it manually I don't know what options were used.  I could pass in the complete cps_record.properties that is returned but that seems abit overkill.

**Comment by techcobweb** [comment]
Implemented. Works fine on our prod system.
@adamcoulthard When you get version 0.37.0 it should be in there.
