### ISSUE TITLE
Account Credit Testcase failing

### ISSUE THREAD

**Issue by Shalini174** [galasa-dev/projectmanagement#192]
Hi ,

I tried running the testcase BasicAccountCreditTest and it is failing with error:
Caused by: dev.galasa.simbank.manager.SimBankManagerException: Missing credentials for id SIMBANK for SimBank instance SIMBANK
	at dev.galasa.simbank.manager.internal.SimBankImpl.getDSE(SimBankImpl.java:106)

I executed all the steps mentioned in the document and haven't modified the code. 
Also, since i couldn't find a forum to post my issue..i am posting my query here.

**Comment by cxharris** [comment]
Please could you tell us what version of Eclipse you are using - choose _Help > About Eclipse IDE_ - the dialog lists the version. Could you also confirm that your `credentials.properties` file contains exactly:

`secure.credentials.SIMBANK.username=IBMUSER 
secure.credentials.SIMBANK.password=SYS1`

**Comment by hobbit1983** [comment]
those credentials should be split over two lines
```
secure.credentials.SIMBANK.username=IBMUSER 
secure.credentials.SIMBANK.password=SYS1
```

**Comment by Shalini174** [comment]
@cxharris : Sorry for the trouble. Password was missing in the credentials.properties file. The test case is now working fine.

**Comment by cxharris** [comment]
@Shalini174 - good to hear! Thanks for letting us know.
