### ISSUE TITLE
Create sample Java/Gradle project to test maven artefact publishing

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1926]
1. Create a sample Java/Gradle project that just does a Hello World starting with the version `0.1.0-dev`
2. Create a basic workflow that attempts to publish this project to the GitHub Packages Maven Registry
3. Test that this can be done multiple times if the project version is suffixed with `-dev`
4. Create a second sample project in the same repository that has a dependency on the first project, but the version specified is `0.1.0` as it doesnt know the suffix
5. Test that the second project can find the first project as a dependency even without the suffix

**Comment by techcobweb** [comment]
there are Dhruv's findings from creating the sample project - https://github.com/jaydee029/TestProject

See the readme in that project.
