### ISSUE TITLE
Buildutils tool should list/set version suffixes

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1932]
# Story
As a galasa build process, I want to be able to strip off all the `-SNAPSHOT` suffixes from all our source code, prior to building a release branch. I also want to be able to add them or change them at will to anything.

# Background
The Github maven builds insist that `-SNAPSHOT` is used for main builds, else the builds would not be publishable to the GH repository.

All our source will have `-SNAPSHOT` included in the build.gradle files.

We need the build tool to change the suffix at will.

Syntax:
```
galasabld versioning list --sourcefolderpath /Users/mcobbett/my/code/source/folder
>
my.bundle.name: 0.36.0-SNAPSHOT
my.bundle2.name: 0.23.0-SNAPSHOT
```

and

```
galasabld versioning set --sourcefolderpath /Users/mcobbett/my/code/source/folder --suffix "-SNAPSHOT"
```

Exit codes from the tool:
- 1 - Failed.
- 0 - Passed.

During the release process, this suffix will be removed, allowing us to publish to maven central.

No external docs changes are needed for this story.

# Tasks
- [x] Build util to list the current versions for all things it finds in a source tree.
- [x] Build util to change all the suffixes in the current versions.

**Comment by jt-nti** [comment]
@techcobweb if it's any help, I think this is how we handled stripping the `-SNAPSHOT` suffix to publish fabric-gateway releases...

https://github.com/hyperledger/fabric-gateway/blob/main/.github/scripts/maven_publish_release.sh#L10C41-L10C53
