### ISSUE TITLE
Log when an artefact isn't found instead of throwing an exception

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1938]
## Describe the bug
During tests, we look for artefacts firstly in our development Maven repos then we go to Maven Central. For artefacts that aren't dev.galasa, they are of course not in the development Maven repos, but they are in Maven Central. However, when it looks in the development Maven repos, it throws an exception instead of just logging that the artefact wasn't found there. This clutters the run.log and fills it with red, and can be misleading what the actual cause of the test failure is.

## Steps to reproduce
1. Run any test in the ecosystem with galasactl
2. Look in the inner run.log for the IVT (`<runname>/artifacts/ecosystem/run/<innerrunname>/run.log`)
3. Scroll down to where it starts trying to fetch artifacts (Search `30/07/2024 06:07:10.539 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact`)

## Expected behavior
If an artefact is first not found in the development Maven repos, it should just log this, then move on to look in Maven Central. If its not found in any provided Maven registry, then it should through an exception.

## Additional context
As shown in the screenshot it first looks for the artefact in development.galasa.dev, then when it can't be found it throws a huge exception. Then it checks in Maven Central, and finds it successfully. 
![Image](https://github.com/user-attachments/assets/193bea96-b61b-4bf1-9457-8af2c92df5a6)

**Comment by techcobweb** [comment]
https://github.com/galasa-dev/framework/pull/608Think I have a fix for this here :

**Comment by techcobweb** [comment]
jade can't see the exceptions now this fix has been applied.
