### ISSUE TITLE
Ability to create a basic Liberty server in a CICS JVM server

### ISSUE THREAD

**Issue by ayushikumari3** [galasa-dev/projectmanagement#1939]
The implementation for the buildWlpServerBasic method in the JVMServer class within Galasa is needed. This method is tasked with executing a series of commands and then generating a server.xml file that incorporates two specific features, similar to the functionality found in JAT.

**Comment by techcobweb** [comment]
This functionality could be added to galasa-managers-parent/galasa-managers-cicsts-parent/dev.galasa.cicsts.resource.manager/src/main/java/dev/galasa/cicsts/resource/internal/JvmserverImpl.java ?

Currently the Galasa team are busy with Java17 support and a new/easier to use build process on Github actions. Would it be possible to get some help implementing this one ?

Contributions to the open source project are always very welcome.

**Comment by Mark-J-Lawrence** [comment]
I have duplicated this issue internally. The CICS team will work to resolve this themselves if it is an issue and we will contribute the fix back.

You can close this issue if you're happy with this.

**Comment by ayushikumari3** [comment]
During my discussion with Alex, we agreed to implement the buildWlpServerBasic method directly within the Galasa test class methods. 
Hence, closing the issue.
