### ISSUE TITLE
JAT Conversion: Write Analytics programs for reporting on JAT usage for CICS TS Testing

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#194]
Write programs to analyse the source/byte code of ALL the tests in the CICS TS JAT test catalog.   We will need the following information:-

What Classes, methods, parameters, annotations, attributes are used by what test classes/projects for packages com.ibm.cics.jatp*, com.ibm.jat*, com.ibm.cics.jatp.helper*

The information needs to be presented both from a Manager standpoint and a Test Project standpoint, from managers, what test classes use these managers, classes, methods
and
from test project, what managers, methods, classes etc are used.
With the appropriate counts, so we can judge the priority.

**Comment by hobbit1983** [comment]
Can now pull out from the test classes:
All the annotations 
All the declared managers/helper
   The methods that are used against that manager/helper
All of which are sorted by the amount of use,

Finally we can see how many managers each test class uses (manager density)
