### ISSUE TITLE
Getting call to Galasa failing with HTTP Error 404 Not Found

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#195]
I'm getting "Error with call to Galasa WAS HTTP/1.1 404 Not Found" when running a Galasa test from the Jenkins Galasa plugin. The problem was caused by using a bootstrap URI in the plugin configuration that ended in "/bootstrap" and removing that fixed the issue.

**Comment by hobbit1983** [comment]
To clarify.  What made you add the /bootstrap on the end?  Would you like the plugin to be /bootstrap agnostic? so if it is added we trim it off?

**Comment by Michael-Baylis** [comment]
The URI should the URI of the the bootstrap service,  this is reflected across the board in the Eclipse plugin etc.   It is the place to go to to find all the other services.
So the default the other services would be to trim /bootstrap off,  then append the default suffix.
If it is necessary the URI of the other services, testcatalog for example can be provided by the bootstrap properties

**Comment by Michael-Baylis** [comment]
So for the cics production galasa ecosystem, the bootstrap can be found at:-
http://cicsk8sm.hursley.ibm.com:31410/bootstrap
So that is the URI that must be provided to gain access to anything else in the framework.

**Comment by hobbit1983** [comment]
soooo .... what can (if anything) be changed to make this better?

**Comment by Michael-Baylis** [comment]
The plugin needs to be changes to use the bootstrap URI as is.  A check should be made, for the moment, that the URI does end with /bootstrap.

Two other URIs are used,   /auth (though not working) and /runs.

Eventually the bootstrap properties could provide the full uri to those microservices.   But for the moment,  assume the default is:-
/bootstrap/../auth
/bootstrap/../runs

eg if the bootstrap is at http://cicsk8sm.hursley.ibm.com:31410/bootstrap
runs will be at http://cicsk8sm.hursley.ibm.com:31410/runs
auth will be at http://cicsk8sm.hursley.ibm.com:31410/auth

Note, for auth,  there will be a bootstrap property URI in milestone 3 to indicate authentication is required.

All in all,  the plugin needs to generate the FULL uris for each of the microservices as soon as the bootstrap properties are retrieved.  Bear in mind, they may not be on the same host or port, but they will, eventually, have the same JWT, auth wont, runs and testcatalog will.

**Comment by Tom-Slattery** [comment]
The bootstrap URI was provided to me to use in the Eclipse preferences of the Galasa plugin. I copied that URI to the Jenkins Galasa plugin and that didn't work. I think the Eclipse preferences must be trimming "/bootstrap" as the tests were running fine from there. I think it would make the most sense for either both of these configurations to trim "/bootstrap" or for both of them to allow it fail with error 404 for consistency.

**Comment by hobbit1983** [comment]
Right got it - sorry and thanks for the explanations

**Comment by hobbit1983** [comment]
OK I have a fix for this on a private branch - once 0.8.0-SNAPSHOT is available I will merge it

**Comment by hobbit1983** [comment]
fix built and with Tom for testing

**Comment by hobbit1983** [comment]
closing as the plugin will soon be deprecated
