### ISSUE TITLE
Lost test result on EnvFail

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#199]
I ran a Galasa test from the Jenkins Galasa Plugin which failed but did not result in a test failure being reported back to me. @Michael-Baylis could see that the test hit an exception in the Galasa Manager code resulting in EnvFail but the console output to Jenkins showed me the tests being completed with no results:

`The following 1 Galasa test classes have been selected for running
    com.ibm.cics.cip.bank.tests.HBankTestsUsingManager
Test Run Instance = jenkins
Maximum number of concurrent runs is: 1
Galasa Server Poll time is: 5 seconds
Tests schedule endpoint: http://cicsk8sm.hursley.ibm.com:31410/runs/10623b4e-53c0-4e4e-bd8c-0bcf45bd5d9d
Galasa has completed 1 out of 1tests
Tests passed:
Tests failed:
Tests ignored:
Tests lost:
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS`

**Comment by Michael-Baylis** [comment]
Reworked the test runner so envfails fail gracefully.
