### ISSUE TITLE
Always release Gradle plugin

### ISSUE THREAD

**Issue by jt-nti** [galasa-dev/projectmanagement#1999]
## Story

As a Gradle user, I want the Galasa plugin version to match the Galasa version, so that I can be confident that I'm using the correct version.

## Background

The Gradle plugin is only released if there have been changes, which would make sense if the version did not track the Galasa release version at all, however the versions look similar enough to cause confusion.

For example, creating a new project with v0.37.0 of `galasactl` creates `build.gradle` files with v0.36.0 of the `dev.galasa.tests`, `dev.galasa.obr`, `dev.galasa.testcatalog` and `dev.galasa.tests` plugins which is unexpected.

It also complicates things when upgrading the plugins, since there will not always be a matching version. It looks like there can be big gaps in the version numbers.

## Tasks

- [ ]  TBC

**Comment by techcobweb** [comment]
I think this is done in v0.38.0 and onwards.
