### ISSUE TITLE
RELEASE - Test the CECI manager

### ISSUE THREAD

**Issue by pauline-andrews** [galasa-dev/projectmanagement#201]
Perform testing to achieve Release level for the CECI manager.

**Comment by hobbit1983** [comment]
Already written a big IVT for the CECI manager.   However this cannot run yet as a Galasa test unless we have a CICS region to run it on.  To complete this testing, I want to actually run some CICS programs using the CECI manager passing data both as a comarea and a channel.  These tests should get added to the IVT

**Comment by hobbit1983** [comment]
Added some extra tests from the documentation to the IVT
