### ISSUE TITLE
Kafka-clients.jar needs upgrading to 3.8.x or 3.9.x

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2060]
A possible vulnerability in the kafka-client-xxx.jar has been reported, so we need to upgrade it to a version unaffected by this.

Currently Galasa 0.38.0 has kafka-client-3.7.1.jar being used.

It needs to change to 3.8.0, 3.8.1 or 3.9.0.

Presumably 3.9.0 will have a longer shelf-life so that sounds best to me.

Having trouble finding release notes/upgrade details.

Did find this about a possible problem that may hit us: https://stackoverflow.com/questions/78844387/upgrading-apache-kafka-client-to-3-8-0-issue

**Comment by jadecarino** [comment]
Dependency on kafka-clients and kafka-server-common upgraded to 3.9.0 in dev.galasa.wrapping.kafka.clients. Kafka plugin activated and test ran to ensure no wiring issues at runtime.

**Comment by techcobweb** [comment]
This is complete.
