### ISSUE TITLE
Resource allocation via DSS is allocating resources already allocated

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [galasa-dev/projectmanagement#2078]
We've had two issues the past few months:

1. Lots of `dss.zos.run.<run name>.zosport.IMG1.<port number>=active` records being stale/orphaned in the DSS
2. Test runs failing due to allocated ports being already in use

We've now think we've proven that these two issues are now actually related and why.

As we are now testing with a larger number of tests, it seems totally possible that this code could cause run time issues: https://github.com/galasa-dev/galasa/blob/5e5c89e00fe85f89069d45f309eda1036eaeba8f/modules/managers/galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPoolPorts.java#L46-L65

It's totally possible that 2 test runs could enter this code at exactly the same time. Obtain exactly the same list of available ports on L47, pick exactly the same port on L56, then both could try to update the DSS at L59.

Both of these updates will happen successfully, but it won't be correct, and this is a bug. As an example, a first test run will go in and update the DSS with:

```
zosport.IMG1.1234=U9999
run.U9999.zosport.IMG1.1234=active
```

the 2nd test run will go in and update with:

```
zosport.IMG1.1234=U8888
run.U8888.zosport.IMG1.1234=active
```

However, because `zosport.IMG1.1234` is the same key, it will simply update the existing key with a new value, so what actually exists in the DSS is:

```
zosport.IMG1.1234=U8888
run.U9999.zosport.IMG1.1234=active
run.U8888.zosport.IMG1.1234=active
```

When test run U8888 ends, the DSS will contain:

```
run.U9999.zosport.IMG1.1234=active
```

What will then happen, is when the port is deleted, this code will not update the DSS because L73 will throw an exception because the entry doesn't exist and it seems the deletes might be done in an atomic action: https://github.com/galasa-dev/galasa/blob/5e5c89e00fe85f89069d45f309eda1036eaeba8f/modules/managers/galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPoolPorts.java#L72-L74

When it then comes around to resource management, it only decides if there are zosport records to delete based on the existence of a `"zosport.IMG1.<port number>`, which there is of course none, so `run.U9999.zosport.IMG1.1234=active` is never removed.

To prove this theory, I've gone through the historic test runs which failed due to ports already being in use, grabbed the port in question, and checked against the DSS. All of them have stale `run.<run id>.zosport.IMG1.<port number>=active` records in the DSS.

It feels like `this.rps.obtainResources()` really needs to be the thing that returns & reserves the port for the test run to use, so its all done in one atomic action. This of course isn't just a problem for ports, its everything that tries to allocate resources via a pool and claims then via DSS.

We can probably put something primitive together to get around this in our ecosystem by adding new DSS entries and using `putSwap()` to ensure it only claims ports when their current state is unallocated.

**Comment by Mark-J-Lawrence** [comment]
Found a fix myself, will deliver PR

**Comment by techcobweb** [comment]
I have to say, I'm not sure about your fix.

```java
} catch (DynamicStatusStoreException exception) {
  logger.info("Allocation of port failed due to collision. z/OS port " + thePort 
    + " on image " + image);
  //*** collision on the port, retry
  Thread.sleep(200 + new SecureRandom().nextInt(200)); // *** To avoid race conditions
  return allocatePort(image);
}
```

Using a recursive function here could be dodgy if the port allocation kept failing indefinitely.
You'd get an exhausted heap issue.

It would probably be better to re-work this into an iterative loop with a max-retries before giving up completely ?

eg: A network failure or something for a long time would cause the pod to crash...

**Comment by Mark-J-Lawrence** [comment]
> @Mark-J-Lawrence cc: @eamansour I have to say, I'm not sure about your fix.
> 
> ```java
> } catch (DynamicStatusStoreException exception) {
>   logger.info("Allocation of port failed due to collision. z/OS port " + thePort 
>     + " on image " + image);
>   //*** collision on the port, retry
>   Thread.sleep(200 + new SecureRandom().nextInt(200)); // *** To avoid race conditions
>   return allocatePort(image);
> }
> ```
> 
> Using a recursive function here could be dodgy if the port allocation kept failing indefinitely. You'd get an exhausted heap issue.
> 
> It would probably be better to re-work this into an iterative loop with a max-retries before giving up completely ?
> 
> eg: A network failure or something for a long time would cause the pod to crash...

It wasn't my fix :) I copied what's currently in-place for some other Galasa managers:

https://github.com/galasa-dev/galasa/blob/d41173b9ab7dfab16ef46041163afb9deecef037/modules/managers/galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosProvisionedImageImpl.java#L64-L81

https://github.com/galasa-dev/galasa/blob/d41173b9ab7dfab16ef46041163afb9deecef037/modules/managers/galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.openstack.manager/src/main/java/dev/galasa/openstack/manager/internal/OpenstackManagerImpl.java#L346-L401

https://github.com/galasa-dev/galasa/blob/d41173b9ab7dfab16ef46041163afb9deecef037/modules/managers/galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.openstack.manager/src/main/java/dev/galasa/openstack/manager/internal/OpenstackServerImpl.java#L123-L153

point taken though, agreed, I'll put something in

**Comment by Mark-J-Lawrence** [comment]
@techcobweb fix in this PR https://github.com/galasa-dev/galasa/pull/112

**Comment by techcobweb** [comment]
Is this story now complete @Mark-J-Lawrence ? What work needs to happen to close it out ?

**Comment by Mark-J-Lawrence** [comment]
Yes, agree, this is now complete and could be closed. Thanks @techcobweb
