### ISSUE TITLE
Create new Tutorial for the z/OS Batch Manager

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#21]
using the enhancements in SimBank to receive a batcj job with new accounts to create in the data lake, create a tutorial to demonstrate this.

Takeaways would be:-
1) How to submit, wait and check batch jobs
2) Possible scenario for solving test data and data lakes.
3) Deep integration with z/OS

**Comment by cxharris** [comment]
Review complete and feedback incorporated.
