### ISSUE TITLE
Test the z/OS Batch Tutorial

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#22]
Run through the tutorial.

**Comment by JonCollettIBM** [comment]
27/01/2020 - Reviewed Clive's doc for this, and very much like what he has written and how it was pitched. One slight variation on what the doc said and the output I had returned (when executing the BatchAccountsOpenTest), but this was minor (I have emailed the difference to Clive).

**Comment by JonCollettIBM** [comment]
Thanks for changing the doc Clive. I am happy to confirm that it now reflects the output that I observed.

**Comment by JonCollettIBM** [comment]
The output anomaly was corrected.
