### ISSUE TITLE
Media links replace Galasa.dev on same tab

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#251]
Clicking the Git/Twitter/Spectrum links in Galasa.dev replace the galasa.dev content on the same tab but should open a new tab, leaving Galasa.dev unchanged. I don't know if Gatsby has particular URL link syntax but straight html syntax would be:
 `<a href="URL here" target="_blank">Icon here</a> `

**Comment by CaroMac** [comment]
Thank you for the comment. This is resolved in the test environment and will be pushed to production shortly.

**Comment by CaroMac** [comment]
resolved in live.
