### ISSUE TITLE
Doc wording difference between galasa.dev & 0.7.0 code

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#252]
Docs in Galasa.dev BatchAccountsOpenTest says:
Loading the JCL with the parameters:

```
// Load the JCL with the given substitution parameters
IBundleResources resources = artifacts.getBundleResources(this.getClass());
InputStream inputStream = resources.retrieveSkeletonFile("/resources/skeletons/SIMBANK.jcl", parameters);
String jcl = resources.streamAsString(inputStream);
```

The code in /dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/BatchAccountsOpenTest.java
says
```
// Load the JCL with the given substitution parameters
InputStream inputStream = resources.retrieveSkeletonFile("/resources/skeletons/SIMBANK.jcl", parameters);
String jcl = resources.streamAsString(inputStream);
```

Not sure if I've misread anything but assume these two should correlate

**Comment by CaroMac** [comment]
Thanks for the comment. Has been amended in test environment. Will close when live.

**Comment by hobbit1983** [comment]
I'll fess up - this was me.  I updated the Artefact manager and the sim bank tests - but forgot about the docs.  Sorry Caroline and Clive.

**Comment by CaroMac** [comment]
Forgiven ! :)
This is now live so will close.
