### ISSUE TITLE
Create a K8S Operator for starting and maintaining a Galasa Ecosystem

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#293]
This operator needs to take OpenShift operators into consideration to provent too much duplication of code.

The Operator will spin up the entire Galasa Ecosystem.   Configuration of the ecosystem will be acheived by a configmap.  A configmap MUST exist as we need the proxy host for ingress and a yaml stub for PVCs.

The operator should be written in such a way that the current state is compared with the configuration and changes applied.   So at first start,  everything is down, so using the config map start bringing everything up in order.

Lower item services must be shutdown before changes are applied to high items,  ie, the the CPS statefulset is to be changed,  all the other services (bar simbank and RAS) need to be shutdown before the CPS is recycled.   If the CPS is lost,  then it should be restarted,  the lower items should auto recover.

This will be ALPHA status and a first pass prototype

**Comment by Jimbo4794** [comment]
@Michael-Baylis you happy for me to close this as the mark of the Alpha being pushed out this release?
