### ISSUE TITLE
RELEASE the HTTP Client Manager

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#297]

**Comment by hobbit1983** [comment]
Current issues with this manager 
1) Does not have a landing page from the list of managers
2) Needs some more cohesive tests

**Comment by hobbit1983** [comment]
I've cleaned up the API by commenting out methods that I think we should remove.  I've updated the other managers that used the old interface, wrote a new IVT and updated snippets.  Plan to probably deliver this change and run all the IVTs to ensure that nothing is broken, then will delete the unused code add in missing methods to round out the capability and then deliver

**Comment by hobbit1983** [comment]
My first draft of the code has been delivered, I've fixed all the stuff that I broke and the INT tests now run successfully.  so will now add the new methods and delete the comments from the previous CS

**Comment by hobbit1983** [comment]
I've updated the code and replaced the content of snippets.  Before this can reach release we need to:
-> Check that the updated Java doc is live
-> Check that snippets have been updated
-> Bump the manager to release status in the documentation
