### ISSUE TITLE
command "terminalA.waitForKeyboard().reportScreenWithCursor();" returning login screen twice

### ISSUE THREAD

**Issue by Shalini174** [galasa-dev/projectmanagement#302]
My test case has below statement mentioned :

terminalA.waitForKeyboard().reportScreenWithCursor();

However when i am running the test case, i am getting the screen returned twice on the console.

----------------------- ****************************************************************************************************
----------------------- *** Start of test class TestConnect
----------------------- ****************************************************************************************************
02/06/2020 19:25:31.554 INFO dev.galasa.framework.GenericMethodWrapper.invoke - Starting
----------------------- ****************************************************************************************************
----------------------- *** Start of test method TestConnect#testConnect,type=Test
----------------------- ****************************************************************************************************
02/06/2020 19:25:31.922 DEBUG dev.galasa.zos3270.spi.Zos3270TerminalImpl.screenUpdated - RECEIVED update to 3270 terminal term1,  updateId=term1-1
=|z/OS V2R2 PUT1512 / RSU1602                        IP Address = xxx.xxx.xxx.xxx   |
=|                                                   VTAM Terminal = SC0TCP06     |
=|                                                                                |
=|                       Application Developer System                             |
=|                                                                                |
=|                                //  OOOOOOO   SSSSS                             |
=|                               //  OO    OO SS                                  |
=|                       zzzzzz //  OO    OO SS                                   |
=|                         zz  //  OO    OO SSSS                                  |
=|                       zz   //  OO    OO      SS                                |
=|                     zz    //  OO    OO      SS                                 |
=|                   zzzzzz //   OOOOOOO  SSSS                                    |
=|                                                                                |
=|                                                                                |
=|                   System Customization - ADCD.Z22B.*                           |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=| ===> Enter "LOGON" followed by the TSO userid. Example "LOGON IBMUSER" or      |
=| ===> Enter L followed by the APPLID                                            |
=| ===> Examples: "L TSO", "L CICSTS52", "L CICSTS53", "L IMS13", "L IMS14"       |
=|                                                                                |
=|                                                                                |
^|^

02/06/2020 19:25:31.924 INFO dev.galasa.zos3270.spi.Zos3270TerminalImpl.reportScreenWithCursor - 
=|z/OS V2R2 PUT1512 / RSU1602                        IP Address = xxx.xxx.xxx.xxx   |
=|                                                   VTAM Terminal = SC0TCP06     |
=|                                                                                |
=|                       Application Developer System                             |
=|                                                                                |
=|                                //  OOOOOOO   SSSSS                             |
=|                               //  OO    OO SS                                  |
=|                       zzzzzz //  OO    OO SS                                   |
=|                         zz  //  OO    OO SSSS                                  |
=|                       zz   //  OO    OO      SS                                |
=|                     zz    //  OO    OO      SS                                 |
=|                   zzzzzz //   OOOOOOO  SSSS                                    |
=|                                                                                |
=|                                                                                |
=|                   System Customization - ADCD.Z22B.*                           |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=| ===> Enter "LOGON" followed by the TSO userid. Example "LOGON IBMUSER" or      |
=| ===> Enter L followed by the APPLID                                            |
=| ===> Examples: "L TSO", "L CICSTS52", "L CICSTS53", "L IMS13", "L IMS14"       |
=|                                                                                |
=|                                                                                |
^|^

Please confirm if this is expected behavior.

**Comment by Michael-Baylis** [comment]
The zos3270 manager will always report to the log any update to the screen automatically.  It appears you have a reportScreenWithCursor method call in your test code as well.   This is not normally required.

**Comment by hobbit1983** [comment]
Just to confirm.  The reportScreenWithCursor method simply logs what is on the screen to the log and nothing else. The framework (as Mike says) will report all interactions with the screen anyway.  If you could share some more of your code then we could look in more detail if you feel this is still a problem

**Comment by Michael-Baylis** [comment]
Closing as no updates for a while, so assuming all is ok.
