### ISSUE TITLE
Add routing option to IZosConsole

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#303]
Currently you cant route commands to different images in a plex, as the zosMF put request gets conflicting routing. When submitting a command like `RO MVXX, D IPLINFO` the created body looks like:
```
{
    "cmd" : "RO MVXX,D IPLINFO",
    "system" : "MVYY"
}
```
Where MVYY is the image that the console object was created upon. It would be good for an option to route commands either by parsing the `RO MVXX` or by having an option to specify the target image from the issueCommand() method

**Comment by DavidXRoberts** [comment]
Fixed
