### ISSUE TITLE
Make use of recent 3270 Manager improvements in CECI Manager

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#311]
Remove the tortuous processing that the CECI Manager used to overcome lack of some 3270 keys which have now been provided.

**Comment by hobbit1983** [comment]
@DavidXRoberts When you complete this note the IVT can be used to test the changes

**Comment by DavidXRoberts** [comment]
@hobbit1983 I've finally completed this. Where's the IVT?

**Comment by Michael-Baylis** [comment]
dont believe we have an IVT until I have written the SEM Manager

**Comment by hobbit1983** [comment]
Nope we do have an IVT but it doesn't run automatically because we can't provision an environment - let me take a look

**Comment by hobbit1983** [comment]
In the managers project I have a CECI IVT branch that has the IVT in it

**Comment by hobbit1983** [comment]
IVT is running

**Comment by hobbit1983** [comment]
IVT passes at 0.11.0-SNAPSHOT
