### ISSUE TITLE
Jenkins plugin does not fail upon a test faillure

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#327]
Jenkins plugin is not marked for failure upon a test failure, and any future steps are run.

**Comment by hobbit1983** [comment]
I can see if we timed out trying to get test results that there is a gap where the runs state will not get updated.  However a failing test should have caused the build to fail - so will need to replicate. @Jimbo4794 was this a true test failure or an env failure or ignored test that triggered the behaviour?

**Comment by Jimbo4794** [comment]
Resolved small issues with the plugin not reognising test end states as failures.

The resposibility of failing a pipeline script should be the script it self. Using the POST step in a stage can allow failures to end pipelines
