### ISSUE TITLE
waitForTextInField for multiple text options

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#332]
Currently the waitForTextInField method of the Terminal class in dev.galasa.3270 will wait for one supplied text string. 

In the situation where customer data needs to be retrieved from Hursley Bank, the customer lookup will either return successfully ("Customer lookup successful. <PF5> to Delete. <PF10> to Update.") or fail with an error message. In this case I need to wait for either the success or fail message to process the screen. Ideally the waitForTextInField would be able to accept and reject a list of text strings.

**Comment by Michael-Baylis** [comment]
WaitForTextInField for ok and error arrays is available in 0.10.0-SNAPSHOT
