### ISSUE TITLE
3270 terminal tab issue

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#344]
If the cursor is placed at the attribute byte of an input field, then tab() skips the field and moves to the next input field.
e.g.
```
terminal.home().tab(); // locates to second input field
terminal.home().cursorLeft().cursorLeft().tab(); // locates to second input field
terminal.home().tab().cursorLeft().tab(); // locates to third input field
```

**Comment by Michael-Baylis** [comment]
@DavidXRoberts Have you got a example test so I can see what is happening in the wild?

**Comment by DavidXRoberts** [comment]
This test will fail for this and #345 
`import org.assertj.core.api.Assertions;

import dev.galasa.BeforeClass;
import dev.galasa.ICredentials;
import dev.galasa.ICredentialsUsernamePassword;
import dev.galasa.Test;
import dev.galasa.zos.IZosImage;
import dev.galasa.zos.ZosImage;
import dev.galasa.zos3270.ITerminal;
import dev.galasa.zos3270.Zos3270Terminal;
import dev.galasa.zos3270.spi.NetworkException;

@Test
public class TestTerminal {

    @ZosImage(imageTag = "A")
    public IZosImage image;

    @Zos3270Terminal(imageTag = "A")
    public ITerminal terminal;
    
    @BeforeClass
    public void beforeClass() throws Exception {
        if (!terminal.isConnected()) {
            throw new NetworkException("Terminal not connected");
        }
                
        ICredentials creds = image.getDefaultCredentials();
        String user = ((ICredentialsUsernamePassword) creds).getUsername();
        String password = ((ICredentialsUsernamePassword) creds).getPassword();
        
        // Logon to ISPF main menu
        terminal.waitForKeyboard();
        String logonCommand = "MVS2CTSO " + user;
        terminal.type(logonCommand).enter().waitForKeyboard();
        terminal.enter().waitForKeyboard().enter().waitForKeyboard();
        terminal.type(password).enter().waitForKeyboard().enter().waitForKeyboard();
        if (terminal.retrieveScreen().contains("READY")) {
            terminal.type("ISPF").enter().waitForKeyboard().reportScreenWithCursor();
            Thread.sleep(2000);
        } else {
            terminal.enter().waitForKeyboard().reportScreenWithCursor();
        }
        Thread.sleep(1000);       
    }
    
    @Test
    public void testNewLine() throws Exception {
        terminal.positionCursorToFieldContaining("Option ===>").tab().reportScreenWithCursor();
        String value = terminal.newLine().retrieveFieldAtCursor();
        terminal.reportScreenWithCursor();
        Assertions.assertThat(value).isEqualTo("Settings    ");
    }
    
    @Test
    public void testTab() throws Exception {
        terminal.positionCursorToFieldContaining("Option ===>").tab().reportScreenWithCursor();
        String value = terminal.tab().retrieveFieldAtCursor();
        terminal.reportScreenWithCursor();
        terminal.cursorLeft().tab().reportScreenWithCursor();
        Assertions.assertThat(value).isEqualTo(terminal.retrieveFieldAtCursor());
    }
}`

**Comment by Michael-Baylis** [comment]
brill,  thank you. will have a play

**Comment by Michael-Baylis** [comment]
I believe I have fixed this specific test case
