### ISSUE TITLE
3270 newLine() not working as expected

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#345]
newLine() moves the cursor to the start of the next line on the screen.
However, it should move the cursor to the first input field on the next line that has an input field.

**Comment by Michael-Baylis** [comment]
@DavidXRoberts Have you got a example test so I can see what is happening in the wild?

**Comment by DavidXRoberts** [comment]
See #344

**Comment by Michael-Baylis** [comment]
Wow,  huge defect in newline!!!!!!!!!!  How on earth did that get through JUnits

**Comment by Michael-Baylis** [comment]
ah, not got a test where there is a protected field in between the potential targets

**Comment by Michael-Baylis** [comment]
I believe I have fixed this specific test case
