### ISSUE TITLE
Add browser preferences and take screenshots when a test fail in Selenium Manager

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [galasa-dev/projectmanagement#364]
Would be great to have the ability to add some properties to the driver, something like the code below. In addition taking an screenshot when a test failed helps when troubleshooting.

**Browser Properties**
> FirefoxOptions ffOptions= new FirefoxOptions(); 
ffOptions.setHeadless(true);
ffOptions.addPreference("dom.webcomponents.enabled", true);
ffOptions.addPreference("dom.disable_beforeunload", true);
ffOptions.addPreference("app.update.auto", false);
ffOptions.addPreference("app.update.enabled", false);
ffOptions.addPreference("app.update.silent", false);
ffOptions.addPreference("dom.popup_maximum", 0);
ffOptions.addPreference("privacy.popups.showBrowserMessage", false);
WebDriver driver = new FirefoxDriver(ffOptions);

**Taking screenshots**
> File file = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);

**Comment by alfonso-rios-ibm** [comment]
I tried to use the selenium screenshot property but the image is not displayed properly.

![image](https://user-images.githubusercontent.com/48730438/89212293-d429d000-d588-11ea-9fa3-6c58cdc4e12a.png)
![image](https://user-images.githubusercontent.com/48730438/89212319-dc820b00-d588-11ea-8c28-ec7fe522d4c7.png)

**Comment by Michael-Baylis** [comment]
The Eclipse plugin should have downloaded the file instead of opening ineditor as a text file.   Will have a look.

**Comment by Michael-Baylis** [comment]
For starters,   the Selenium Manager incorrectly saves the stored artifact as a text file.  which is why it is opening in Eclipse.
Second, there is no code to download a non-text artifact.

**Comment by Michael-Baylis** [comment]
ok,  the selenium manager will store as application/png

Will find the JAT code that causes downloads to happen and copy to Galasa

**Comment by Jimbo4794** [comment]
Sorry should of updated and closed this earlier. Eclipse now allows for Images to be opened properly, and browser options can now alos be passed. (0.11.0-SNAPSHOT)
