### ISSUE TITLE
Need to find out requirements to make Galasa java 11 compliant

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#372]
Currently mostly affecting the VS code plugin as the RedHat langage support for Java has enforced the use of java 11 and above, which galasa does not currently support.

As mentioned by Richard,  eclipse will soon be moving to java 11 too: https://www.eclipse.org/lists/eclipse-pmc/msg03821.html

**Comment by matthewchivers** [comment]
Related: #403 "Eclipse Plugin not compatible with version 4.15+", where Eclipse logs indicate failure of the Galasa plugin due to the requirement of Java 11.

**Comment by hobbit1983** [comment]
From a compile perspective (compiling with a java 11 JDK but targeting java 8.

Maven - no issues

Framework - apache Felix and Jacoco not happy with the change of JVM upgrading org.apache.felix:maven-bundle-plugin to 5.1.1 and org.jacoco:jacoco-maven-plugin to 0.8.6 fixes this - NB this will probably be fixed when we move to gradle anyway
                    - We also utilise the com.sun.javadoc packages from tools.jar which up until java9 was in the lib directory of the JDK.  However this API is now deprecated and replaced by javax.lang.model. thus galasautils-maven-plugin will also need to be updated to use the new API.  See http://cr.openjdk.java.net/~chegar/httpclient/02/javadoc/api/deprecated-list.html and https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/package-summary.html#migration

Managers    - As of Java 9 (feel I might be saying this a lot) the JAXB APIs were considered not part of J2SE and were removed from the default class path - in Java 11 they are not in the JDK at all - they can be re-added using 2 maven dependencies see - https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio
Currently investigating a failure in the surefire plugin when building the CICSTS Manager.

**Comment by hobbit1983** [comment]
Believe I have solved the problem with the CICSTS CECI manager, simbank, extensions all appear to compile cleanly now with 11 - just want to confirm that managers is happy

**Comment by hobbit1983** [comment]
Woo - have got galasa building using Java 11 (but targeted for Java 8) now to see if it actually runs

**Comment by hobbit1983** [comment]
Moving on to run Galasa on a Java 11 VM.  First problem is with GSON, all available versions of GSON explicitly require either a 1.5, 1.6, 1.7 or a 1.8 ExecutionEnvironment.  Run it with a V11 runtime and OSGi gets all upset:
09/10/2020 17:24:19.705 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unable to resolve dev.galasa.framework/0.12.0.202010082201
09/10/2020 17:24:19.705 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: ee:(|(ee=JavaSE-1.6))
09/10/2020 17:24:19.705 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: ee:(|(ee=J2SE-1.5)(ee=JavaSE-1.6)(ee=JavaSE-1.7)(ee=JavaSE-1.8))
09/10/2020 17:24:19.705 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: package:(&(package=com.google.gson)(version>=2.7.0)(!(version>=3.0.0)))
Pretty sure this is OSGi complaining correctly about the level of the VM and not a bug in felix.  Which gives us a problem, AFAIK there is no plan to give GSON java 11, do we need to look at a different JSON parser?

**Comment by hobbit1983** [comment]
I've now wrapped GSON as a better OSGi bundle and am working in getting that incorporated into the rest of the build
