### ISSUE TITLE
Document an error message that can be ignored when importing a Maven Project

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#375]
![image.png](https://images.zenhubusercontent.com/5e45650eee4f44318eb1897c/84ec2f11-e998-4f1c-9250-d201abbc48cd)

In the instructions for **Importing the prepared directory into Eclipse** at  https://galasa.dev/docs/writing-own-tests/setting-up-galasa-project the import process creates the error shown in the image. Mike tells me this is expected and can be ignored but will disappear in time. Until it does, I think we should add a small note to the instructions to indicate that it may be safely ignored.

**Comment by CaroMac** [comment]
Added If you see a warning or error dialog, opt to resolve the error later.
