### ISSUE TITLE
Galasa 3270 Gherkin enhancements

### ISSUE THREAD

**Issue by sayom88** [galasa-dev/projectmanagement#376]
Hello @Michael-Baylis  @hobbit1983 ,

As we discussed today, setting up a request for the expansion of Galasa Framework to handle generic Test Step Creation and Step Definition For Mainframe Applications.

**Comment by Michael-Baylis** [comment]
If you could "design" the Gherkin statements you would like to see in the 3270 Manager and list them in here please.   We can have a discussion on what they would like to ensure they do not collide with any future support in other Managers.

**Comment by sayom88** [comment]
Yes surely. Here you go.
[Sample Gherkin FF.zip](https://github.com/galasa-dev/projectmanagement/files/5040598/Sample.Gherkin.FF.zip)

**Comment by Michael-Baylis** [comment]
Readme of the zos 3270 manager updated with the list of supported gherkin statements,   it is not the full set,  but enough to get going.
https://github.com/galasa-dev/managers/tree/master/galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos3270.manager

sample Simbank test that works:-
https://github.com/galasa-dev/simplatform/blob/master/galasa-simbank-tests/dev.galasa.simbank.gherkin.tests/simbankivt.feature
