### ISSUE TITLE
Slack Workspace Invite Link Broken?

### ISSUE THREAD

**Issue by cgossett** [galasa-dev/projectmanagement#377]
I'm trying join the Galasa Slack workspace by using the link from the Support page of the Galasa site. I'm directed to Slack to enter my email, after which it says I've been sent an invite link, however I never receive an email. Is the invite link still accurate? This is the link I'm using, taken from the Support page:
 * [https://join.slack.com/t/galasa/shared_invite/zt-ele2ic8x-VepEO1o13t4Jtb3ZuM4RUA](https://join.slack.com/t/galasa/shared_invite/zt-ele2ic8x-VepEO1o13t4Jtb3ZuM4RUA)

**Comment by hobbit1983** [comment]
Hi. Thanks for your interest. That link should still be active. However we will investigate over the weekend and get you a link that works. Sorry for the delay

**Comment by hobbit1983** [comment]
I've just tested the link and it appears to still be valid. Could the email have ended up in a spam folder?

**Comment by hobbit1983** [comment]
If you still can't find it. Email me at wyates@uk.ibm.com and I can invite you manually

**Comment by cgossett** [comment]
Thanks so much @hobbit1983! I tried again this morning and was able to receive the email invite from Slack. I'll go ahead and close this issue since things seem to be working now. See you in Slack!
