### ISSUE TITLE
ALPHA - RSE support for zOS Managers

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#389]
Investigate the RSE v1 API server to see what managers can be supported, with a leaning towards batch.

This is so a customer can opt to use RSE rather than zosmf. 

zOSMF support will still be needed, so is not a replacement,  it is an alternative.

**Comment by DavidXRoberts** [comment]
Implemented for Assembler/C/Cobol/Pl1 batch and CICS

**Comment by DavidXRoberts** [comment]
Closed in error
