### ISSUE TITLE
Problem deploying updates to website due to change in latest cloud foundry cli

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#394]
I got this error https://travis-ci.com/github/galasa-dev/galasa.dev/jobs/379801710 when trying to merge this PR to production https://github.com/galasa-dev/galasa.dev/pull/230  
I spoke to Ben about it and he noted the following on his machine :
Upgrading to the latest cf sub-command gets me that same error. Just noting things down for my reference:
Previous ic-embedded cf version: 6.50.0
New (broken) ic-embedded cf version: 6.52.0
It transpired that :
There’s been a change in the latest Cloud Foundry CLI, cf, which changes its home directory (where it stores its logged-in state, etc) as per https://github.com/cloudfoundry/cli/releases/tag/v6.52.0. This now makes it incompatible with the ibmcloud/ic CLI, which does some interaction with cf too, tries to read/write its home directory. So ic was setting up the logged-in state, then cf was trying to read the logged-in state… from somewhere else.
To fix, I’ve pinned the version of the cf CLI to 6.51.0, i.e. the version immediately proceeding the breakage. I imagine that ic will be updated in short order to make it compatible with cf again, so we could do with creating a task, deferred by a few weeks, to investigate compatibility and remove that pinning. 
For reference… It’s planned to be fixed in ic version 1.2.1, and tracked at https://github.ibm.com/Bluemix/bluemix-cli/issues/3237.

**Comment by ind1go** [comment]
This issue is to remedy the version pinning once a compatible update has been released. Will revisit in a week or two.

**Comment by CaroMac** [comment]
I believe this is now resolved so will close.
