### ISSUE TITLE
https://github.com/galasa-dev/wrapping/blob/master/README.md  refers to Spectrum not slack

### ISSUE THREAD

**Issue by MN-Mike** [galasa-dev/projectmanagement#396]
I see reference to Spectrum in the README.md in this github section.  I assume we are moving to Slack for usage questions?

**Comment by hobbit1983** [comment]
Yes please Mike.  I'm leaving the spectrum channel there for a while to ensure everyone has moved over and then will be closing it

**Comment by Michael-Baylis** [comment]
@hobbit1983 we can action this now can't we?   is there any reference to spectrum still hanging around?

**Comment by hobbit1983** [comment]
checking

**Comment by Michael-Baylis** [comment]
No I have actually read the issue properly,  closing as wrapping readme has been changed

**Comment by hobbit1983** [comment]
Can't see any references to spectrum in the READMEs

**Comment by hobbit1983** [comment]
Deleted the galasa spectrum thingy
