### ISSUE TITLE
Broken links in zOS Program manager Docs

### ISSUE THREAD

**Issue by cliftona-hursley** [galasa-dev/projectmanagement#397]
Looking at the documentation for z/OS Program Manager at https://galasa.dev/docs/managers/zos-program-manager and expanding the "zOS Program" twistie gives a section that contains links to  ZosProgram.Language,  ZosProgram and IZosProgram all of which give a "not found" error.

**Comment by CaroMac** [comment]
I spoke with Dave about this - there seems to be a problem with the Javadoc build- he is investigating with a view to delivering the fix for the next release.

**Comment by CaroMac** [comment]
Spoke with Dave and Mike is looking to fix this.

**Comment by CaroMac** [comment]
ZosProgram and IZosProgram now appear to work. Just  ZosProgram.Language is erroring.

**Comment by CaroMac** [comment]
I can see that the link to the ZosProgram.Language in the annotations section is wrong. It is https://javadoc-snapshot.galasa.dev/ZosProgram/Language.html but it should be https://javadoc-snapshot.galasa.dev/dev/galasa/zosprogram/ZosProgram.Language.html. The trouble is I don't see where this link is being set. I've done quite a bit of searching but to no avail.   I tried importing import dev.galasa.zosprogram.ZosProgram.Language; at the top of the file but it has not worked. The link in the Javadoc seems to work fine eg in dev.galasa.zosprogram.spi but it does not work in this topic. The link @ annotation in the topic works fine for ZosProgram and IZosProgram and goes to the correct url ie https://javadoc-snapshot.galasa.dev/dev/galasa/zosprogram... Will need to ask @Michael-Baylis for help with this link problem.
