### ISSUE TITLE
Documentation for zOS Program manager not present

### ISSUE THREAD

**Issue by cliftona-hursley** [galasa-dev/projectmanagement#398]
This may be related to issue #397.

On the page https://galasa.dev/docs/managers/zos-program-manager is a statement: "You can view the Javadoc documentation for the Manager here" which has a link to https://javadoc.galasa.dev/ but on following the link, the only mention of program on the page is in the description for dev.galasa "Galasa - Testers Programming Interface (TPI)"

**Comment by CaroMac** [comment]
Yes, this is related to issue #397 - the Javadoc for the program manager is failing to build - Dave is investigating.

**Comment by CaroMac** [comment]
I can now see program manager so can update link to program manager

**Comment by CaroMac** [comment]
Java doc now available so have updated link to point here https://javadoc.galasa.dev/dev/galasa/zosprogram/package-summary.html
