### ISSUE TITLE
QoL:  Backup CPS properties

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#404]
At the moment,  there is no easy way of backing up the etcd CPS properties, other than using the etcd snapshot routines.  Also,  the underlying CPS may not be etcd,  so we need a consistent way of backing up and restoring the CPS via the framework.

So this Epic will create a routine that runs under galasa-boot to read the CPS and write to the console the current CPS properties.   We write to the console so that it can be piped to wherever the user wants, rather than force it to a file.

1) create a new option in galasa-boot called "backupcps" in dev.galasa.boot.Launcher
2) create a new method in dev.galasa.boot.felix.FelixFramework to receive the backupcps call.
3) create a new OSGi service in dev.galasa.framework, that (2) will call.
4) The new OSGi service will initialise the Framework
5) Read the CPS via the CPS SPI and write property as a separate line to the console in the format key=value.
6) Ignore all CPS properties starting with dss., certificate., secure. .

**Comment by matthewchivers** [comment]
Spoke to @Michael-Baylis regarding the output destination for CPS properties. 

Currently, this feature requests that cps properties be sent to standard output, the same destination as log entries. This creates a mish-mash of cps properties and log entries. It would not be ideal (or long-term sustainable) to place responsibility on an end user to work out how to extract the necessary values from this output.

The revised, preferred solution is to output the properties to a user-specified file location. This location shall be specified using the option `-f`.

**Comment by hobbit1983** [comment]
Would an option like outFile be better for when we do mass loading of CPS properties from a a file?

**Comment by matthewchivers** [comment]
Is it possible to include the file name as an argument after the backupcps option?

'--backupcps dir/file name.txt' without needing the extra '-f' ?

**Comment by hobbit1983** [comment]
Possible yes. But if we ever need to add extra flags to the utility in future it would be good to designate the output file with a flag

**Comment by Michael-Baylis** [comment]
--file and -f are the options we should go for as they can be reused for restorecps and anything else that will use a file

**Comment by matthewchivers** [comment]
Feature implemented and merged into master as PR #182 on @galasa-dev/framework .
