### ISSUE TITLE
QoL: Create an Eclipse editor to edit the CPS properties

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#406]
To make it easy to maintain the CPS properties, rather than having to use the etcdctl command, please create an Eclipse editor to edit the CPS properties via the framework.

1) The Framework needs to be initialised for this editor to work,  so if it is not, please display a label, instead of a text editor to say, initialise framework.
2) Exclude properties starting with dss. certificate. secure. from consideration, both read and write, they will have their own views and editors eventually.
3) Read all the current properties into the editor as a flat text file, as it was in JAT.
4) When the user saves, compare the new values with the current values (you will have to check the framework again as a long time may have happened between read and save and someone else may have changed the values).
5) Report the proposed changes to the user.
6) Apply the changes.

Essentially as it was with the JAT Standard Properties Editor, you can use that source as a guide.

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
