### ISSUE TITLE
QoL: Copyright checker for pull requests

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#407]
After searching in GitHub, Will and I can't find a preexisting app to perform copyright change checks on every pull request.  So we need to write one.
This new app is to be written so that it can be used by the world, as a possible "loss leader" to generate interest in Galasa.
Michael has done a bit of research and the suggestions below are based on this, however, there may be a better way of doing this, so if you find it, please let Michael know.

1) You need to create a new Java http server application.  Select whichever is best for the job.
2) Needs to be written in Java 11.
3) Will run in a docker container within kubernetes.
4) Written as a GitHub App rather than a webhook.
5) The authentication is complicated and needs to be resolved.
6) The program will receive notification from github that a pull request has been raised.
7) The app will check the branch to see if there is a copyrightcheck.yaml file in the root of the repo.   If there is not, don't do anything.
8) If there is, read the YAML file.  The structure is open, but it is suggest something like:-

message: (c) Copyright IBM Corp. (\d{4}\,)?(\d{4})\.
filepatterns:
- .*\.java
- .*\.ts

9) For each file that has CHANGED, and matches the patterns, check for the presence of the regex in the file and that the LAST group is the current year, based on LOCAL time.
10) Raise a status on the github to reflect the presence of the copyright message,  failed if the message is missing or incorrect year.  Passed if ok.
11) It is unsure if you need to provide a link to a report or you can list the files that need changing directly on the status.

**Comment by techcobweb** [comment]
Copyright tool exists. This issue can be closed.
