### ISSUE TITLE
Zip based RAS for audit purposes

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#41]
Create a RAS, intended to run in parallel with the CouchDB RAS, so that tests are automatically archived in zip files for long term storage, for audit purposes.

Possible targets are FTPS, SFTP, HTTP, S3, Google Filestore, whatever the IBM equiv is, etc

**Comment by hobbit1983** [comment]
Duplicated by https://github.com/galasa-dev/projectmanagement/issues/1407 &
