### ISSUE TITLE
Additional documentation around CPS

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#417]
After speaking with Will - 

1. How the cps binds your test material to your environment - inc information around clustering, referencing multiple lpars in the same test
2. How to edit a cps properties file (can be done locally or in ecosystem)
3. What do I use a Manager for
4. Best practice around eg # of projects to use, how to categorise tests, number of tests - these could depend on things like the number of applications you have or the test environments you have eg best so far and production.

**Comment by CaroMac** [comment]
further thigns to do, deploy maven artifacts to the nexus

we will need to create some instructions for people not using the provided nexus to reconfigure the CPS to look for a different repo

**Comment by CaroMac** [comment]
doing 1 and 2 for this. will raise new issues for 3 and 4.

**Comment by CaroMac** [comment]
https://github.com/galasa-dev/galasa.dev/pull/257 and url is https://deploy-preview-257--galasa.netlify.app/docs/writing-own-tests/binding-tests

**Comment by CaroMac** [comment]
Question: is the Zos.dse.tag required or used ? Do I need to include that in this topic? 
![CPS.PNG](https://images.zenhubusercontent.com/5e971680326f9124fa876a8c/ff7542b9-a8e7-4982-885a-8fefc97dd0b9)

**Comment by Michael-Baylis** [comment]
in this particular instance,  the dse properties should not be provided for zos

**Comment by Michael-Baylis** [comment]
but need something in the docs to explain that some managers have dse properties to "force" the tests to be provisioned with specific resources.

Be very careful of using a TAG with the same name as the resource.

The
zos.dse.tag.PRIMARY.imageid=MVLA
zos.dse.tag.PRIMARY.clusterid=PLEXLA
would be the correct way to demonstrate.

**Comment by CaroMac** [comment]
I think I will raise a separate issue for that as it probably needs a bit more explanation outside of this topic where the aim is to explain late binding in clustering by building on a galasa test example.
