### ISSUE TITLE
Updates needed on Galasa Program Manager Page

### ISSUE THREAD

**Issue by cliftona-hursley** [galasa-dev/projectmanagement#421]
The Program Manager on page https://galasa.dev/docs/managers/zos-program-manager has a few issues that need updates - if individual issues are required for any or all of these please advise.

All these are under the "Configuration Properties" sections.

All sections indicate that Valid values are "$validValues".
The descriptions do  generally expand much on the name of the property.
Do none of the properties default to environment information?
Apart from custom compile syslibs, all properties are listed as required. With no defaults I guess this is understandable. However, if this is a none CICS Batch Program (as per the code snippets) do I really need to supply a CICS Dataset prefix?
In the examples, it took me a while to realise a comma separated items in a list rather than typo for a full stop. Does this need explanation or is it a standard approach I have not yet learnt?

**Comment by CaroMac** [comment]
Meeting with Dave to discuss additional documentation

**Comment by DavidXRoberts** [comment]
These properties need to be reworked. Currently just Alpha to get the manager working. Most the values should really be obtained from the zOS and CICS managers

**Comment by CaroMac** [comment]
Will speak to Dave again once he is back of holiday

**Comment by CaroMac** [comment]
Spoke to Dave. Code changes still need to be made, so its best not to update the docs until that is completed.

**Comment by DavidXRoberts** [comment]
Hi @CaroMac I've made updates to the Program Manager properties classes. Not sure if the docs are built automatically, but you should be able use the content from the classes.

**Comment by CaroMac** [comment]
Preview available here https://deploy-preview-318--galasa.netlify.app/docs/managers/zos-program-manager
