### ISSUE TITLE
0.11.0 tn3270 Manager may have added extra text to screen buffer 

### ISSUE THREAD

**Issue by MN-Mike** [galasa-dev/projectmanagement#423]
Using the 3270 manager, it appears now that all the screens have some attributes at the end of the screen buffer with the status of the connection, screen size, cursor position and keyboard lock status.  

I use the method to confirm the screen is cleared ( containsOnlyWhitespaces() ) and it no longer works as these attributes appear to be in the screen buffer. 

The code I execute is below and the assert is consistently failing for me now.   I attached the run log from a recent test. 

		terminal.clear().waitForKeyboard();
		assertThat(terminal.retrieveScreen()).containsOnlyWhitespaces();

[run.log](https://github.com/galasa-dev/projectmanagement/files/5357451/run.log)

On a related note, I uninstalled Galasa from my Eclipse and reinstalled 0.10.0 but the logs still seem to execute the 0.11.0 framework, how do I get that to fall back?

**Comment by hobbit1983** [comment]
Hi Mike. I will leave Mike Baylis to confirm the changes to 3270 manager. But to roll back you will have to update the release of Galasa that is referenced in the Galasa preferences in eclipse

**Comment by hobbit1983** [comment]
@Michael-Baylis can you answer the 3279 question please

**Comment by MN-Mike** [comment]
I think I need a little more guidance on how to switch back to 0.10.0 in eclipse, I have uninstalled 0.11.0, restarted.  Then reinstalled 0.10.0, restarted. But the test executions are still finding the 0.11.0 libraries.  I found them in the .m2 folders and removed all the 11 folders.  But they all returned when I ran the next test.  

I have gone through all the property menus in Eclipse and do not see anything that points to a framework version for galasa.

**Comment by Michael-Baylis** [comment]
That was my error,    I have since removed the text from the retrieveScreen, so will be back to as it was in 0.12.0.
The default for running locally is the use the latest version.   you can override this by using the Eclipse Galasa preferences,  there is a field for OBR Version,   change this to 0.10.0. and that will use the version you wish.
