### ISSUE TITLE
Galasa results are not loaded in eclipse and got error message when initialise the framework

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [galasa-dev/projectmanagement#427]
Problem right after I initialise the galasa framework in eclipse.

`Initialising the Galasa Framework
Configuration Property Store is etcd:http://galasa1.fyre.ibm.com:2379
Searching for CPS providers
Found CPS Provider dev.galasa.cps.etcd.internal.Etcd3ConfigurationPropertyRegistration
Found CPS Provider dev.galasa.framework.internal.cps.FpfConfigurationPropertyRegistration
Selected CPS Service is dev.galasa.cps.etcd.internal.Etcd3ConfigurationPropertyStore
Dynamic Status Store is etcd:http://galasa1.fyre.ibm.com:2379
Searching for DSS providers
Found DSS Provider dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStoreRegistration
Found DSS Provider dev.galasa.framework.internal.dss.FpfDynamicStatusStoreRegistration
Selected DSS Service is dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStore
Result Archive Stores are [couchdb:http://galasa1.fyre.ibm.com:5984, file:///Users/alfonso/.galasa/ras/]
Searching for RAS providers
Found RAS Provider dev.galasa.framework.internal.ras.directory.DirectoryResultArchiveStoreRegistration
Found RAS Provider dev.galasa.ras.couchdb.internal.CouchdbRasRegistration
Selected RAS Service is dev.galasa.framework.internal.ras.FrameworkMultipleResultArchiveStore
Credentials Store is etcd:http://galasa1.fyre.ibm.com:2379
Searching for Creds providers
Found Creds Provider dev.galasa.cps.etcd.internal.Etcd3CredentialsStoreRegistration
Found Creds Provider dev.galasa.framework.internal.creds.FileCredentialsRegistration
Selected Credentials Service is dev.galasa.cps.etcd.internal.Etcd3CredentialsStore
Searching for Confidential Text Service providers
Found Confidential Text Services Provider dev.galasa.framework.internal.cts.FrameworkConfidentialTextServiceRegistration
Selected Confidential Text Service is dev.galasa.framework.internal.cts.FrameworkConfidentialTextService
Framework initialised`

<img width="364" alt="image" src="https://user-images.githubusercontent.com/48730438/97313697-8d1c4580-182c-11eb-9021-8858aa5016eb.png">
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/48730438/97313646-7e359300-182c-11eb-894b-5a82ede6e29d.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/48730438/97313816-ac1ad780-182c-11eb-85e2-df893d291761.png">

**Comment by Michael-Baylis** [comment]
I have fixed the problem,   just need to get it to p2-snapshot.   We have a problem with the integration testing at the moment which requires me to sort some infrastructure.
Will let you know when it has reached public

**Comment by Michael-Baylis** [comment]
Integration pipeline running again.

The updated p2 snapshot should now have this fix
