### ISSUE TITLE
Convert the Framework repo to Gradle

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#441]
Finish converting the remaining Maven projects to Gradle and test the build, excluding the maven plugin projects of course.  Enable the building of the OBR and the npm packages.

**Comment by matthewchivers** [comment]
Closing, having implemented the framework build conversion in the following PRs: 
* @galasa-dev/framework#220
* @galasa-dev/framework#240
* @galasa-dev/framework#241
* @galasa-dev/framework#242
* @galasa-dev/framework#243
* @galasa-dev/framework#244
