### ISSUE TITLE
Find or write a Gradle plugin to build the openapi.yaml files into typescript code

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#445]
The build of the framework api projects also build the typescript code used by the webui and vscode.

The plugin needs to run the openapi generator and then build and deploy the npm packages,  probably calling the npm command.

Needs to be build cache aware AND set the build cache for the resulting artifacts.

**Comment by matthewchivers** [comment]
Closing this, as the openapi plugin was implemented in the framework build 👍🏻
