### ISSUE TITLE
Convert the Managers standard projects to Gradle

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#450]
For all those projects that can be converted,  convert to Gradle,   excluding BOM,  uber obr and uber javadoc.

- [x] Core
- [x] Comms 
- [x] Logging
- [x] zOS
- [x] CICS/TS
- [x] Unix
- [x] Cloud
- [x] TestingTools
- [x] Other

**Comment by matthewchivers** [comment]
Final section 'other managers' in for review @galasa-dev/managers([445](https://github.com/galasa-dev/managers/pull/445))

Other PRs that will close this (all in @galasa-dev/managers):
Core: [429](https://github.com/galasa-dev/managers/pull/429)
Comms: [433](https://github.com/galasa-dev/managers/pull/433)
Logging: [435](https://github.com/galasa-dev/managers/pull/435)
zOS: [438](https://github.com/galasa-dev/managers/pull/438)
CICS TS: [439](https://github.com/galasa-dev/managers/pull/439)
Unix: [440](https://github.com/galasa-dev/managers/pull/440)
Cloud: [442](https://github.com/galasa-dev/managers/pull/442)
TestingTools: [443](https://github.com/galasa-dev/managers/pull/443)

**Comment by matthewchivers** [comment]
Integration tests passing with all java builds converted. Closing Issue.
