### ISSUE TITLE
zOSMF and RSE API have different String values for Job status

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#456]
`IZosBatchJob.getStatus()` returns a String value that is different between the zOSMF and RSE API implementations.

I suggest a `JobStatus` Enum and public `JobStatus getStatus()` and `public String getStringStatus()` 

This will break existing users, but if we don't change `getStatus()` then tests could fail when switching between implemntations

**Comment by Michael-Baylis** [comment]
I agree with the enum.  Will take the hit with the users.

Set for release in 0.13.0.

When it gets to 0.13.0-SNAPSHOT,  will need to post of Galasa slack to let the users of 0.13.0-SNAPSHOT and 0.13.0-NIGHTLY know.

**Comment by DavidXRoberts** [comment]
OK, I'll look at this next
