### ISSUE TITLE
zOS/MF CPS properties need reworking

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#457]
The way the current CPS properties work at the moment, mistakenly uses the ClusterID as a reference,  where it should not as ClusterID should only be used for zosImage provisioning.  To find which zOS/MF zos* should use for managing an Image should be a combination of Image and Sysplex.  So I propose the following CPS properties and routes to finding the zosmf server to use for a provisioned zos image

First, a zosmf server should have a unique ServerID (instead of using the clusterID), reason, there may be 2 zOS/MF servers on an image:-
zosmf.server.SERVERID.image=IMAGEID      (says where the server is installed, used to get host name and default creds)
zosmf.server.SERVERID.port=99999        ( the host name is not provided as should get from unmanaged zosimage, saves coding twice)
zosmf.server.SERVERID.https=true          (https or not, default true)
zosmf.server.SERVERID.credentials=CREDSID    ( incase your want to override the default zosimage creds)

We need an default index of all the zOSMF servers on a SYSPLEX (not cluster).
zosmf.sysplex.SYSPLEXID.default.servers=SERVERID1,SERVERID2
(changed the zosmf.server. to zosmf.sysplex. as it was confusing the hell out of me what the property related to.)

we also need the ability to override for specific images:-
zosmf.image.IMAGEID.servers=SERVERID1,SERVERID2

So if you need a zosmf server for MV2C,  you would do the following:-
Search for 
zosmf.image.MV2C.servers=SERVERID1
if not found, request the sysplexid (mandatory) from zosimage:-
zos.image.MV2C.sysplex=PLEX2
get the server list for PLEX2
zosmf.sysplex.PLEX2.default.servers=SERVERID1,SERVERID2

The sysplex assumes that it is a shared MAS, if the MAS is not,  then the image override comes into play for complicated scenarios.

if missing, assume a default zosmf server on the actual instance and assume the default port (443?)

**Comment by DavidXRoberts** [comment]
Looks OK to me. Same changes will be required for RSE API Manager

**Comment by Michael-Baylis** [comment]
We will have to make sure everyone is aware on the release in JAN

**Comment by Jimbo4794** [comment]
No this sounds good. I think this makes it clearer to be honest, especially when selecting zosmf servers to images

**Comment by hobbit1983** [comment]
makes sense

**Comment by Michael-Baylis** [comment]
Pushed
