### ISSUE TITLE
zOS/MF BatchJob toString should return simple output

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#462]
dev.galasa.zosbatch.zosmf.manager.internal.ZosmfZosBatchJobImpl.toString() should return "JOBNAME(JOBID)" only so can be easily referenced by other managers in diagnostic messages.
At the moment,  the status message is too much information.
I didn't simply change it because unsure of the implications.

**Comment by DavidXRoberts** [comment]
Done for batch.
Same changes required for File

**Comment by DavidXRoberts** [comment]
Wrong defect!
Complete
