### ISSUE TITLE
zOSBatchManager does not allow archiving to a set folder

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#463]
dev.galasa.zosbatch.zosmf.manager.internal.ZosmfZosBatchJobImpl.saveOutputToResultsArchive() does not allow other managers to choose the storedartifact folder into which to archive the jobs.   The test and the managers should have the choice.

**Comment by Michael-Baylis** [comment]
once complete,  change com.ibm.cics.galasa.sem.internal.SemManagerImpl.retrieveOutput(String, List<IZosBatchJob>)

**Comment by DavidXRoberts** [comment]
Done for batch.
Same changes required for File

**Comment by DavidXRoberts** [comment]
I've noticed that batch is prefixing the supplied archive path with /zosBatchJobs.  Need to remove that

**Comment by DavidXRoberts** [comment]
Prefix removed

**Comment by DavidXRoberts** [comment]
Complete. reassigning to @Michael-Baylis re above comment

**Comment by Michael-Baylis** [comment]
Brill,  working perfectly,  thank you
