### ISSUE TITLE
Secure the Ecosystem

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#480]
Secure the Ecosystem by enabling security on all the stores.
Provide a means to authenticate and receive short/long term JWTs
Authentication is required from web/eclipse/vscode/automation
Enable https
Provide API Keys
OpenLDAP default service
Roles
OIDC?
API authorisation

**Comment by techcobweb** [comment]
duplicate of epic #1474 and related security epics.
