### ISSUE TITLE
Support for Galasa plugin in IBM Z Open Development (ZOD) V2.0.0

### ISSUE THREAD

**Issue by russell-bonner** [galasa-dev/projectmanagement#51]
Installing Galasa Eclipse plugin into IBM Z Open Development (ZOD) V2.0.0, raises following installation messages, with a failure resulting:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Galasa zOS Feature 0.3.0 (dev.galasa.zos.feature.feature.group 0.3.0)
  Missing requirement: Galasa Framework 0.3.0 (dev.galasa.framework 0.3.0) requires 'package org.apache.commons.lang3 [3.1.0,4.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Galasa Eclipse 0.3.0 (dev.galasa.eclipse 0.3.0)
    To: bundle dev.galasa.framework 0.0.0
  Cannot satisfy dependency:
    From: Galasa zOS Feature 0.3.0 (dev.galasa.zos.feature.feature.group 0.3.0)
    To: dev.galasa.zos3270.ui [0.3.0]
  Cannot satisfy dependency:
    From: Galasa zOS 3270 UI 0.3.0 (dev.galasa.zos3270.ui 0.3.0)
    To: package dev.galasa.eclipse 0.0.0

**Comment by adamcoulthard** [comment]
I've got a similar issue, when I installed it into eclipse I got the following error:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Galasa zOS Feature 0.3.0 (dev.galasa.zos.feature.feature.group 0.3.0)
  Missing requirement: Galasa Eclipse 0.3.1 (dev.galasa.eclipse 0.3.1) requires 'package org.eclipse.jetty.server 9.4.0' but it could not be found
```

**Comment by Michael-Baylis** [comment]
CICS and zOS Explorers are not really Java IDE environments, so therefore not really applicable for Galasa, so for the moment we are going to add a comment on the docs to say "do not use withing a Vanilla explorer instance".

Will probably look at IDz and ZOD in February.

**Comment by stewartfrancis** [comment]
Happy to help you take a look at why it won't install into z/OS Explorer or CICS Explorer if you like.  Probably some interaction between Installation Manager and how it handles missing dependencies in the target package group.  Or missing bits of IES on the update site if it's a p2 install, though I'd guess that Jetty would be there already

**Comment by GeraldMit** [comment]
ZOD has been off-market for a long time. This item should be closed.

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
