### ISSUE TITLE
z/OS Batch status needs a "not found" status

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#516]
The dev.galasa.zosbatch.IZosBatchJob.JobStatus enum needs a NOTFOUND status if the job was not found.

Needs to be set in dev.galasa.zosbatch.zosmf.manager.internal.ZosmfZosBatchJobImpl.ZosmfZosBatchJobImpl(IZosImage, IZosBatchJobname, String, ZosBatchJobcard) line 586+

Not sure what the implications are,  so didn't do it myself

**Comment by DavidXRoberts** [comment]
Complete
