### ISSUE TITLE
Expect no AID key returned, 7D returned instead

### ISSUE THREAD

**Issue by bigrichie3** [galasa-dev/projectmanagement#520]
we sent a x'F2' (Read Buffer command) and we expect x'60' (no AID byte ) as the first byte of data returned.  The emulator sent x'7D' in this case, so we failed the test.  The question is why did the new emulator choose to send x'7D' in the first byte instead of x'60'

**Comment by Michael-Baylis** [comment]
Found the following text, finally:-

Keyboard-restore bit. When set to 1, restores operation of (unlocks) the
keyboard. It also resets the AID byte.

so will reset the AID on keyboard reset

**Comment by Michael-Baylis** [comment]
Delivered
