### ISSUE TITLE
pod initialization of api server ignores locally loaded docker images and fails with ImagePullBackOff

### ISSUE THREAD

**Issue by SteamboatHarry** [galasa-dev/projectmanagement#522]
I'm setting up a Galasa ecosystem in k8s. In my working environment I don't have access to the internet and therefor I'm forced to use a work-around to load all the images I need locally on my servers. It seems if the pod initialization of the api server ignores the fact that there are images present locally and instead tries to pull the images from the internet. Because I don't have access this fails with ImagePullBackOff.
I would like to be able to configure the imagePullPolicy (e.g. in the YAML to set up a Galasa ecosystem) so I can set this policy to IfNotPresent. This way it would look for local images first.

**Comment by SteamboatHarry** [comment]
BTW... I've looked at the go code and saw that PullAlways is used not only in apiserver.go, but also in other code (like resmon.go, metrics.go, simbanks.go). So I probably hit the same issue when going further. Therefor it would be nice to consider these also when solving the issue :-)

**Comment by SteamboatHarry** [comment]
As a short term solution I can continue fine if all the PullAlways would be changed to PullIfNotPresent. On a longer term I think it would be nice if it's possible to configure the imagePullPolicy yourself

**Comment by Jimbo4794** [comment]
Hi Harry. I have made the changes so you can define your own pull policy as part of the ecosystem YAML, to all the pods in the operator. This now has the default of IFNotPresent if you dont define one.

You will need to re-apply the new CRD for the ecosystem and pull the new operator (0.13.0-SNAPSHOT), which is building now. Ill comment on this when ready.

**Comment by Jimbo4794** [comment]
Should now be live

**Comment by SteamboatHarry** [comment]
I'm getting further, so this works! Thank you!
