### ISSUE TITLE
org.openqa.selenium.support.ui Selenium package not exported during mvn deploy

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#523]
When running tests using Jenkins in a Galasa ecosystem I get an error installing my test bundle from the OBR repository:

"dev.galasa.framework.spi.FrameworkException: Unable to install bundle "com.ibm.cics.cip.bank.tests" from OBR repository" 

due to the missing org.openqa.selenium.support.ui package:

ERROR d.g.f.BundleManagement - Unsatisfied requirement: package:(&(package=org.openqa.selenium.support.ui))

**Comment by Jimbo4794** [comment]
Completed and merged
