### ISSUE TITLE
Emulator sending 798 bytes when PA2 pressed instead of 1 byte.

### ISSUE THREAD

**Issue by bigrichie3** [galasa-dev/projectmanagement#530]
Mike has resolved a couple of issues with the emulator and it appears we hit one more snag.

Per one of my developers:

_After applying the latest JAT fix and the fix to the test case that we discussed this morning, it is getting farther, but it has now hit another problem.

In this problem, the test case does this:

When PA2 is pressed, just the AID byte (x'6E') should be sent to the application, so the test case expects a Received byte count of 1, instead, it gets 798 bytes._

I will forward his screen shots/email to Mike and Will. Please let me know if there is anything else you need.

**Comment by Michael-Baylis** [comment]
Galasa 3270 Manager updated,  now in JAT dev and prod streams
