### ISSUE TITLE
Implement Docker volumes into the Docker Manager

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#533]

**Comment by ArpanaKulenur** [comment]
@Jimbo4794 any update on when will it be available?

**Comment by Jimbo4794** [comment]
This work is in the same Docker Config PR as i mentioned in #545 : https://github.com/galasa-dev/managers/pull/404

**Comment by Jimbo4794** [comment]
Merged and in SNAPSHOT build
