### ISSUE TITLE
Galasa Jenkins Core Plugin link invalid

### ISSUE THREAD

**Issue by MN-Mike** [galasa-dev/projectmanagement#544]
In the Docker example Jenkins setup, the Galasa Jenkins Core Plugin has a link to https://galasa.dev/galasa-extensions-parent/dev.galasa.jenkins which gets an HTTP 404 error.  

I am looking to get the plugin and eventually get it approved for adding in our enterprise, that link will need to be populated with relevant information.

**Comment by Michael-Baylis** [comment]
@MN-Mike Where are you getting this link from,  as it is totally wrong.

**Comment by MN-Mike** [comment]
In the Jenkins setup in the sample Docker installation, when I look at the Jenkins installed Plugins (http://localhost:8082/pluginManager/installed) and click on the "Galasa Jenkins Core Plugin"  0.9.0 link, it goes to that 404 page.  https://galasa.dev/galasa-extensions-parent/dev.galasa.jenkins

 If I click on other links on that page (like the git link) it takes me to an information page that describes the client and how it is used.

**Comment by Michael-Baylis** [comment]
We will be removing the Jenkins plugin from the Galasa distribution as the galasactl cli will take over as it is more generic.
