### ISSUE TITLE
Implement passing environment variables to docker run in Docker Manager

### ISSUE THREAD

**Issue by ArpanaKulenur** [galasa-dev/projectmanagement#545]

**Comment by ArpanaKulenur** [comment]
@Jimbo4794  any update on when will it be available?
This is will be our basic requirement as we cannot start ctg container without passing env variable LICENSE_ACCEPT=true.

**Comment by Jimbo4794** [comment]
A pull request is under review for this work at the moment. If you want to see all the updates: https://github.com/galasa-dev/managers/pull/404

May have to have further changes after review but shouldnt be much longer

**Comment by Jimbo4794** [comment]
The changes are now in the SNAPSHOT release. To start a container with custom config a new annotation is required. Have a look at the IVT as an example: https://github.com/galasa-dev/managers/blob/master/galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.docker.manager.ivt/src/main/java/dev/galasa/docker/manager/ivt/DockerManagerIVT.java

**Comment by Jimbo4794** [comment]
Merged and in the SNAPSHOT build
