### ISSUE TITLE
Implement @ContinueOnTestFailure annotation to continue test execution even if a Testcase fails

### ISSUE THREAD

**Issue by ArpanaKulenur** [galasa-dev/projectmanagement#546]

**Comment by Michael-Baylis** [comment]
@ContinueOnTestFailure is now available in 0.14.0-SNAPSHOT.

You can switch the same functionality on globally using CPS property

framework.continue.on.test.failure=true

so you dont need the annotation in the class.

Will be available in release 0.14.0
