### ISSUE TITLE
NPE during run using 3270 term to interact with IMS transaction screens

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#552]
During our test run we intermittently (at least 50%) get an NPE during the test using the terminal to interact with IMS screens.

06/01/2021 15:11:18.304 DEBUG d.g.z.s.Zos3270TerminalImpl - SENDING, CLEAR to 3270 terminal term1,  updateId=term1-80
=|                                                                                |
^|^
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
=|                                                                                |
06/01/2021 15:11:18.306 INFO  d.g.f.GenericMethodWrapper - Ending
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method dev.galasa.genapp.tests.ims.IMSTMSupport#startRecordingIVTCV,type=Test
----------------------- ****************************************************************************************************
java.lang.NullPointerException
	at dev.galasa.zos3270.internal.comms.Network.sendDatastream(Network.java:327)
	at dev.galasa.zos3270.internal.comms.Network.sendDatastream(Network.java:315)
	at dev.galasa.zos3270.spi.Terminal.clear(Terminal.java:214)
	at dev.galasa.genapp.tests.ims.IMSTMSupport.startRecordingIVTCV(IMSTMSupport.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:81)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:56)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:182)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:509)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:481)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:441)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:414)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:104)
06/01/2021 15:11:18.306 INFO  d.g.f.TestClassWrapper - Ending

**Comment by Michael-Baylis** [comment]
@hbunchgithub What version are you running on?   current 14 snapshot,  Network is only 310 lines long!!!!

**Comment by hbunchgithub** [comment]
We were quite busy toward the end of last year and tried to upgrade to 13 but were not successful. In the interest of completing work we stayed on 0.9. Both locally in the dev env and on the Eco.
![image](https://user-images.githubusercontent.com/77065775/103894203-93e0f780-50bc-11eb-9869-93a1a33f278f.png)

**Comment by hbunchgithub** [comment]
Can we upgrade the Eco by itself (Not changing the local env) , by just changing all the versions in the config yaml to 13, 0.13.0? Or must the local env and the Eco always be at the same level?

**Comment by hbunchgithub** [comment]
Stopped and removed the running containers.
Updated the config.yaml
![image](https://user-images.githubusercontent.com/77065775/103929088-be49a980-50ea-11eb-9513-7401d2869a15.png)

[root@wazi-vtp-galasa-ecoystem1 /]# docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.14.0-SNAPSHOT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Using the following configuration:-
!!dev.galasa.docker.operator.config.EcosystemConfiguration
api:
  extraBundles: dev.galasa.cps.etcd,dev.galasa.ras.couchdb
  image: galasa-boot-embedded-amd64
  port: 8080
cps:
  image: quay.io/coreos/etcd
  port: 2379
  version: v3.4.9
engineController:
  controllerImage: galasa-boot-embedded-amd64
  controllerVersion: 0.14.0-SNAPSHOT
  engineImage: galasa-boot-embedded-amd64
  engineVersion: 0.14.0-SNAPSHOT
  maxEngines: 2
galasaRegistry: docker.galasa.dev
hostname: wazi-vtp-galasa-ecoystem1.fyre.ibm.com
jenkins:
  image: jenkins/jenkins
  port: 8082
  version: '2.243'
metrics:
  image: galasa-boot-embedded-amd64
  port: 9010
nexus:
  image: sonatype/nexus3
  port: 8081
  version: 3.24.0
ras:
  image: couchdb
  port: 5984
  version: 2.3.1
resourceManagement:
  image: galasa-boot-embedded-amd64
simplatform:
  databasePort: 2027
  image: galasa-boot-embedded-amd64
  telnetPort: 2023
  webservicePort: 2080
  zosmfPort: 2040
version: 0.14.0-SNAPSHOT

CPS container status is changing, stopping ENGINE
Defining the CPS container
Defining the RAS container
Pulling image 'docker.galasa.dev/galasa-boot-embedded-amd64:0.14.0-SNAPSHOT'
Defining the API container
Defining the RESMAN container
Defining the METRICS container
Defining the ENGINE container
Defining the Nexus container
Defining the Jenkins container
Defining the SIMPLATFORM container
CPS Container is down, requires start up
Starting CPS container
CPS container is up
RAS Container is down, requires start up
Starting RAS container
RAS container is up
API Container is down, requires start up
Starting API container
API container is up
RESMAN Container is down, requires start up
Starting RESMAN container
RESMAN container is up
METRICS Container is down, requires start up
Starting METRICS container
METRICS container is up
ENGINE Container is down, requires start up
Starting ENGINE container
ENGINE container is up
Nexus Container is down, requires start up
Starting Nexus container
Nexus container is up
Jenkins Container is down, requires start up
Starting Jenkins container
Jenkins container is up
SIMPLATFORM Container is down, requires start up
Starting SIMPLATFORM container
SIMPLATFORM container is up
Setting CPS property 'framework.test.stream.SIMBANK.obr' with 'mvn:dev.galasa/dev.galasa.simbank.obr/0.14.0-SNAPSHOT/obr'
Setting CPS property 'zosmf.image.SIMBANK.servers' with 'SIMBANK'
Setting CPS property 'zosmf.server.SIMBANK.image' with 'SIMBANK'
Initial start of the Ecosystem is complete
Shutdown request received

**Comment by nathandanielcassata** [comment]
Hi @Michael-Baylis,
Is there a galasa-bom 14-snapshot available that the Galasa tests can use? I was able to grab version 0.13.0 but it would be nice to have matching test and ecosystem versions.

This is the error I saw when I updated the galasa-bom to 0.14.0-SNAPSHOT and ran a `mvn clean install`
```
❯ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact dev.galasa:galasa-bom:pom:0.14.0-SNAPSHOT @ line 80, column 16
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa:jar is missing. @ line 92, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.framework:jar is missing. @ line 97, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.core.manager:jar is missing. @ line 102, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.zos.manager:jar is missing. @ line 107, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.zos3270.manager:jar is missing. @ line 112, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.http.manager:jar is missing. @ line 117, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.artifact.manager:jar is missing. @ line 122, column 15
[ERROR] 'dependencies.dependency.version' for dev.galasa:dev.galasa.docker.manager:jar is missing. @ line 127, column 15
[ERROR] 'dependencies.dependency.version' for commons-logging:commons-logging:jar is missing. @ line 132, column 15
[ERROR] 'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 137, column 15
```

**Comment by hbunchgithub** [comment]
NPE not seen but intermittently this appears in the same test sequence of terminal interaction:

**Comment by hbunchgithub** [comment]
Version 14-SNAPSHOT seemed to resolve the NPE's closing issue.

**Comment by Michael-Baylis** [comment]
Wow,   that was easy for me!!!!
