### ISSUE TITLE
Design and implement the Java, JVM Server, Liberty, zOS Liberty, CICS * Managers

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#559]
Completely redesign the JAT Managers that support Java and Liberty for all platforms, including CICS and zOS.

The Managers should be written in the way we want them in Galasa,  not the way they evolved in JAT.

These Managers will be public.

**Comment by DavidXRoberts** [comment]
@Michael-Baylis @hobbit1983 
Here’s the structure that I’m working on. It’s incomplete, but I want to check I’m not heading off in the wrong direction. Please let me have your comments.

**CICS Manager**
New Interfaces:
- `dev.galasa.cicsts.cicsresource.ICicsResourceManager`
	create CICS resource object, specifically JVM server (`IJvmserver/ILibertyJvmserver`) 
- `dev.galasa.cicsts.cicsresource.ICicsResource`
	set/get RDO resource attributes/build/install/delete (via CEDA)
	enable/waitForEnable/disable/waitForDisable/discard etc (via CEMT)
- `dev.galasa.cicsts.cicsresource.IJvmserver extends ICicsResource`
	set/get JVM server specific RDO resource attributes (via CEDA)
	JVM server specific set/get attributes, phaseout/purge etc (vis CEMT)
	set/get JVM profile (`IJvmprofile`)
	build – create JVM profile, create RDO resource, install, enable
	set/get work dir/log files/checkpoint logs/search message in log/manage logs etc
- `dev.galasa.cicsts.cicsresource.ILibertyJvmserver extends IJvmserver`
	set/get Liberty JVM server specific properties in JVM profile
	set/get Liberty server object (`IZosLibertyServer`)
- `dev.galasa.cicsts.cicsresource.IJvmprofile`
	set/get properties
	build profile
	
**New CICS Resource Manager**
Implements `ICicsResourceManager` and `ICicsResource`

**New CICS JVM server Resource Manager**
Implements `IJvmserver`, `ILibertyJvmserver `and `IJvmprofile`

**New zOS Liberty server Manager**
can be used stand alone
specific zOS Liberty server function
Interface:
- `dev.galasa.zosliberty.manager.IZosLibertyServer extends ILibertyServer`

**New zOS Connect Manager**
can be used stand alone
specific zOS Connect server function
Interface:
- `dev.galasa.zosconnect.manager.IZosConnectServer extends IZosLibertyServer`

**New Liberty server Manager**
can be used stand alone
provides Liberty server function
Interface:
- `dev.galasa.liberty.manager.ILibertyServer`
