### ISSUE TITLE
The dropdown on the page number of the run results table is not working.

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#562]
Click on the dropdown and nothing happens.

**Comment by CJMeek** [comment]
https://github.com/IBM/carbon-components-angular/issues/1709

**Comment by jadecarino** [comment]
Hi Mike @Michael-Baylis this issue looks to have been resolved by Carbon now, I've checked in Chrome Firefox and Safari and the dropdown looks and works fine now. Happy to close this?
