### ISSUE TITLE
In Eclipse, View Galasa Results of Eco run, Run Overview, Queued, Started, Finished, run data incorrect (showing current local times)

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#564]
Nightly run at 1:30am on ECO results when viewed locally in eclipse Galasa Results show times that run is viewed:

![image](https://user-images.githubusercontent.com/77065775/105492259-aa26b000-5c85-11eb-8dba-8150ca8da51e.png)

Close the run tab reopen it you get the new current time stamps in the view
![image](https://user-images.githubusercontent.com/77065775/105492388-e22df300-5c85-11eb-898e-6b598825a248.png)

**Comment by Michael-Baylis** [comment]
Wow,   that can't be right.   will add to queue

**Comment by Michael-Baylis** [comment]
Stupid coding error.  Corrected.
Available in 0.14.0-SNAPSHOT now https://p2snapshot.galasa.dev/,  will be in 0.14.0 release
