### ISSUE TITLE
dev.galasa.zos3270.internal.comms.NetworkThread.readByte - Terminal has been disconnected due to A TIMEMARK request was not answered by the client in the specified time indicating a lost connection.

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#567]
During running of the ZVTP testclass for IMS using the Galasa 3270 mgr the client is disconnected by the host for A TIMEMARK request was not answered by the client in the specified time indicating a lost connection.

During the run of this test class:
IMS Control Region IMSOCR::IVPPRT1 log indicates LOSTTERM on NODE NTCP=0042:
/START PROGRAM DFSIVP34 NODE NTCP0042 USER BZUBVT0 .
.DFS058I 01.37.38 START COMMAND COMPLETED NODE NTCP0042 USER BZUBVT0 .
/START TRANS IVTCB NODE NTCP0042 USER BZUBVT0 .
.DFS058I 01.37.41 START COMMAND COMPLETED NODE NTCP0042 USER BZUBVT0 .
/DIS TRANS IVTCB NODE NTCP0042 USER BZUBVT0 .
.    TRAN     CLS ENQCT   QCT   LCT  PLCT CP NP LP SEGSZ SEGNO PARLM    RC  NODE NTCP0042 USER BZUBVT0 .
    IVTCB      1    10     0 65535 65535  1  1  1     0     0  NONE     0  NODE NTCP0042 USER BZUBVT0 .
        PSBNAME. DFSIVP34 NODE NTCP0042 USER BZUBVT0 .
    *21027/013745* NODE NTCP0042 USER BZUBVT0 .
DFS970I  1.37.56 UNEXPECTED  STATUS   ,**NODE NTCP0042**,USER BZUBVT0 ,******,RC=00
,FDB2=00,**LOSTERM=14**,SENSE=00000000,REASON=00.

SDSF Log indicates
NODE NTCP0042 indicates Timemark Error:
![image](https://user-images.githubusercontent.com/77065775/105994504-b2ac2b80-6075-11eb-9f53-c655866acb93.png)

[LOSTERM.txt](https://github.com/galasa-dev/projectmanagement/files/5880393/LOSTERM.txt)

**Comment by Michael-Baylis** [comment]
Wow.   Don't believe I have implemented timemark into the client.    Will have to have a look

**Comment by Michael-Baylis** [comment]
but atleast that explains why the connection is being dropped

**Comment by Michael-Baylis** [comment]
@hbunchgithub  i have discovered the following code:-

```
private void doIacDoTimingMark(InputStream messageStream) throws NetworkException {
     logger.trace("timing received");
     this.network.sendIac(new byte[] {IAC, DONT, TIMING_MARK});
}
```

Would you please rerun you test with TRACE enabled to ensure you are seeing the "timing received" logger message, to ensure we are in the right place.

In the meantime,  I will look up the telnet protocols to see what I should be responding with.

**Comment by Michael-Baylis** [comment]
@hbunchgithub change is up at 0.15.0-SNAPSHOT and 0.15.0-NIGHTLY,   so would you please try your IMS test again.

**Comment by hbunchgithub** [comment]
Config.yaml is has been set to 0.15.0-SNAPSHOT since v14 was released. Stopped all the containers and reissued docker run command to start everything back up.  We stopped seeing the timemark related error a couple weeks back and are unsure why the comm changed to the client. 
Will perform some runs, but were not sure a timemark request will ever be issued.

**Comment by hbunchgithub** [comment]
Test run is successful. Will monitor:
![image](https://user-images.githubusercontent.com/77065775/108115423-1c619900-7068-11eb-98e3-814d70a6e91e.png)

**Comment by Michael-Baylis** [comment]
Ok,   I will close the issue.   If the problem reoccurs,  please comment and I will reopen

**Comment by hbunchgithub** [comment]
Seen again today:
