### ISSUE TITLE
Implement leaveRunning annotation with DockerContainer

### ISSUE THREAD

**Issue by ArpanaKulenur** [galasa-dev/projectmanagement#582]
While debugging testcases, it is difficult to debug without having the running container. So its good to have @leaveRunning tag with Docker Container so that it will not be removed at the end of execution.

**Comment by Michael-Baylis** [comment]
Sorry,  but this will massively complicate the automatic clean up of the docker engine.

The way you would normal do this is run the test locally,   put a break point in an @AfterClass,  run the test until you hit the break point and then go and do your investigation.

**Comment by Michael-Baylis** [comment]
once you have finished the investigation,  allow the test to continue and allow the resources to be cleaned up

**Comment by Michael-Baylis** [comment]
Been open for a while and no return comment,  so closing
