### ISSUE TITLE
Need support for Selenium Manager webdriver and browsers on Docker Eco Env

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#584]
Per Mike, Selenium Manager is only supported locally. Thus when running on Eco with same setup, driver is not found from the Galasa container engine.

ZVTP has selenium manager working in Eclipse, on Eco host RHEL 8 we have deployed Chrome and the chromedriver:
[root@wazi-vtp-galasa-ecoystem1 bin]# pwd
/usr/bin
[root@wazi-vtp-galasa-ecoystem1 bin]# ls -ltr chrome*
-rwxr-xr-x 1 root root 11459768 Feb  9 09:34 chromedriver
Updated CPS:
# etcdctl get --prefix selenium.
selenium.instance.PRIMARY.chrome.path
/usr/bin/chromedriver
selenium.instance.PRIMARY.web.driver
CHROME
But when that test class runs it throws:
Caused by: java.lang.IllegalStateException: The driver executable does not exist: /usr/bin/chromedriver

**Comment by hbunchgithub** [comment]
@Michael-Baylis I am sure you have tests in the works for your new Galasa WebUI and we have a new VTP feature for a viewer that will display data in a browser. Is there a milestone target for support of Selenium Mgr in the Eco?

**Comment by Jimbo4794** [comment]
Closing as enhancement merged
