### ISSUE TITLE
Please review Landing Page and raise issues

### ISSUE THREAD

**Issue by DianaSlepikaite** [galasa-dev/projectmanagement#590]
Please review Galasa Landing page and Landing page only, and raise any issues you find separately no matter how small the issues are.
http://cicsk8sm.hursley.ibm.com:32612/

**Comment by Michael-Baylis** [comment]
I have raised an issue for Caroline to replace the latin text with proper words.

This issue is the first expermintal way of review web pages,  so shall see how it goes.
