### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#592]
On my MacBook Pro with an external 4k screen the hamburger menu doesn't render well on Firefox, Safari or Vivaldi (Chrome) - the middle two bars are antialiased, the top & bottom are crisp
![image](https://user-images.githubusercontent.com/61017744/108235067-62d4f780-713d-11eb-8922-79035d4032be.png)

This page may be helpful https://github.com/carbon-design-system/carbon-icons-angular - I presume you're using a Carbon SVG icon at its native size (one from: 16, 20, 24, or 32, with no rescaling)

The hover state needs a little adjustment to the colour and possibly to layout in Firefox
![image](https://user-images.githubusercontent.com/61017744/108235141-78e2b800-713d-11eb-90fa-2e18277ea859.png)

- The background colour needs to be the same as the hover colour for the Galasa icon. (See Will's Sketch file where he's put the styleguide).
- Also, on my Firefox (85.0.2) but not on Safari or Vivaldi, the hover colour doesn't reach the top or bottom of the header bar?
![image](https://user-images.githubusercontent.com/61017744/108235273-93b52c80-713d-11eb-8027-825c962340d3.png)

(In terms of size (not colour), it correctly renders like this on Safari and Vivaldi)
![image](https://user-images.githubusercontent.com/61017744/108235361-a9c2ed00-713d-11eb-8375-e9648562a6d7.png)

In Will's Sketch style guide, he has specified a three bar hamburger menu, not four bar. Will will be able to supply the correct SVG icon for that, if he hasn't already done so.

On Firefox (but not Safari, or Vivaldi), the flyout menu is a few pixels above where it should be
![image](https://user-images.githubusercontent.com/61017744/108235587-dd057c00-713d-11eb-8d10-5ba455a0f14c.png)
And it would be useful to replicate the button links (View tests, Check status, Configure system & Submit [tests]) in the flyout) -  I realise this is just a point in time issue, but if it's easy it would be useful

**Comment by DianaSlepikaite** [comment]
@lubelg concerning the hamburger it is preset in carbon, so what I can do to change the svg of the hamburger is to get rid of carbon hamburger and make a hamburger on my own if thats ok @Michael-Baylis

**Comment by Michael-Baylis** [comment]
@DianaSlepikaite yep,   ask @willb-01 for the svg for the icon.   If carbon doesn't have the 3 line version

**Comment by jadecarino** [comment]
@lubelg re the button links in the Hamburger menu (View tests, Check status, Configure system & Submit [tests] as you mentioned), would those options come as a sub-option for Dashboard when you click a dropdown for example or would they be just separate items? Also I delivered code for the Hamburger yesterday evening so you should be able to see the actual items with links now not the word 'Link', when did you take the bottom screenshot?

**Comment by jadecarino** [comment]
@lubelg The spec document says these should be the options included in the Hamburger can you confirm if this is still correct please? Dashboard, CPS properties, Schedule tests, Running tests, Previously run tests

**Comment by lubelg** [comment]
@jadecarino The images were from yesterday afternoon, just before the time I posted the issue (but may have been from an unrefreshed page from earlier in the day)

The main purpose of the hamburger menu is to navigate between these four modes and so the 'getting started' page is really just an in-your-face equivalent, to make it easier for people first arriving on the WebUI. Thereafter, they'd use the hamburger menu. So the hamburger menu should contain as first level (not indented) items, in the order shown below.

1. Getting Started - 
2. View tests - changes mode to the pages Jade's implementing
3. Check status - changes mode to view currently running tests (not yet designed)
4. Submit tests - changes mode to allow test scheduling (not yet designed)
5. Configure system -  only shown for users with admin authority - changes mode to CPS property editor pages
also (but I'll get back to you on these):
6. Edit profile
7. Read docs
8. Get support

**Comment by jadecarino** [comment]
@lubelg Okay I didn't see the time the issue was opened, you wouldn't have had the code with the items yet so that's fine. I will add the rest of the items you've listed there, thanks Greg. The items that don't lead anywhere currently will just have no route for now. Will work on styling icon and hover also, thanks.

**Comment by lubelg** [comment]
@jadecarino After your question and having played with the updated code, I reviewed what I'd put in the [Functional spec](https://ibm.box.com/s/i8h9992munr1gkdsx3veol24956ht9ml), to bring it in line with what we discussed. There are three additional (not super urgent) tweaks that I think will improve the hamburger menu

1. put a blank line or short ruled line between the first main items (Getting started down to Configure system) and the secondary items (profile, help, support)
2. Change the Edit profile to profile, Read docs to Help & Get support to Support (In the menu, not the tiles)
3. When any item is selected from the menu, automatically close the menu away

**Comment by jadecarino** [comment]
@DianaSlepikaite ^

**Comment by DianaSlepikaite** [comment]
@lubelg I believe this is fixed, can we close the issue?

**Comment by lubelg** [comment]
@DianaSlepikaite 
I have raised separate issues for the Firefox problems (flyout positioning and the highlight size/positioning for hamburger menu and Galasa icon), so I think this issue can be closed and the Firefox issues can be tracked independently
