### ISSUE TITLE
Dashboard - or not!

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#593]
This page isn't a dashboard and is more of a 'quick start' or 'Getting started' page - (We may want a dashboard too but we'd need to design a dashboard as a separate exercise, with a little research into user needs)

In order to fix this, please can we ditch the title in the header bar and instead increase the size of the 'Getting started' title on the left end of the grey section to 1.75rem (details of the rem/px implications in Will's styleguide). This will give this title the appearance of being higher in the title hierarchy and therefore promote it to be the page title

**Comment by DianaSlepikaite** [comment]
@lubelg should i then ignore the design parts of this? Because in @willb-01 design the title exist on the header and its called dashboard and get started is the size as it is right now.

**Comment by Michael-Baylis** [comment]
@DianaSlepikaite In this case,  yes,  ignore the design for this one.   This is a landing page, not a dashboard page, yet.

**Comment by willb-01** [comment]
@DianaSlepikaite as @Michael-Baylis said ignore design and remove title from header.

**Comment by Michael-Baylis** [comment]
@jadecarino please change the breadcrumb to say "Home" instead of "Dashboard"

**Comment by DianaSlepikaite** [comment]
@Michael-Baylis @lubelg can I close this issue because I believe it has been resolved?

**Comment by lubelg** [comment]
@DianaSlepikaite @Michael-Baylis I believe this can be closed now
