### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#598]
The following must be _Open Sans_
https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans&sidebar.open=true&preview.text_type=custom
- **Body text**
- **Button text** & 
- **Text links**

All **headings** are _Work Sans_
https://fonts.google.com/specimen/Work+Sans?selection.family=Open+Sans&sidebar.open=true&preview.text_type=custom&query=work+sans

**Comment by Michael-Baylis** [comment]
The fonts should be downloaded and included in the assests folder,  so access to the internet is not required

**Comment by jadecarino** [comment]
@lubelg Hi Greg, please can you let me know if the elements below count as headings or body so I can apply the correct Work or Open Sans to it?
The label of the toolbar: 
<img width="265" alt="Screenshot 2021-02-18 at 12 03 59" src="https://user-images.githubusercontent.com/65225359/108354594-92d5d680-71e1-11eb-9330-6dc709e4e65a.png">
The header row of data tables:
<img width="407" alt="Screenshot 2021-02-18 at 12 04 15" src="https://user-images.githubusercontent.com/65225359/108354625-9b2e1180-71e1-11eb-8dad-6eac2fff31ed.png">
The attribute, so the word 'Result' in Run Overview?
<img width="272" alt="Screenshot 2021-02-18 at 12 04 43" src="https://user-images.githubusercontent.com/65225359/108354677-b13bd200-71e1-11eb-8f41-c29484b090bd.png">

**Comment by willb-01** [comment]
@jadecarino and @DianaSlepikaite 

The fonts used for Galasa are Work Sans and Open Sans both open source fonts available at: https://fonts.google.com

https://fonts.google.com/specimen/Work+Sans?preview.text_type=custom#standard-styles
https://fonts.google.com/specimen/Open+Sans?preview.text_type=custom&query=open+sans

If you install these on your system you will be able to tell what font is used within the designs and where.

I have downloaded as Mike asked and saved here:
https://ibm.box.com/s/l0gbg0g742nbl6b9uzav82h8i04ri2ok

Generally rule is Work Sans Semi Bold for all headings. Anything else is Open Sans. 

@jadecarino to answer above yes both are set in Work Sans Semibold.

Please be sure to use the latest Sketch file galasa-web-ui-v1-20210218 which uses Work Sans Semibold
https://ibm.box.com/s/wab2cxishru2lv3knsbir5xnnzt5om96

**Comment by jadecarino** [comment]
@lubelg @willb-01 Hi both, I amended the fonts across the UI yesterday and have delivered to Prod, please can you review again?

**Comment by Michael-Baylis** [comment]
not sure I like the heading one,  seems a bit "much"

**Comment by willb-01** [comment]
Can you send me the link please @jadecarino

**Comment by lubelg** [comment]
@willb-01 http://cicsk8sm.hursley.ibm.com:32612/

**Comment by willb-01** [comment]
@jadecarino agree its too heavy. 

Try the next weight down which is 500 (Medium). If thats still too bold then drop down to 400 (Regular). 

Its strange though as galasa.dev is using 400 for large headings and 600 for smaller headings and doesn't look anywhere near as bold as its rendering currently on the tool your working on.

**Comment by willb-01** [comment]
Also @jadecarino Get started should have a lower case s i.e. Get started rather than Get Started :)

**Comment by willb-01** [comment]
Hi @jadecarino please can you do the following update:

Replace all instances of Work Sans for Open Sans. This should only effect the heading styles. Replace as follows:
Work Sans Regular  > Open Sans Regular
Work Sans Medium or Bold > Open Sans Semi bold

Please check the latest Sketch file.

Thanks

**Comment by jadecarino** [comment]
Hi @willb-01 I have actioned your comment and set all fonts to Open Sans, Regular or Bold, we'll continue to use these font faces going forward. Please review with @lubelg if you're happy with the fonts I will close this issue (please ignore Run Log of the Run Page as still in development so final styling has not been applied).
