### ISSUE TITLE
Increase contrast toggle button position

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#599]
_Increase contrast_ toggle button and its label should be:

- Label text & toggle centred verticaly 
- Toggle moved to the far right (minus the margin distance)
- The label text to the left of the toggle
- Toggle colour is blue, not dark grey
![image](https://user-images.githubusercontent.com/61017744/108243210-c105d880-7145-11eb-8a52-a059a4eec428.png)

**Comment by jadecarino** [comment]
@lubelg Hi Greg, is the footer / white bar containing the Increase Contrast toggle meant to be sticky ie should it be stuck to the bottom of the browser window and stay there if the user scrolls, or should it be always underneath the content?

**Comment by lubelg** [comment]
The footer bar is sticky and 48 px high, as per _components  footer with toggle / 01_ in the Symbols section of the Sketch file
This also shows the _Increase contrast_ toggle button & label position (RHS vertically centred )

**Comment by jadecarino** [comment]
As per the changes to the designs which now adhere to accessibility standards, we no longer need a high contrast mode so can remove the footer with the increase contrast toggle altogether, so I am closing this issue
