### ISSUE TITLE
Change 'Submit' to 'Schedule tests' on button

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#601]
Change _Submit_ to _Submit tests_ on button on the Submit tests tile

**Comment by lubelg** [comment]
On reflection, these titles and buttons should match what's in the hamburger menu

**Comment by jadecarino** [comment]
Hi @lubelg the button now says 'Schedule tests' so I'll close this issue. Caroline and I have been working together on content so have tweaked anywhere that didn't match. The Hamburger menu options now match the corresponding buttons on all of the Landing page tiles.
