### ISSUE TITLE
Is autogenned manager build pushing not just additions but also removals of files.

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#604]
When testing a search facility in the galasa website, more results than expected were returned. The same result got returned for example under zos file manager and z/os file manager. 

If you take a look at https://galasa.dev/sitemap.xml it prints out all the pages in the site. There seem to be two pages that are inaccessible from the managers page:
https://galasa.dev/docs/managers/z-os-file-manager
https://galasa.dev/docs/managers/zos-file-manager

These two are also returned:
https://galasa.dev/docs/managers/zos-file-zos-mf-manager
https://galasa.dev/docs/managers/z-os-file-zos-mf-manager

Is the automation pushing not just additions but also removals of files? If not, we might get results we don't want returned in a search. 
Raising as a bug in case.

**Comment by Michael-Baylis** [comment]
The generation program cannot detect fiels to be deleted,  so these will need to be manually deleted in github.   The whole autogenerated docs thing needs to reviewed and rebuilt, so will not fix it for the moment.
