### ISSUE TITLE
Broken link on CICS TS CECI Manager page

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#616]
On this page https://galasa.dev/docs/managers/cics-ts-ceci-manager
clicking on the Javadoc documentation for the manager here - link is broken.  It currently points to:
https://javadoc.galasa.dev/dev/galasa/cicsts/ceci/package-summary.html

**Comment by CaroMac** [comment]
Thank you, will update

**Comment by hobbit1983** [comment]
Thanks @CaroMac i've checked this and it's working now
