### ISSUE TITLE
Sort out the eclipse.plugin version qualifier so that it updates when there are changes to dependencies

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#617]
The current tycho plugin uses the git commit time of the eclipse plugin project to set the version qualifier.   But this does not change if there is a change to the galasa-boot.jar.   at the moment we have to make a dummy change to the pom.xml to ensure the version qualifier is bumped so eclipse installs it.
There has to be a better way.

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
