### ISSUE TITLE
coreManager.registerConfidentialText(cred.getPassword() is not masking for short IDs. 

### ISSUE THREAD

**Issue by MN-Mike** [galasa-dev/projectmanagement#618]
I was testing with a RACF ID that was 8 bytes long.  I recently switched to a 7 byte long ID and now the password is not getting masked.  The only change was updating the credential file to the new ID/Password. 

If there is a user error, please help be update my side, but I suspect this may be a new issue.

**Comment by hobbit1983** [comment]
Thanks Mike - we can take a look at recreating this problem locally.  Was the problem encountered when running the test locally?

**Comment by MN-Mike** [comment]
Yes, I saw the issue running locally,  I am having some concerns with my Docker setup so not sure about that yet.


Mike Baillargeon | Optum Technology
***@***.***D72223.B16C6630]
Senior Principal Engineer,  Director CICS Support
Technology Leadership Career Path
6150 Trenton Lane North, Plymouth, MN 55442
• (763) 337-8716
***@***.******@***.***>

**Comment by hobbit1983** [comment]
Thanks Mike - We've tried recreating locally with both a 8 character and 7 character user ID and in each instance we mask the  field correctly in the run log and in the terminals.  Can you confirm that you are using the same case in both the creds file and when it is entered on the screen?

This was on 0.14.0

**Comment by MN-Mike** [comment]
It was local testing, the only difference was changing between the two length of User IDs.

I am running 0.14.0 but the configuration is set to 0.13.0 in the POM.

                                  <lifecycleMappingMetadata>
                                         <pluginExecutions>
                                                <pluginExecution>
                                                       <pluginExecutionFilter>
                                                              <groupId>dev.galasa</groupId>
                                                              <artifactId>
                                                                     galasa-maven-plugin
                                                              </artifactId>
                                                              <versionRange>
                                                                     [0.13.0,)
                                                              </versionRange>
                                                              <goals>
                                                                     <goal>obrresources</goal>
                                                              </goals>
                                                       </pluginExecutionFilter>
                                                       <action>
                                                              <ignore></ignore>
                                                       </action>
                                                </pluginExecution>
                                         </pluginExecutions>
                                  </lifecycleMappingMetadata>


Mike Baillargeon | Optum Technology
***@***.***D7222B.3DE42920]
Senior Principal Engineer,  Director CICS Support
Technology Leadership Career Path
6150 Trenton Lane North, Plymouth, MN 55442
• (763) 337-8716
***@***.******@***.***>

**Comment by MN-Mike** [comment]
I updated the POM entry to 0.14.0 and it made no difference.


Mike Baillargeon | Optum Technology
***@***.***D7222B.664AB870]
Senior Principal Engineer,  Director CICS Support
Technology Leadership Career Path
6150 Trenton Lane North, Plymouth, MN 55442
• (763) 337-8716
***@***.******@***.***>

**Comment by MN-Mike** [comment]
We can setup a screen sharing session if you would like to observe the conditions.


Mike Baillargeon | Optum Technology
***@***.***D7222B.9BAFB240]
Senior Principal Engineer,  Director CICS Support
Technology Leadership Career Path
6150 Trenton Lane North, Plymouth, MN 55442
• (763) 337-8716
***@***.******@***.***>

**Comment by MN-Mike** [comment]
Update.  I think I have a clue.  The password had a "$" symbol in it and that may have been significant.  When I changed to a new password (after revoking (long story)). I see it is now working. The new password does not have the "$" in it.

**Comment by MN-Mike** [comment]
Note, in the etcdctl commands to populate the docker credentials, I need to enclose the password in single quotes to get a complete password retrieved. I did not have this issue with the credentials file and that is the testing that did not mask the password correctly (when the password had a "$").

The credentials based file is also now working with the new password (no "$").

**Comment by hobbit1983** [comment]
Hi Mike - I saw your update and concur - it does appear the $ is throwing out the masking - I'll take a look

**Comment by hobbit1983** [comment]
Got a CS to fix this.  Is the latest snapshot OK or would you like this against the current released version?

**Comment by MN-Mike** [comment]
I can wait for the next release to come out.  Now that I understand the cause, I will reset passwords to avoid the "$" until it is released.

**Comment by hobbit1983** [comment]
No worries.  This is now fixed in 0.15.0-SNAPSHOT
