### ISSUE TITLE
Test History - Inconsistent behaviour when dealing within invalid input data between date and time boxes

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#619]
Recreation Steps
1) Load the Test history page of the web UI
2)Enter the String FRED as a Start Date and press enter
3) Note the input FRED is removed, the default text DD/MM/YYYY is entered, the box turns red and the message Invalid appears at the bottom of the UI
4) Repeat step 2 with the Start time 
5) Note that the although the box turns red and the Invalid message appears the text FRED remains in the input box.

Both behaviours need to be consistent.  Either leave the invalid text in the box and mark it as invalid or remove it and don't mark the field as invalid

**Comment by jadecarino** [comment]
Actioned, time box cleared if value is invalid, code to be delivered

**Comment by jadecarino** [comment]
@hobbit1983 Hi Will I have just merged a PR to hopefully solve this issue (I wasn't able to link the PR and issue as different repos), please can you check this tomorrow and confirm if you're happy with the fix?

**Comment by hobbit1983** [comment]
Yes sure that sounds like a plan - will take a look
