### ISSUE TITLE
Test History - time field can be > 24:00 but this gives a weird time to the backend

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#620]
In the test history page enter a end date of 07/04/2021 and a end Time of 25:05.  The URL that gets created is:
http://cicsk8sm.hursley.ibm.com:32612/results?to=2021-04-08T00:05:00.000Z

note that this is the time has rolled over to the following day.  Ideally we should prevent times > 24 hrs from being entered as entering a time > 24 is changing the date field as well

**Comment by jadecarino** [comment]
Actioned code to be delivered

**Comment by jadecarino** [comment]
@hobbit1983 Hi Will I have just merged a PR to hopefully solve this issue (I wasn't able to link the PR and issue as different repos), please can you check this tomorrow and confirm if you're happy with the fix?

**Comment by hobbit1983** [comment]
Yup - of course - thanks for taking a look

**Comment by hobbit1983** [comment]
Yes now a date > 24 hrs returns an invalid response - thanks
