### ISSUE TITLE
Test History - Run Overview pages, the title gets 'stuck'

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#621]
Go to the test history page and note that there is no title on the page.  Click any of the tests that are available to go to the run details page and note that the page title changes to 'Run test detail / Overview'.

Clicking the back button of the browser will take you back to the test history page and keep the title 'Run test detail / Overview'.
Clicking the breadcrumb trail to go back to the test history page will change the title to 'Title'

Not sure if this is because the test history page doesn't set it's own title that it is persisting, but either way we need to have a consistent title for each page

**Comment by jadecarino** [comment]
Hi @DianaSlepikaite I believe this is to do with the Header Title Service you developed it seems to be working great when you switch from tab to tab on the Run Page but not clearing when you go back to the Results Page as described by Will above, please could you look into this?

**Comment by DianaSlepikaite** [comment]
It didn't work because the test history ts did not had the dynamic header code. Should be fine now

**Comment by hobbit1983** [comment]
Looks tonnes better - thanks
