### ISSUE TITLE
Test History - Start time can be later than the end time

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#622]
Bit self explanatory really - no tests are then listed

**Comment by jadecarino** [comment]
Hi Will @hobbit1983 I have delivered some code which now greys out all future dates in the calendar and flags future dates as Invalid if entered manually in the text box. The box will also flag as Invalid if a start time is entered that is before the end time, or vice versa, and then I have prevented this new 'backwards' time range from filtering the table, so you won't see an empty table anymore. I am unable to prevent the user from entering dates that are the wrong way round, but hopefully this makes it obvious when they have entered an Invalid time range. Please review this and close if you are happy?

**Comment by hobbit1983** [comment]
Hi Jade - just had a re-test of this area.  I can see that if I try to specify a start date that is > end date I see a Invalid message.  However this new logic needs a bit of refining.  
As you can see from the attached image.  I can specify a start date/time 1 hour before the end time, although I get correct results displayed in the table, I still see the invalid message displayed

![image](https://user-images.githubusercontent.com/23282299/114977756-20e7d980-9e80-11eb-82d3-60b628e03096.png)

**Comment by jadecarino** [comment]
Hi Will @hobbit1983 thanks for raising this, I realised I did not remove the Invalid message from one box if the other box corrected the issue. I have now fixed this, please review. Thanks.

**Comment by hobbit1983** [comment]
Yes that looks a lot better now.  I have retested and am now happy - thanks!
