### ISSUE TITLE
Test History - Time field doesn't get cleared when input is deleted 

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#623]
Filter Tests using these criteria:
Start Date: 01/04/2021
Start Time: 13:33
End Date 08/04/2021

Press enter and the following URL is generated:
http://cicsk8sm.hursley.ibm.com:32612/results?from=2021-04-01T12:33:00.000Z&to=2021-04-07T23:00:00.000Z
Nice work on knowing I am in BST and correcting to UTC!

However delete the start time value and change the end date to be the 07/04/2021 (in order to re-fire the logic) and the following URL is generated:
http://cicsk8sm.hursley.ibm.com:32612/results?from=2021-04-01T12:33:00.000Z&to=2021-04-06T23:00:00.000Z
Note that the start time (although it was deleted from the field) is still in the URL

A second point is the date field.  In the end date for the second example I have set 07/04/2021 and have entered nothing for the time.  However the code has picked 00:00 as the time, adjusted for BST, rolled it back 1 hour and I now have the date of 06/04/2021 which although I agree is only a small change means I could have tests being included or occluded that I didn't expect

**Comment by jadecarino** [comment]
Hi @hobbit1983 , I have fixed the issue where if you delete the time from the field it is removed from the URL and effectively reset. Re your second point, the Zulu timestamp in the URL will always be in UTC time as that is the timezone the API Server uses, so regardless of whether you input 00:00 or if it is empty (therefore defaults to 00:00), as we are currently in BST the URL will revert to 23:00 of the previous day and retrieve those runs from the API Server. This shouldn't affect the results you'll be expecting to see as even though for you you'd see an end time of ~midnight to the API the test finished at ~23:00. Are you happy or would you like me to look into this further?

**Comment by hobbit1983** [comment]
Hi Jade,  Yes I can see that the time now gets removed from the parameter string - that's great, I assume that you rolled the same change into the end time picker as well (although I haven't checked for that yet). 

As for the time rolling back - After thinking about it, I agree that this is the right behaviour.  The start / finish times displayed in the test history table are set to the local TZ so to the user it looks correct.  So no further work needed there
