### ISSUE TITLE
Dropdown controls are missing corner radius & bottom edge

### ISSUE THREAD

**Issue by lubelg** [galasa-dev/projectmanagement#628]
![image](https://user-images.githubusercontent.com/61017744/114024950-84647c80-986c-11eb-8eb7-5a182d2fd2cc.png)

This is in both Firefox (86.0.1 (64-bit)) and Safari (Version 14.0.3 (16610.4.3.1.7)) on Mac Big Sur

**Comment by Michael-Baylis** [comment]
The results page is not available for review yet.   Please do not raise issues for this page
