### ISSUE TITLE
Extend the Open Stack Manager to provide Firewall support

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#641]
Extend the Open Stack Manager to provide the ability to set firewall rules.

We need the ability to create OS instances that do not have access to the internet.  ie,  set the firewall rules so an instance only has access to 9.x.x.x and 10.x.x.x.

The actual rules will need to be configured by annotations,   jsut don't know how.

**Comment by Jimbo4794** [comment]
Work completed and merged with PR 471 (managers)
