### ISSUE TITLE
Documentation for installing the MVP Galasa Distribution

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#655]
Produce the documentation that describes how to install the MVP Galasa Distribution which needs to include the following:-

1. Unload of the zip
1. Change gradle settings to point to the local repo
1. How to install the Galasa plugin from the local directory
1. Test using the simbank gradle examples
1. How to find the local directory version of the documentation
1. How to load the docker images of the docs and resources
1. How to run the docker images of the docs and resources
1. How to configure gradle to load from the docker images
1. How to install the Galasa plugin from the docker images

**Comment by CaroMac** [comment]
https://deploy-preview-284--galasa.netlify.app/docs/getting-started/installing
https://deploy-preview-284--galasa.netlify.app/docs/getting-started/simbank
https://deploy-preview-284--galasa.netlify.app/docs/running-simbank-tests

Topics updated after working with Matt. Now in CiP with Daniella.

**Comment by CaroMac** [comment]
Need to understand how the doc will be packaged with the Galasa zip file to document point 5 I think.
