### ISSUE TITLE
Produce standalone version of the galasa.dev documentation site

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#656]
For the closed network solutions we need standalone versions of the galasa.dev documentation.   Specifically we need:-

1. A version that can run from a directory of the laptop,  point the browser at the index.html and all the docs are available
2. A docker image running something to present the documentation to the browser from the docker container.

**Comment by CaroMac** [comment]
@ind1go has been working on this and has provided a worklow and jar for review in the Galasa Slack channel.

**Comment by Michael-Baylis** [comment]
Bed has produced a jar and works perfectly inside the mvp zip
