### ISSUE TITLE
Issue with new line character with streamAsString method

### ISSUE THREAD

**Issue by james-ashman** [galasa-dev/projectmanagement#663]
streamAsString is adding a new line character after the actual content it is reading. 

I noticed that a HelloWorld.txt file containing the single line "Hello World" was being stored as "Hello World\n" when using streamAsString.

**Comment by Michael-Baylis** [comment]
oo thats not good.  will look into it.      which streamAsString are you referring to,  ie the class/interface

**Comment by hobbit1983** [comment]
Issue in BundleResourceImpl. We loop through the inputStream and for each line we append the line to a StringBuilder followed by a new line.  Thus the last line read will always be followed by a new line.

**Comment by Michael-Baylis** [comment]
its using bufferedreader? oops

**Comment by hobbit1983** [comment]
Fixed in 0.15.0-SNAPSHOT
