### ISSUE TITLE
Issue with coreManager.registerConfidentialText not censoring run log 

### ISSUE THREAD

**Issue by james-ashman** [galasa-dev/projectmanagement#664]
coreManager.registerConfidentialText is allowing both the run log and console to display the confidential text set by the method. I tested this by storing the string 'World' as confidential text and logging the String 'Hello World'. Upon running the test the text 'Hello World' was visible in both the run log and console.

**Comment by hobbit1983** [comment]
The expected behaviour is that the confidential text should be printed to the console but not the run log

**Comment by hobbit1983** [comment]
Got a fix for this.  However there is a small problem, we log the message to say that the framework is shut down.  However at that point the confidential text service has also gone so we cause an NPE

**Comment by hobbit1983** [comment]
PR in to merge the fix for this.

**Comment by hobbit1983** [comment]
@james-ashman can you check this again for me please

**Comment by james-ashman** [comment]
@hobbit1983 Just checked and seems to be working as expected now, good work!

**Comment by hobbit1983** [comment]
Cool - thanks
