### ISSUE TITLE
commons.io vulnerable in framework

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#675]
In Apache Commons IO before 2.7, When invoking the method FileNameUtils.normalize with an improper input string, like "//../foo", or "\\..\foo", the result would be the same value, thus possibly providing access to files in the parent directory, but not further above (thus "limited" path traversal), if the calling code would use the result to construct a path value.

Ideally need to upgrade commons.io to 2.7 or higher - but this will be hard due to an eclipse limitation in oxygen and photon

**Comment by Michael-Baylis** [comment]
commons-io upgraded to 2.9.0 which is the latest at this time
