### ISSUE TITLE
Can Galasa be used for IMS screens

### ISSUE THREAD

**Issue by Shalini174** [galasa-dev/projectmanagement#684]
Hi Team,

I wanted to check if Galasa can be used for testing IMS screens, if yes, are there documentation for the setup/configuration.

**Comment by Shalini174** [comment]
Hi Team,

Any leads will be helpful, please suggest.

**Comment by Michael-Baylis** [comment]
Are you referring to 3270 screens?   If so, yes,  however,  there are reports that occasionally IMS doesn't like the datastream,  but we haven't narrowed it down yet.

**Comment by Michael-Baylis** [comment]
No reply or updates,  so closing
