### ISSUE TITLE
Increase the IVT ONLY testing of the zosBatch manager

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#697]
In consultation with James Davies, increase the unit and ivt testing of the zosbatch zosmf manager manager. Use the reports found at http://cicsk8sm.hursley.ibm.com:31530/ .

**** Write the IVTs in the zos Manager in such a way that the same IVT can be run with the zosmf and RSE implementations.   Concentrate on the zosmf implementation when writing the tests.

A judgement will need to be made on how much testing is required to give confidence that the manager can be released to DfG.

Please note, the code should be TESTED, not simply driven to improve the code coverage statistics, in other words, ensure the code has worked the way that it was expected rather than simply exercising the code. No powermock please, and keep the mocking to a minimum.

Keep the PRs small and add James and Michael as reviewers for all PRs.

**Comment by hobbit1983** [comment]
Should mostly be there still need to run with the RSE implementation and check cc

**Comment by Michael-Baylis** [comment]
Will and I believe there is enough coverage on zOSBatch for zOS/MF and RSE
