### ISSUE TITLE
Increase the IVT ONLY testing of the zos 3270 manager

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#703]
In consultation with James Davies, increase the unit and ivt testing of the artifact manager. Use the reports found at http://cicsk8sm.hursley.ibm.com:31530/ .

A judgement will need to be made on how much testing is required to give confidence that the manager can be released to DfG.

Please note, the code should be TESTED, not simply driven to improve the code coverage statistics, in other words, ensure the code has worked the way that it was expected rather than simply exercising the code. No powermock please, and keep the mocking to a minimum.

Keep the PRs small and add James and Michael as reviewers for all PRs.

**Comment by hobbit1983** [comment]
Found a potential defect with this https://github.com/galasa-dev/projectmanagement/issues/721

**Comment by hobbit1983** [comment]
Added a set of tests for this and am happy with the level of code coverage - closing
