### ISSUE TITLE
Issue with retrieveJar failing to properly inspect versions

### ISSUE THREAD

**Issue by james-ashman** [galasa-dev/projectmanagement#705]
The retrieveJar method within BundleResourcesImp.java is currently failing to compare versions and instead treats files as though there is no attached version.

**Comment by james-ashman** [comment]
I am currently working on a fix for this issue.

**Comment by hobbit1983** [comment]
So looking at the retrieveJar method AFAIK it does the following:

> assumes that the jar file will have the version in the file name - if it does then it assumes this is correct and goes with that
> 
> if no file matches then we get a list of all the jar files regardless of filename, we then go an check the content of the jar for the symbolic name, if we get a match then we check the manifest for the bundle-version.  We use this information to gert the best match for the requrested jar.

With that in mind what problem are you seeing in that method?

**Comment by james-ashman** [comment]
I believe what I was thinking is that if the jar did not explicitly have a Bundle-Version in the manifest and instead had another type of version parameter, this would be overlooked as though the file itself did not have a version. If this is an intended function I shall close the issue.
