### ISSUE TITLE
Issue with listDirectory adding an extra dot for each element iterated over 

### ISSUE THREAD

**Issue by james-ashman** [galasa-dev/projectmanagement#706]
The listDirectory method within BundleResourcesImpl.java is adding a "." to the file extension each loop which works for the first element but for each additional element afterwards an extra "." is added so .jar becomes ..jar etc.

**Comment by james-ashman** [comment]
I am currently working on a fix for this issue.

**Comment by hobbit1983** [comment]
When you have a PR for this issue can you link it to this issue please @james-ashman

**Comment by james-ashman** [comment]
@hobbit1983 PR is linked
