### ISSUE TITLE
Create new CLI which can submit and monitor ecosystem runs

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [galasa-dev/projectmanagement#708]
We are moving from using jenkins to Gitlab CI. It will be nice to have support for running the Galasa tests using Gitlab CI.

**Comment by Michael-Baylis** [comment]
We are experimenting with a CLI for running tests in an ecosystem.   This should work perfectly in gitlab

**Comment by kathysychan** [comment]
We are planning to use GitLab CI in our next Wazi Dev zTrial scenario. We would like to be able to invoke Galasa tests using Gitlab CI as part of the scenario. 

Michael, would you be able to provide an outlook of when this function might be available?

**Comment by Michael-Baylis** [comment]
Internally, we want a cli for submitting and monitoring test runs for our Tekton pipeline.
So we have a requirement for Azure, gitlab and Tekton.
I will start working on this asap.   So by end of June at the latest, subject to other priorities.

**Comment by Michael-Baylis** [comment]
Looking to release the first pass of the galasactl cli for submitting and monitoring runs in 0.17.0, which is the next release,   probably in 2-3 weeks time.

**Comment by Michael-Baylis** [comment]
whats left to do:-

shared environments
yaml report
junit report

**Comment by Michael-Baylis** [comment]
and need --throttleFile so can dynamically alter the throttle in flight

**Comment by Michael-Baylis** [comment]
add --requestor and --requestType flags

**Comment by Michael-Baylis** [comment]
--reportYaml  --reportJson --reportJunit all done

**Comment by Michael-Baylis** [comment]
--requestor and --requestType complete

**Comment by Michael-Baylis** [comment]
--throttleFile added

**Comment by Michael-Baylis** [comment]
--throttleFile added

**Comment by Michael-Baylis** [comment]
CLI runs subcommand is complete.   Will be available in 0.17.0.   It will also need an ecosystem at 0.17.0.
