### ISSUE TITLE
z/OS Batch Manager does not document the @ZosBatchJobName annotation

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#713]
In https://galasa.dev/docs/managers/zos-manager
I would expect to see documentation of the @ZosBatchJobname annotation and the IZosBatchJobname Type that it provisions.  Not sure if this is missing in the manager code or not being pulled by the documentation

@CaroMac can you take a look

**Comment by hobbit1983** [comment]
Fixing now

**Comment by hobbit1983** [comment]
@CaroMac can you check the doc that I have added and massage it onto the site please?

**Comment by CaroMac** [comment]
Thanks Will, taking a look.

**Comment by hobbit1983** [comment]
Thanks @CaroMac all good or do I need to change anything?
