### ISSUE TITLE
Galasa Eclipse plugin does not support a test method in the Test Method box

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#715]
Although I can search the selected class to run a specific test method, this value is ignored and not persisted.

**Comment by alfonso-rios-ibm** [comment]
I am facing the same issue, even when I select an specific test method to run the entire test suite is executed

<img width="867" alt="image" src="https://user-images.githubusercontent.com/48730438/120344864-989e8600-c2bf-11eb-8c2c-f6270718396b.png">

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
