### ISSUE TITLE
Galasa 0.15.0 Eco start fails with "no main manifest attribute, in /operator.jar"

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#723]
Henry Bunch Yesterday at 1:03 PM
Eco start fails with "no main manifest attribute, in /operator.jar"
Status: Downloaded newer image for docker.galasa.dev/galasa-docker-operator-amd64:0.15.0
no main manifest attribute, in /operator.jar

**Comment by Michael-Baylis** [comment]
This is fixed in 0.16.0
