### ISSUE TITLE
File manager (zosmf) doesn't always call the image/machine for new information.

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#727]
Methods on IZosUNIXFile don't all reach out to the specified image/machine to retrieve new information. Possibly this is intended functionality, but would like to check.

Methods affected:
* `getFileType()`
* `getLastModified()`
* `getUser()`
* `getGroup()`
* `getSize()`
* `getUnixPath()` \*
* `getFileName()` \*
* `getDirectoryPath()` \*

> Notes (\*)
> Not sure of the implications if these were to return a different value to that with which they were initialised. e.g. A IZosUNIXFile is initialised with a file path (including file name), if the file name was to change on machine/image, the new name wouldn't be returned without the IZosUNIXFile instance also being updated with the new name.

### Example
```
String filePath = "/u/exampleuser/directory/file"
IZosUNIXFile unixFile = fileHandler.newUNIXFile(filePath, imagePrimary);
int size = unixFile.getSize();
```

The `getSize()` implementation (zosmf and rseapi) both return `this.fileSize;`.
Where I believe they should be making a call to the image/machine to fetch new information each time.

To reproduce:
```
unixFile.create();
unixFile.store("Hello World"); // or larger strings
assertThat(unixFile.getSize()).isGreaterThan(0);
```
After executing the code above I would expect `unixFile.getSize()` to return a value larger than zero **without** having to first call `setAttributeValues()` or `setFileSize()`.  (alas, it does not).

**Comment by DavidXRoberts** [comment]
I've checked this one out and it's already been fixed
