### ISSUE TITLE
Jenkins property is not configuring the prefix at all

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [galasa-dev/projectmanagement#728]
Even though I set the jenkins property **framework.request.type.JENKINS.prefix=J**  the prefix is still **U** instead of **J**

**Comment by Michael-Baylis** [comment]
The Galasa team will not be providing a Jenkins plugin from 0.17.0 onwards.   Instead we will be providing a CLI, called galasactl which you can use within Jenkins or any other devops tooling.

galasactl will default to a requestor type of "CLI", which can be overridden from a flag.  Example:-

galasactl \
         runs prepare \
         --bootstrap http://cicsk8sm.hursley.ibm.com:31410/bootstrap \
         --stream inttests \
         --portfolio test.yaml \
         --package local \
         --package kubernetes

galasactl \
         runs submit \
         --bootstrap http://cicsk8sm.hursley.ibm.com:31410/bootstrap \
         --portfolio test.yaml \
         --throttle 6 \
         --poll 10 \
         --progress 1 \
         --reportyaml tests.yaml \
         --reportjson tests.json \
         --reportjunit junit.xml

**Comment by Michael-Baylis** [comment]
Closing this issue as Jenkins will be decommissioned
