### ISSUE TITLE
Jenkins build runs forever when having wrong test name

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [galasa-dev/projectmanagement#730]
I ran a jenkins build but I had a typo in the test name in the jenkins pipeline, but the build is running forever with status **allocated** even when the docker container in the ecosystem does not longer exists.

`tests: ["nazare.systems.cicd.galasa.tests/dev.galasa.nazare.tests.WrongTestName"]`

I think the jenkins build should finished with failure status and marked the galasa test as failed too or something like that.

**Comment by Michael-Baylis** [comment]
Yep,  you are correct,  it is on my list to fix as this annoys me 10 times a day

**Comment by Michael-Baylis** [comment]
The engine will terminate cleanly and mark the run as finished if the bundle or testclass cannot be found.

This will be in the 0.17.0 release
