### ISSUE TITLE
Enhancement to generate and return random job names

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#739]
We currently assign unique, random APPLIDs (and therefore resulting job names) when provisioning CICS and those APPLID identifiers are used throughout test for each instance. To have unique ones per instance is necessary for checking and debugging. 

I'd like to be able to use something like #getRandomJobName() in Galasa in order to generate a random suffix to a given prefix (e.g., "FRED") so that the APPLID to use for that instance will be, e.g., FREDU4WE and associated job names will be easily identifiable.

**Comment by Michael-Baylis** [comment]
@ZosBatchJobname
public IZosBatchJobname jobname1;

Is that sufficient?

**Comment by jasonrhughes** [comment]
Ah thanks - I wasn't aware of that. It returns job names prefixed GAL (e.g., GAL91GLX, GALTD5DA etc.) which is nice and random but we'll need to supply our own 4 char prefix instead. I could do this in the tests (e.g., supply the stub FRED and use just the last 4 chars returned from IZosBatchJobname to get something like e.g., FRED1GLX), assuming I'm not missing a method here to supply a stub as part of the call and have it return a job name based on that.

If I'm not missing anything, please feel free to close and I'll work with this. Thanks.

**Comment by hobbit1983** [comment]
I do think that this is something that the coreManager should be able to do.  If I read the og correctly it might be used for anything not just job names.  In which case it seems weird to use zosBatch to just get a unique name - could easily put something into core as a QoL improvement

**Comment by Michael-Baylis** [comment]
There is the resource pooling service that can do this.    Just need to figure out if it is exposed to tests or not.

**Comment by Michael-Baylis** [comment]
However,  if you are using this to generate unique jobnames for further testing,    by the test generating the unique name,  it up to the test to ensure that the jobname is not in use on the system already.   a randonmly generated name does not ensure it is "unique" on the zos image.    The @ZosBatchJobname guarentees that the jobname is not is use as the GAL prefix is reserved for Galasa and the batch manager coordinates to ensure uniqueness across the ecosystem.
If your test uses FRED*,  then there is the posibility there will be collisions.
I think you need to ask yourself if you really care what the jobname is, or is this just an historical thing.  Why does it need to be FRED*

**Comment by jasonrhughes** [comment]
For the z/OS userID in use on our system, the APPLID - which is also the STC ID - needs to have a particular allowed prefix otherwise our provisioning won't work. 

Thinking about this, maybe I should ask to give the userID the added ability to have GAL* as allowed APPLID/STCs if that's possible. In the meantime I have something I can use that works well, so this isn't urgent at all.

**Comment by jasonrhughes** [comment]
The userID is now also allowed to use started tasks beginning GAL and so I'm able to use the suggested IZosBatchName provided name without changing it. That will probably be the best way forward, as I migrate things over to Galasa.

Many thanks for your help and suggestions. I'll close this now.
