### ISSUE TITLE
Enhancement to have getHome() for z/OS images

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#740]
I'm able to use ILinuxImage#getHome() to return the home directory for the Linux image user. I'd like to be able to do the same for z/OS, i.e., IZosImage#getHome(), to return the home directory for the USS user.

This is currently not available for z/OS images so raising this issue to request it to be added. Many thanks.

**Comment by Michael-Baylis** [comment]
Not sure what to do about this one.    With Linux,  you get a userid that will be purged so we don't need to worry about housekeeping.   With zOS, you will tend to get JATP or GALASA,  so housekeeping becomes an issue.

I think we simply return IZosImage.getRunTemporaryUNIXPath()

**Comment by DavidXRoberts** [comment]
`IZosImage#getHome()` will be avaiable in the next 0.19.0 build
