### ISSUE TITLE
Docker Container does not check that it is already started

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#75]
IDockerContainer.start()
IDockerContainer.start()

the Docker Container does not check it is already running before attempting to allocate slot etc.

**Comment by Jimbo4794** [comment]
The containerImpl, does do this check before attempting to start the container
![Screenshot 2020-01-20 at 10.58.54.png](https://images.zenhubusercontent.com/5dde88195d4d9e0001e18c6f/97a603bc-8b88-49de-b011-c5cb76c04934)

**Comment by Michael-Baylis** [comment]
sorry was wrong.
