### ISSUE TITLE
Review the release.yaml process

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#760]
To update the a manager version,  the process is still a bit cumbersome.

Investigate in having a release.yaml per repo,   so a manager bump is only one PRm, build,  not PR, build, PR, build.

**Comment by techcobweb** [comment]
We already have a release.yaml per repo, which is packaged as a maven artifact, so that the OBR project can download dependencies of the correct level, and use them to build the OBR.
So this story can be closed I think.
