### ISSUE TITLE
zos3270 Integration tests are broke

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#764]
see https://cicscit.hursley.ibm.com/phoenix2/collection/60951575e4b048f3470abbbb

I have not investigated further,   if I had to guess,  the CICS region is down

**Comment by hobbit1983** [comment]
will take a look after the playback

**Comment by hobbit1983** [comment]
resolved

**Comment by Michael-Baylis** [comment]
and the problem was?

**Comment by hobbit1983** [comment]
as you diagnosed.  CICS region was not up - it is now

**Comment by Michael-Baylis** [comment]
still failing,  J23883 and J23939

**Comment by hobbit1983** [comment]
taking a look

**Comment by hobbit1983** [comment]
GMTEXT incorrect

**Comment by hobbit1983** [comment]
R151 - passed - closing
