### ISSUE TITLE
The DSS slot allocation/cleanup is broken

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#77]
The current way the DSS is used within the Docker Manager is broken and can leave the used slot count out of sync with the actual used count.

The dss.docker.server.default.current.slots must be incremented in the same command as the dss property 
dss.docker.slot.default.run.L1.SLOT_L1_0 is set to active.

Same for cleanup,   the current.slots count must be decremented in the same command as the slot is "freed".  

This is to prevent the counter getting out of sync with the number of "active" or "freed" slots.   It is possible (and because it is possible, likely) that the engine can terminate between the command to increment the slot count and the active slot being recorded.   Therefore, if this happens a few times, we could run out of virtual slots and the resource management routines can't clean anything up as the slot is not "active"

**Comment by Jimbo4794** [comment]
Have corrected the allocate dss setting. There is no need to change the free-ing of a slot, as that does remove the slot and properties at the same time. There is a method called dssDelete() which is used by the resource monitor for deleting stale properties, is this what you were referring too?

**Comment by Michael-Baylis** [comment]
deleteStaleDssSlot. is doing something different to freeDockerSlot and is not handling the "free" correctly.

the slot count swap and the setting of the "free" must happen in the same update.

I suggest that you copy the code from "freeDockerSlot" to deleteStaleDssSlot,  and then call deleteStaleDssSlot

the endoftest clean up should be identical to rm clean up

**Comment by Michael-Baylis** [comment]
look better
