### ISSUE TITLE
Docker Ecosystem Documentation Error

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#790]
The documentation on this page: https://galasa.dev/docs/ecosystem/installing states:

```
In Eclipse, you can edit the bootstrap by completing the following steps:

1. Select Eclipse > Preferences > Galasa
2. Update Bootstrap URI to point to http://{hostname}:8080/
3. Apply and close the preferences
```

The correct url should actually be `http://{hostname}:8080/bootstrap`(note the inclusion of `/bootstrap` at the end). Otherwise an error is encountered when initialising the framework:

```
'Initialise Galasa Framework' has encountered a problem.

Failed

Falied
  http://{hostname}:8080/
```

**Comment by CaroMac** [comment]
have published as part of 0.18.0 https://github.com/galasa-dev/galasa.dev/pull/296
