### ISSUE TITLE
VTP Manager

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#800]

**Comment by pauline-andrews** [comment]
I asked Luke on Slack to confirm the date we're working towards. He has replied : "Kim Bailey (the PM) has said right now its the 25th of feb". 
I've gone back asking for confirmation that we'd be aiming for IBMDfG refresh complete on that date.

**Comment by hobbit1983** [comment]
@pauline-andrews can we close this Epic now?

**Comment by pauline-andrews** [comment]
Hi @hobbit1983 yes, good point. I'll close now.
