### ISSUE TITLE
RSE problem with returning the wrong JOBID

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#802]
RSE returns the wrong jobid on occasions,   needs to be raised with the RSE team

**Comment by DavidXRoberts** [comment]
RTC defect [35117](https://jazzk01.hursley.ibm.com:9443/ccm/web/projects/Zeus#action=com.ibm.team.workitem.viewWorkItem&id=35117) created

**Comment by DavidXRoberts** [comment]
The defect shows that the defect is fixed. I've asked when and how we can pick up this fix

**Comment by DavidXRoberts** [comment]
RTC defect update:

Hi David @david.roberts@uk.ibm.com , our next PTF is scheduled for October 29, but we do have an early (pre-release) October 1 drop for ADCD if you need to have something earlier.

**Comment by hobbit1983** [comment]
Just added a dep to remind us to add the tests that the RSE bug caused to fail back into the testing

**Comment by DavidXRoberts** [comment]
Oneticket raised [https://oneticket.devit.ibm.com/tickets/119017](https://oneticket.devit.ibm.com/tickets/119017)

**Comment by hobbit1983** [comment]
awesome - thanks Dave

**Comment by hobbit1983** [comment]
Added a comment on the ticket to see if there is a rough outlook on time

**Comment by DavidXRoberts** [comment]
Update on ticket from Carl:
Hi Will ...... we have a large number of tickets at the moment so I may not be able to action this ticket before the end of this week or maybe next week.

**Comment by hobbit1983** [comment]
Thanks @DavidXRoberts

**Comment by DavidXRoberts** [comment]
Update from Carl:
_Hi Will ... The PTF ( UI77777) was applied to ZOS204 sysres 5th November and the 2.4 systems in PLEX2 were IP'ed on 10th November so it should be picking it up ..... Exception to this is MVS2D which is running off a static ZOS204 system ....._

My response:
_Hi Carl, 
Sorry I should have been more specific in this request, the server needs to be installed. Ticket https://oneticket.devit.ibm.com/tickets/82199 contains details of the last install.
Thanks,
Dave_

**Comment by hobbit1983** [comment]
Checked the ticket in Dave's absence.  MV2C and MV26 appear to have been updated and a request to server:6800/rseapi/api/v1/info/serverdetails shows the rse api level of 1.0.7 (which is what we think is needed). 2D is still back level so I have asked if the changes can be applied there as well.  However the CPS is using 2C so we could consider this closed and add all the RSE tests back into the rotation

**Comment by DavidXRoberts** [comment]
RSEAPI on MV2D/C and returns the correct jobid. MV26/8 not working. I'll investigative why and raise a new ticket for it.
@hobbit1983 not sure where the RSE tests are currently running, but they should be limited to MV2C or MV2D until the ticket is resolved.

**Comment by hobbit1983** [comment]
They are restricted

**Comment by DavidXRoberts** [comment]
Excellent,
Oneticket raised fro broken servers https://oneticket.devit.ibm.com/tickets/123466

This issue can be closed if required as the reported problem is fixed.

**Comment by techcobweb** [comment]
Thanks very much @DavidXRoberts . Closing now.
