### ISSUE TITLE
CLI command to get the test run artifacts from an ecosystem

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [galasa-dev/projectmanagement#803]
As a user of galasa, I want to be able to download all artifacts associated with a test run ID, so I can view the results collected by the test, and the runlog, in order to diagnose a problem with the test or the tested system.

This story has been broken down into several parts:
- A REST interface where you could download the artifacts from.
- A CLI which uses the REST interface to perform the download operation.
- The documentation of the REST interface should appear in the galasa-dev web site reference page.
- Optionally zip-up the downloaded artifacts.

These smaller stories are stories of this Epic.

**Comment by techcobweb** [comment]
We now plan to allow the CLI to download everything about the runid rather than just the run log.
