### ISSUE TITLE
Unsatisfied requirement: Linux Manger version needs manual override in pom

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#804]
I have the Linux Manager in my parent pom. With Galasa 0.17.0 and 0.18.0 a test run complains that it can't find the managed version of 0.17.0:

**Unsatisfied requirement: package:(&(package=dev.galasa.linux)(version>=0.17.0)(!(version>=1.0.0)))**

To get around this I have to override the managed version in my pom, to force it to 0.15.0 by adding a version line:

```
			<groupId>dev.galasa</groupId>
			<artifactId>dev.galasa.linux.manager</artifactId>
			<version>0.15.0</version>
```

There's a warning in the pom that the managed version of 0.17.0 is being overridden, but tests do now run.

**Comment by hobbit1983** [comment]
I have check - linux manager now appears in the obr and bom correctly - so this should be fixed.  If not let us know and I will update
