### ISSUE TITLE
Doc incomplete for "Creating an example Galasa project using Gradle"

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#810]
The documentation for "Creating an example Galasa project using Gradle" assumes that the user has downloaded the zipped repository and is missing for uses that want to use the remote repository.

**Comment by CaroMac** [comment]
Thanks, I will take a look.

**Comment by CaroMac** [comment]
Working on this now - will send out for review / test later this week or early next.

**Comment by CaroMac** [comment]
now published
