### ISSUE TITLE
Problems with Gradle examples in Eclipse

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#811]
Eclipse does not recognise the Gradle Examples as Gradle projects.
First, they have a strange format:

![Gradle_Examples](https://user-images.githubusercontent.com/29795477/134012000-6735b2b6-774d-4952-855b-085466250892.jpg)

and should look more like:

![Gradle_Examples_after](https://user-images.githubusercontent.com/29795477/134012208-be6f723d-83e7-4ee9-9445-0e47a1ac45ce.jpg)

This is because Eclipse doesn't know these are Java source folders. This can be fixed using new>Source Folder for src/main/java and src/main/resources and make sure the Eclipse config file is stored in Git.

Secondly, projects fail to build with:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\workspace\Galasa\Galasa_Plugin_01\dev.galasa.simbank.parent\dev.galasa.simbank.manager\build.gradle' line: 3

* What went wrong:
Plugin [id: 'biz.aQute.bnd.builder', version: '5.3.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'biz.aQute.bnd.builder:biz.aQute.bnd.builder.gradle.plugin:5.3.0')
  Searched in the following repositor
```

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
