### ISSUE TITLE
Write the Distributed WMQ  Manager

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#835]
We need a message broker in the demos,  so write a Distributed WMQ Manager to provide this.  Needs to be able to create/retreive queues and provide access via the java.jms? packages

**Comment by hobbit1983** [comment]
A first draft is now mostly there. Just need to pull the configuration from the CPS

**Comment by hobbit1983** [comment]
Now that I have the annotations defect out of the way - this is a priority again.  Should mostly be there, the only thing that is missing is the configuration though the CPS

**Comment by hobbit1983** [comment]
Just on a back and forth with review comments - then this will be done

**Comment by hobbit1983** [comment]
All review comments passed and approved.  Just need to squash and re-push and this can go to release candidate
