### ISSUE TITLE
Doc update: Ecosystem on Docker page needs to have Jenkins references removed

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#880]
This page in the doc.:
https://galasa.dev/docs/ecosystem/installing
talks about installing an ecosystem under Docker and states there should be nine resulting containers, one of which is Jenkins. It later describes running SimBankIVT using Jenkins to verify the installation.
It seems Jenkins has been removed, in favour of the Galasa CLI. When installed, only eight containers are present; Jenkins is absent.
The doc. should be updated to reflect this.

**Comment by Michael-Baylis** [comment]
The docker operator no longer provides a jenkins instance

**Comment by CaroMac** [comment]
thank you will update

**Comment by CaroMac** [comment]
https://deploy-preview-302--galasa.netlify.app/docs/ecosystem/installing
