### ISSUE TITLE
Documentation update for Beta release of CEMT Manager

### ISSUE THREAD

**Issue by pauline-andrews** [galasa-dev/projectmanagement#934]
When testing has been done to satisfy Beta level of the CEMT manager, update the Galasa.dev Website.

**Comment by hobbit1983** [comment]
@CaroMac since this manager is in the distributed release this is probably no longer needed.  If there are any updates to be made to the content then this can be done when we move the doc to the new template and structure - if you agree can you close this issue?

**Comment by CaroMac** [comment]
agreed - closing
