### ISSUE TITLE
Consider how we document the internal managers for the CICS TS team

### ISSUE THREAD

**Issue by pauline-andrews** [galasa-dev/projectmanagement#937]
Reminder issue for Michael and Dave to consider how we should document internal managers.

**Comment by CaroMac** [comment]
If it is for internal use only, could we document these Managers in an internal GitHub Pages or the CICS wiki?

**Comment by hobbit1983** [comment]
@CaroMac can we mark this as done since our conversation?  If so can we update this work item with our findings please?
