### ISSUE TITLE
Shell issue command should return exit code along with command output

### ISSUE THREAD

**Issue by jansengsy** [galasa-dev/projectmanagement#942]
Currently, when using the CommandShell object, the return only sends the output from the shell and not the command error code. I thought it might be nice to add this too. 

I have spent a bit of time poking around the IPNetworkManager and the SSHClient class and I think we can use the [GetExitStatus](https://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/Channel.html#getExitStatus---) method to return this value. There are a couple ways we could do this:

1. We could simply append the exit code to the return value of the retrieveOutput method within the SSHClient class. [(here)](https://github.com/galasa-dev/managers/blob/4791283d4b3653347f2610021da2d911b0349faf/galasa-managers-parent/galasa-managers-comms-parent/dev.galasa.ipnetwork.manager/src/main/java/dev/galasa/ipnetwork/spi/SSHClient.java#L486).

2. We could overload the retrieveOutput method to include a boolean option to include the exit code in its response. I think this method would be better because it would be a less destructive change. 

I am aware that either of these solutions will require multiple changes in the code base (within the ILinuxManager, for example), but I think it would make the experience a lot better and more consistent with other similar libraries.

**Comment by Michael-Baylis** [comment]
The getExitStatus does not work consistently across all platforms, sometimes it returns what you expect,  other times, like windows it returns the shell exist code,  not the command exit code.

Also, we don't want to encourage testers to rely on the exit code.   the exit code is not implemented consistently across commands.

Testers should use the message output to verify the success of the command and it did what was expected.  rc=0 could mean anything.

&& echo response=$? is only used as a last resort, when the command does not return any meaningful output on success.
