### ISSUE TITLE
Confirm what the url in the plug in install documentation should be set to

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#952]
The following topics 
https://galasa.dev/docs/getting-started/installing-online and 
https://galasa.dev/docs/getting-started/installing-offline
contain urls with the word "master" in:
<repositories>
                <repository>
                    <id>galasa.repo</id>
                    <url>https://nexus.galasa.dev/repository/master</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>galasa.repo</id>
                    <url>https://nexus.galasa.dev/repository/master</url>
                </pluginRepository>
            </pluginRepositories>

in the settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"

This issue is raised after discussion with Mike to confirm what the url should be.

**Comment by Michael-Baylis** [comment]
I assume this has been updated already as can't find the references in the docs that you have indicated
