### ISSUE TITLE
dev.galasa.docker.internal.DockerVolumeImpl.createDockerfile should be using artifact manager templating

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#963]
in dev.galasa.docker.internal.DockerVolumeImpl.createDockerfile(String, Map<String, String>)

            for (String key: subs.keySet()) {
            	dockerfileTemplate = dockerfileTemplate.replace(key, subs.get(key));
            }

is being used to provide template capabilities.    The method should be using the templating capabilities of the artifact manager instead.  call retrieveSkeletonFileAsString instead of retrieveFileAsString

**Comment by hobbit1983** [comment]
PR in to resolve this
