### ISSUE TITLE
Tag of the isolated docker image is incorrect

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#966]
On https://galasa.dev/docs/getting-started/installing-offline,

Run the container by using the following command:

docker run -d -p 8080:80 --name galasa galasadev/galasa-distribution:0.19.0

Should be latest,  not the version,  we changed this so the docs do not need to keep in step.

also,  needs to be icr.io/galasadev/galasa-distribution:latest

The (2.) point is not tabbed the same as 1 and 3

**Comment by CaroMac** [comment]
updated - preview available here https://deploy-preview-331--galasa.netlify.app/docs/getting-started/installing-offline
