### ISSUE TITLE
Ecosystem docker installation page needs altering for icr.io

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#967]
On https://galasa.dev/docs/ecosystem/installing

galasaRegistry: docker.galasa.dev
needs to be 
galasaRegistry: icr.io

and would be helpful to bump the versions to 0.20.0

docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v {path}/config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.17.0

needs to be icr.io/galasadev/galasa-docker-operator-amd64:0.20.0

**Comment by CaroMac** [comment]
updated - preview available here https://deploy-preview-331--galasa.netlify.app/docs/ecosystem/installing
