### ISSUE TITLE
Docker Manager Retrieve File as String

### ISSUE THREAD

**Issue by rsomers1998** [galasa-dev/projectmanagement#97]
Retrieve File would be better suited to returning as an input stream in the cases where a non-test object is being retrieved (eg binary, image etc)

**Comment by Michael-Baylis** [comment]
will enhance this in release 0.5.0 or 6

**Comment by Jimbo4794** [comment]
@Michael-Baylis, Im happy to make this change. Very quick as i originally retrieve a input stream and convert to a string to match what you wanted in the IVT.

**Comment by Michael-Baylis** [comment]
leave it for now.   Only a couple of days until release.  Can do it in 0.5.0

**Comment by Michael-Baylis** [comment]
changed my mind.   if you can do it and richard can test it,  do it.

**Comment by Jimbo4794** [comment]
changed, will push with the #98 changes too

**Comment by Jimbo4794** [comment]
fixes contained in PR 76
