### ISSUE TITLE
Enable SecVuln scanning of Maven dependencies by OSS Index and Whitesource

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#985]
The SecVuln scanning of all the dependencies of Galasa is inconsistent and a manual process.   We need to automate this and ensure that the best possible reporting is acheived with the tools available.   At the moment, the tool that is providing the best results is Sonatype OSS Index.   However, as IBMers, we also need to ensure Galasa is scanned by Whitesource ETS.

Galasa is built by Gradle for various reasons,  but Gradle is not supported that well in the scanning tools,  Maven is the better option as the dependencies we use are from Maven Central.   So this Issue will "fiddle" the process to enable the best scanning reporting and present the data to our product owners for approval, by creating a psuedo Maven project to expose the full dependency chain.

Jade will write a scanning pipeline that will generate the psuedo maven project by extracting the dependencies from the component main pom.xml, in the following order:-
1. dev.galasa.uber.obr
1. isolated
1. mvp
1. k8s operator
1. docker operator
1. simplatform

The pipeline will consist of the following steps, using uber.obr as example :-
1. Create a new parent maven project called dev.galasa:security-scanning:x.xx.x (current version from obr release.yaml). include the OSS Index maven plugin.
1. Obtain the pom.xml (generated by gradle) of the uber.obr
1. Strip out everything but the dependencies and the project identification, change the packaging to jar
1. Add a parent element for the scanning parent.
1. Add as a module of the parent in it's own subfolder of the parent.
1. For each dependency of the uber.obr that has a groupid of dev.galasa,  repeat the process:-
    1. Obtain the pom.xml from the maven repo
    1. Strip out everything but the dependencies and project identification change the packaging to jar
    1. Replace the parent with the scanning parent
    1. Add as a module of the parent in it's own subfolder of the parent.
1. At this point, every dependency of ubr ober should be a module of scanning, if dev.galasa
1. Push this project to the galasa/security-scanning project on GHE, so Whitesource ETC can take a stab at it.
1. Build the maven project, with the validate goal.
1. Build the maven project with dependency tree
1. Each module should have a OSS Index report of any vulnerabilities and it's dependency tree.
1. Process each report and merge into a single yaml file, information we need is:-
    1. The CVE number
    1. The base dev.galasa projects this CVE came from
    1. Is it a direct or transient dependency (detail dependency chain)
    1. Any fix available (not sure this is possible)
1. At this point we would merge in the harbor security scan (to be written after this).
1. Using an "override" yaml file on projectmanagement repo,  process the yaml files and produce a mardown document for management approval.
    1. Needs to highlight new vulnerabilities
    1. Needs to highlight accepted vulnerabilities
    1. Each vulnerability in a table needs to be on a single line so that the diff in github becomes relevant
1. Raise a PR for any difference in the document with the "release" repo on GH.

This is a living process,  as we work through it, we will find new things to report on or ignore.

**Comment by jadecarino** [comment]
- I have developed the three galasabld commands necessary for this: maven to create the pseudo maven projects, ossindex to scan the maven projects and create a yaml file of all vulnerabilities and report to parse the yaml into markdown
- I have made a Tekton pipeline and confirmed this works in my namespace: the pipeline runs the three galasabld commands, and pushes the pseudo maven projects to the security-scanning repo for Whitesource and pushes the markdown to test-release for approval
- In terms of next steps a) my galasabld code should probably get a review from someone else who is confident in Go b) the markdown report should be reviewed by its intended audience to check if it is readable, gives enough/too much info etc c) after those steps the Tekton pipeline needs to be set up in the galasa-prod namespace and scheduled to run on a regular basis (originally we were going with daily but can discuss as a team if still suitable)

**Comment by jadecarino** [comment]
@hobbit1983 no - I'd say I'm happy with my code and currently working with James to get the pipeline set up. Once managers start reviewing the markdown report there might be feedback on the report itself so can be adjusted as we work with it. But nothing needs to be reviewed as such.
