### ISSUE TITLE
Finish development of SemCicsImpl

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#987]
The following methods need to be developed. When used they throw "Not developed yet" exceptions:
- getUssHome
- getJvmProfileDir
- getJavaHome

**Comment by jadecarino** [comment]
@eamansour FYI - duplicate of your story I believe.

**Comment by eamansour** [comment]
Thanks Jade. Closing this as a duplicate of https://github.com/galasa-dev/projectmanagement/issues/1515
