### ISSUE TITLE
galasactl panics when no bootstrap is provided

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#989]
```
hobbit@Hobbit's MacBook Pro Downloads % ./galasactl-darwin-amd64 runs prepare -p ecoRuns.yaml 
2022/03/22 13:18:51 Galasa CLI - Assemble tests
panic: unsupported bootstrap

goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/api.loadBootstrap()
	/workspace/git/cli/pkg/api/api.go:75 +0x3c3
github.com/galasa.dev/cli/pkg/api.InitialiseAPI(0x0, 0x0, 0x1)
	/workspace/git/cli/pkg/api/api.go:38 +0x98
github.com/galasa.dev/cli/pkg/cmd.executeAssemble(0x186f600, 0xc0000aa7a0, 0x0, 0x2)
	/workspace/git/cli/pkg/cmd/runsPrepare.go:69 +0x1e7
github.com/spf13/cobra.(*Command).execute(0x186f600, 0xc0000aa780, 0x2, 0x2, 0x186f600, 0xc0000aa780)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x186f100, 0x103acea, 0x18368a0, 0xc00005e750)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/galasa.dev/cli/pkg/cmd.Execute()
	/workspace/git/cli/pkg/cmd/root.go:28 +0x31
main.main()
	/workspace/git/cli/cmd/galasactl/main.go:14 +0x20
```

Ideally we should provide a message similar to what happens when the portfolio flag is missed:
```
hobbit@Hobbit's MacBook Pro Downloads % ./galasactl-darwin-amd64 runs prepare                
Error: required flag(s) "portfolio" not set
Usage:
  galasactl runs prepare [flags]
```

**Comment by Michael-Baylis** [comment]
cobra does not have the required flag because if --bootstrap is not there,   then it looks for the env variable GALASA_BOOTSTRAP.
but we should have a better message

**Comment by Jimbo4794** [comment]
Yeah i think we should avoid using `panic(err)`, espcially if we are passing an message in the error. We should look just to impl a generic error response for the CLI which can handle any error and print nicely

**Comment by Michael-Baylis** [comment]
need to figure out I8N and position us for multiple languages.   Which is why I was panicing, until I had time to figure out the "correct" way of message support.

**Comment by hobbit1983** [comment]
ah didn't realise it was a Mike panic - looked like a go panic ;) 🙀

**Comment by techcobweb** [comment]
The code currently uses the following coding pattern to get us closer to a supportable I18N position. It's not I18N yet, but at least it concentrates the error message parameter-substitution into a single piece of code.

The pattern is as follows:
```
import galasaErrors "github.com/galasa.dev/cli/pkg/errors"
...
err := galasaErrors.NewGalasaError(galasaErrors.GALASA_ERROR_BOOTSTRAP_URL_BAD_ENDING, bootstrap)
panic(err)
```

panic(err) is a great way of nearly-but-not-quite exiting the program, as we can 'catch' the panic with a deferred function in the main()...

```
	// Catch execution if a panic happens.
	defer func() {
		errobj := recover()
		if errobj != nil {
			fmt.Fprintln(os.Stderr, errobj)
			log.Println(errobj)
			os.Exit(1)
		}
	}()
```

So, right now you are likely to see this appear on stderr:

```
GAL1003E: Bootstrap contents is badly formed. Bootstrap is at %s. Reason is: %s
```

**Comment by techcobweb** [comment]
So... I think we can close this one, and worry about full I18N later on...
