### ISSUE TITLE
Find alternative to IBM Cloud Certificate Manager for p2, Javadoc and web sites

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#993]
Having just updated the certificates for the website, a message was displayed on the page to say that IBM Cloud Certificate Manager is deprecated but can be used until end Sept this year.  We therefore need to replace Certificate Manager. Secrets Manager seems to be the replacement. The loss of Certificate Manager will affect not only the website but also other aspects including the p2 site and Javadoc site.

**Comment by Michael-Baylis** [comment]
Secrets Manager is the replacement for Certificate Manager and there is a Migration Path.  Dont think this will be difficult.

**Comment by CaroMac** [comment]
I was looking at the instructions for the migration here https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-migrate-from-certificate-manager and I noticed that it said "Unlike Certificate Manager, Secrets Manager is a paid service that requires a credit card-equipped account. Review the Secrets Manager pricing plans to understand how migrating to the service might impact your billing. For more information, contact your IBM Cloud sales representative." So it looks like we also need to setup payment for this?

**Comment by Michael-Baylis** [comment]
no, we dont.   dont need to deal with this yet.

**Comment by hobbit1983** [comment]
migration guide is here https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-migrate-from-certificate-manager

**Comment by hobbit1983** [comment]
We have now migrated to secrets manager
