### ISSUE TITLE
Security Vulnerabilities in Jetty

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#997]
jetty-websocket-server
jetty-http
jetty-server

All need to be bumped from 9.4.20v20190813. The version 9.4.46.v20220331 appears to fix all the vulnerabilities but should be simple to move to rather than V11

**Comment by hobbit1983** [comment]
so we will probably have to bump org.apache.felix.http.jetty.  The later versions appear to be vulnerabilities free

**Comment by techcobweb** [comment]
@hobbit1983 Can this be closed ? or is it still a live issue ?

**Comment by hobbit1983** [comment]
It can be closed
