### ISSUE TITLE
Eclipse workspace obr misses dependencies

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#998]
When the eclipse run launcher creates the workspace obr before a test launch it misses dependencies both in the test, parent and obr projects.  Example

I have a parent project, the pom of which has two modules declared (the test and obr projects) and a dependency on an OSGi module in maven central (that doesn't already exist in the galasa uber obr). When the project is built, the dependency is correctly added to the repository.obr file of the obr project.  However when the test is launched, the workspace obr builder skips the obr and parent projects, adds the test project but doesn't add the resource element into the workspace obr for the test dependency and so as the framework initialises it cannot load the test from the workspace obr due to the unsatisfied constraint.

I have tried moving the dependency from the parent project to the test project, tried different dependencies, tried with gradle projects and always got the same result.

If I run the test outside of eclipse and pass the repository.obr file as a parameter to boot.jar then all is well so this only effects local eclipse runs

**Comment by hobbit1983** [comment]
Probably less of a problem now as we are running tests outside of eclipse / using our own OBR projects

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
